API Documentation for Boo-2.0.x: /var/www/Boo-2.0.0/tests/add-user.php File Reference
add-user.php File Reference
Add user test.
Variables
$user = new Boo_User
$userId = $user->getUserId()
Detailed Description
Add user test.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
See also:
Boo_User
Definition in file add-user.php.
Variable Documentation
$user = new Boo_User
Definition at line 23 of file add-user.php.
Referenced by Boo_User::__construct(), Boo_User::getFieldByUserId(), Boo_User::isUser(), Boo_Twitter::newMessage(), and Boo_User::open().
$userId = $user->getUserId()
Definition at line 35 of file add-user.php.
Referenced by Boo_Page::__construct(), Boo_User::auth(), Boo_User::getFieldByUserId(), Boo_User::getSessionUserId(), Boo_User::isUser(), Boo_User::isUserId(), Boo_User::login(), Boo_User::open(), and Boo_User::openImages().
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.