API Documentation for Boo-2.0.x: /var/www/Boo-2.0.0/scripts/camel_case.php File Reference
camel_case.php File Reference
Converts variables in files from underscored case to lower camel case.
Enumerations
enum BASE_DIR
Functions
c ($word)
cDir ($path)
cFile ($filename)
Detailed Description
Converts variables in files from underscored case to lower camel case.
call cDir() with the directory of the files you wish to change.
Will only effect $undersored_words and $this->undersocred_words.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition in file camel_case.php.
Enumeration Type Documentation
enum BASE_DIR
Definition at line 18 of file camel_case.php.
Function Documentation
c ($ word)
Definition at line 22 of file camel_case.php.
References Boo_Helper::toCamelCase().
cDir ($ path)
Definition at line 68 of file camel_case.php.
References cFile().
cFile ($ filename)
Definition at line 26 of file camel_case.php.
References Boo_Helper::getFileExtension().
Referenced by cDir().
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.