API Documentation for Boo-2.0.x: Boo_LoremIpsum Class Reference
Boo_LoremIpsum Class Reference
Lorem ipsum class.
Public Member Functions
__construct ($preload=false)
Default constructor.
Static Public Member Functions
static getWords ($count=20)
Returns a string of words.
static htmlPs ($count=5, array $attrs=array())
Returns an array of paragraphs of lorem ipsum.
static htmlUl ($count=5, array $attrs=array())
Gets an unorderd list of lorem ipsum.
Static Protected Attributes
static $lis = array()
Array of list items.
static $ps = array()
Array of paragraphs.
static $words = array()
Array of words.
Static Private Member Functions
static loadFiles ()
Loads files into class.
Detailed Description
Lorem ipsum class.
This class is used to generate lorem ipsum.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 16 of file LoremIpsum.php.
Constructor & Destructor Documentation
Boo_LoremIpsum::__construct ($ preload = false)
Default constructor.
Parameters:
bool $preload Preload ipsum files.
Returns:
void.
Definition at line 38 of file LoremIpsum.php.
References loadFiles().
Member Function Documentation
static Boo_LoremIpsum::getWords ($ count = 20) [static]
Returns a string of words.
Returns:
string The string of words. Will always end in a period.
Parameters:
int $count[optional] The number of words.
Definition at line 49 of file LoremIpsum.php.
References Boo_Validator::isInt(), and loadFiles().
static Boo_LoremIpsum::htmlPs ($ count = 5, array $ attrs = array()) [static]
Returns an array of paragraphs of lorem ipsum.
Returns:
Boo_Html A collection of paragraphs.
Parameters:
int $count[optional] The number of paragraphs.
array $attrs[optional] The attributes to apply to each paragraph.
Definition at line 77 of file LoremIpsum.php.
References Boo_Validator::isInt(), and loadFiles().
Referenced by Boo_Test::htmlKitchenSinkDiv().
static Boo_LoremIpsum::htmlUl ($ count = 5, array $ attrs = array()) [static]
Gets an unorderd list of lorem ipsum.
Returns:
Boo_Html_Ul The unordered list.
Parameters:
int $count[optional] The number of list items to include.
array $attrs[optional] The attributes for the unorderd list.
Definition at line 107 of file LoremIpsum.php.
References $ul, Boo_Validator::isInt(), and loadFiles().
Referenced by Boo_Test::htmlKitchenSinkDiv().
static Boo_LoremIpsum::loadFiles () [static, private]
Loads files into class.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 135 of file LoremIpsum.php.
References array_trim().
Referenced by __construct(), getWords(), htmlPs(), and htmlUl().
Member Data Documentation
Boo_LoremIpsum::$lis = array() [static, protected]
Array of list items.
Definition at line 26 of file LoremIpsum.php.
Boo_LoremIpsum::$ps = array() [static, protected]
Array of paragraphs.
Definition at line 21 of file LoremIpsum.php.
Boo_LoremIpsum::$words = array() [static, protected]
Array of words.
Definition at line 31 of file LoremIpsum.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/LoremIpsum.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.