API Documentation for Boo-2.0.x: Boo_Qrbg Class Reference
Boo_Qrbg Class Reference
Quantum random bit generator class.
Public Member Functions
__construct ($username=false, $password=false)
Default constructor.
clearCache ()
Removes all items from cache.
getByte ()
Gets a byte.
getBytes ($count)
Returns array of bytes.
getDouble ()
Gets a double.
getDoubles ($count)
Returns array of doubles.
getFloat ()
Gets a float.
getFloats ($count)
Returns array of floats.
getHost ()
Gets the host.
getInt ()
Gets a an integer.
getInt16 ()
Gets a 16-bit integer.
getInt32 ()
Gets a 32-bit integer.
getInt64 ()
Gets a 64-bit integer.
getInt8 ()
Gets a 16-bit integer.
getInts ($count)
Returns array of integers.
getLongInt ()
Gets a long integer.
getLongInts ($count)
Returns array of long integers.
getPassword ()
Gets the password.
getPort ()
Gets the port number.
getUsername ()
Gets the username.
setHost ($host)
Sets the host.
setPassword ($password)
Sets the password.
setPort ($port)
Sets the port number.
setUsername ($username)
Sets the username.
testCmd ()
Tests the BOO_QRBG_CMD.
Public Attributes
const PRIMARY_KEY = 'cache_id'
Primary key.
const TABLE_NAME = 'boo_qrbg_cache'
Table name.
Protected Member Functions
exec ($type= 'int', $count=1)
Executes QRand or grabs value form cache.
removeCacheById ($cacheId)
Removies item form cache.
saveCache ($cache, $type)
Saves an item to cache.
Protected Attributes
$host = 'random.irb.hr'
QRBG Service host.
$password = BOO_QRBG_PASSWORD
QRBG Service password.
$port = '1227'
QRBG Service port.
$username = BOO_QRBG_USERNAME
QRBG Service username.
Detailed Description
Quantum random bit generator class.
This class provides a PHP wraper for the QRand Command-line Utility [v0.2, 2007-07-17].
The following constant must be defined:
BOO_QRBG_CMD = The qrand command '/PATH_TO/./qrand'.
BOO_QRBG_CACHE = Use cache (bool).
BOO_QRBG_CACHE_SIZE = Size of cache, try setting to 1000.
BOO_QRBG_USERNAME = Your QRBG Service username.
BOO_QRBG_PASSWORD = Your QRBG Service password.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.5
Required:
http://random.irb.hr/ QRand Command-line Utility [v0.2, 2007-07-17]
Definition at line 24 of file Qrbg.php.
Constructor & Destructor Documentation
Boo_Qrbg::__construct ($ username = false, $ password = false)
Default constructor.
Returns:
void.
Parameters:
string $username[optional] Your QRBG Service username.
string $password[optional] Your QRBG Service password.
Reimplemented from Boo_Db.
Definition at line 62 of file Qrbg.php.
References $password, $username, setPassword(), and setUsername().
Member Function Documentation
Boo_Qrbg::clearCache ()
Removes all items from cache.
Returns:
bool Returns TRUE on success, FALSE otheriwse.
Definition at line 423 of file Qrbg.php.
References $e, and Boo_Db::connect().
Boo_Qrbg::exec ($ type = 'int', $ count = 1) [protected]
Executes QRand or grabs value form cache.
Returns:
mixed Returns value on success, FALSE otherwise.
Parameters:
string $type[optional] Data type.
int $count[optional] Number of values to return.
Definition at line 307 of file Qrbg.php.
References $e, Boo_Db::connect(), removeCacheById(), and saveCache().
Referenced by getByte(), getBytes(), getDouble(), getDoubles(), getFloat(), getFloats(), getInt(), getInt16(), getInt32(), getInt64(), getInt8(), getInts(), getLongInt(), getLongInts(), and testCmd().
Boo_Qrbg::getByte ()
Gets a byte.
Returns:
int byte on success, FALSE otherwise.
Warning:
May not work as expected. PHP has no support for a single byte data type.
Definition at line 227 of file Qrbg.php.
References exec().
Boo_Qrbg::getBytes ($ count)
Returns array of bytes.
Returns:
array Array of bytes.
Parameters:
int $count The number of items to return.
See also:
Boo_Qrbg::getByte()
Definition at line 257 of file Qrbg.php.
References exec().
Boo_Qrbg::getDouble ()
Gets a double.
Returns:
double Double on success, FALSE otherwise.
Warning:
May not work as expected. PHP has poor support for a doubles.
Definition at line 246 of file Qrbg.php.
References exec().
Boo_Qrbg::getDoubles ($ count)
Returns array of doubles.
Returns:
array Array of doubles.
Parameters:
int $count The number of items to return.
See also:
Boo_Qrbg::getDouble()
Definition at line 297 of file Qrbg.php.
References exec().
Boo_Qrbg::getFloat ()
Gets a float.
Returns:
float Float on success, FALSE otherwise.
Definition at line 236 of file Qrbg.php.
References exec().
Boo_Qrbg::getFloats ($ count)
Returns array of floats.
Returns:
array Array of floats.
Parameters:
int $count The number of items to return.
See also:
Boo_Qrbg::getFloat()
Definition at line 287 of file Qrbg.php.
References exec().
Boo_Qrbg::getHost ()
Gets the host.
Returns:
string The host.
Definition at line 164 of file Qrbg.php.
Boo_Qrbg::getInt ()
Gets a an integer.
Returns:
int Integer on success, FALSE otherwise.
Definition at line 188 of file Qrbg.php.
References exec().
Boo_Qrbg::getInt16 ()
Gets a 16-bit integer.
Returns:
int 16-bit integer on success, FALSE otherwise.
Definition at line 179 of file Qrbg.php.
References exec().
Boo_Qrbg::getInt32 ()
Gets a 32-bit integer.
Returns:
int 32-bit integer on success, FALSE otherwise.
Definition at line 197 of file Qrbg.php.
References exec().
Boo_Qrbg::getInt64 ()
Gets a 64-bit integer.
Returns:
int 64-bit integer on success, FALSE otherwise.
Warning:
May not work as expected. 64-bit support is not really up to par.
Definition at line 207 of file Qrbg.php.
References exec().
Boo_Qrbg::getInt8 ()
Gets a 16-bit integer.
Returns:
int 16-bit integer on success, FALSE otherwise.
Definition at line 170 of file Qrbg.php.
References exec().
Boo_Qrbg::getInts ($ count)
Returns array of integers.
Returns:
array Array of integers.
Parameters:
int $count The number of items to return.
See also:
Boo_Qrbg::getInt()
Definition at line 267 of file Qrbg.php.
References exec().
Boo_Qrbg::getLongInt ()
Gets a long integer.
Returns:
int Long integer on success, FALSE otherwise.
Warning:
May not work as expected. 64-bit support is not really up to par.
Definition at line 217 of file Qrbg.php.
References exec().
Boo_Qrbg::getLongInts ($ count)
Returns array of long integers.
Returns:
array Array of long integers.
Parameters:
int $count The number of items to return.
See also:
Boo_Qrbg::getLongInt()
Definition at line 277 of file Qrbg.php.
References exec().
Boo_Qrbg::getPassword ()
Gets the password.
Returns:
string The password.
Definition at line 118 of file Qrbg.php.
Boo_Qrbg::getPort ()
Gets the port number.
Returns:
int The port number
Definition at line 141 of file Qrbg.php.
Boo_Qrbg::getUsername ()
Gets the username.
Returns:
string The username.
Definition at line 95 of file Qrbg.php.
Boo_Qrbg::removeCacheById ($ cacheId) [protected]
Removies item form cache.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
int $cacheId The cache ID.
Definition at line 373 of file Qrbg.php.
References $e, and Boo_Db::connect().
Referenced by exec().
Boo_Qrbg::saveCache ($ cache, $ type) [protected]
Saves an item to cache.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
mixed $cache Item to save to cache.
string $type The type.
Definition at line 393 of file Qrbg.php.
References $e, and Boo_Db::connect().
Referenced by exec().
Boo_Qrbg::setHost ($ host)
Sets the host.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
sring $host The host.
Definition at line 148 of file Qrbg.php.
References $host.
Boo_Qrbg::setPassword ($ password)
Sets the password.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
string $password The password.
Definition at line 102 of file Qrbg.php.
References $password, and Boo_Validator::isPassword().
Referenced by __construct().
Boo_Qrbg::setPort ($ port)
Sets the port number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
int $port The port number.
Definition at line 125 of file Qrbg.php.
References $port, and Boo_Validator::isInt().
Boo_Qrbg::setUsername ($ username)
Sets the username.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
string $username The username.
Definition at line 79 of file Qrbg.php.
References $username, and Boo_Validator::isUsername().
Referenced by __construct().
Boo_Qrbg::testCmd ()
Tests the BOO_QRBG_CMD.
Warning:
Uses var_dump().
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 442 of file Qrbg.php.
References exec().
Member Data Documentation
Boo_Qrbg::$host = 'random.irb.hr' [protected]
QRBG Service host.
Definition at line 49 of file Qrbg.php.
Referenced by setHost().
Boo_Qrbg::$password = BOO_QRBG_PASSWORD [protected]
QRBG Service password.
Definition at line 44 of file Qrbg.php.
Referenced by __construct(), and setPassword().
Boo_Qrbg::$port = '1227' [protected]
QRBG Service port.
Definition at line 54 of file Qrbg.php.
Referenced by setPort().
Boo_Qrbg::$username = BOO_QRBG_USERNAME [protected]
QRBG Service username.
Definition at line 39 of file Qrbg.php.
Referenced by __construct(), and setUsername().
const Boo_Qrbg::PRIMARY_KEY = 'cache_id'
Primary key.
Definition at line 34 of file Qrbg.php.
const Boo_Qrbg::TABLE_NAME = 'boo_qrbg_cache'
Table name.
Definition at line 29 of file Qrbg.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Qrbg.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.