API Documentation for Boo-2.0.x: Boo_Io Class Reference
Boo_Io Class Reference
IO class.
Public Member Functions
__construct ($tableName=false, $primaryKey=false)
Default constructor.
addArrayField ($field)
Adds a field to the array list.
addArrayFields (array $fields)
Adds fields to the list of array fields.
addEncryptedField ($field)
Adds a field to the encrypted list.
addEncryptedFields (array $fields)
Adds fields to the list of encrypted fields.
addField ($field, $value)
Adds field.
addFields (array $fields)
Adds multiple fields.
addIgnoredField ($field)
Adds a field to the ignored list.
addIgnoredFields (array $fields)
Adds fields to the list of ignored fields.
addMagicField ($field)
Adds a field to the magic list.
addMagicFields (array $fields)
Adds fields to the list of magic fields.
addSerializedField ($field)
Adds a field to the serialized list.
addSerializedFields (array $fields)
Adds fields to the list of serialized fields.
afterClose ($result)
Called after Boo_Io::close().
beforeClose ()
Called before Boo_Io::close().
clearArrayFields ()
Clears the list of array fields.
clearEncryptedFields ()
Clears the list of encrypted fields.
clearFields ()
Clears the list of fields.
clearIgnoredFields ()
Clears the list of ignored fields.
clearMagicFields ()
Clears the list of magic fields.
clearSerializedFields ()
Clears the list of serialized fields.
clearSession ($key= 'boo_io')
Clears session.
close ()
Close the object.
count ()
Counts all the rows in the table.
delete ()
Deletes and item for the database.
fixNulls (array $excludeFields=array())
Converts empty strings in fields to null.
get ($field)
Gets a field value.
getArrayFields ()
Gets the array of array fields.
getBooId ()
Gets the Boo ID.
getCreated ()
Gets the time the object was created.
getEncryptedFields ()
Gets the array of encrypted fields.
getField ($field)
Gets a field value.
getFields ()
Returns array of fields.
getHandledMagicFields ()
Returns an array of handled magic fields.
getIgnoredFields ()
Gets the array of ignored fields.
getIp ()
Gets the IP for the object.
getMagicFields ()
Gets the array of magic fields.
getModified ()
Gets the time the object was modified.
getSafeFields ()
Returns an array of fields that are safe to open or save.
getSerializedFields ()
Gets the array of serialized fields.
getUuid ()
Gets the UUID for the object.
handleMagicFields ()
Handles magic fields.
hasArrayFields ()
Determins if object has any array fields.
hasEncryptedFields ()
Determins if object has encrpyted fields.
hasFields ()
Determins if object has fields.
hasIgnoredFields ()
Determins if object has ignored fields.
hasMagicFields ()
Determins if object has magic fields.
hasSafeFields ()
Determins if object has safe fields.
hasSerializedFields ()
Determins if object has serialized fields.
htmlDebugDiv (array $attrs=array())
Prints HTML for debuging.
isArrayField ($field)
Determins if a field is on the array list.
isEmpty ()
isEncryptedField ($field)
Determins if a field is on the encrypted list.
isField ($field)
Determins if a field exists.
isIgnoredField ($field)
Determins if a field is on the ignored list.
isMagicField ($field)
Determins if a field is on the magic list.
isMagicFieldHandled ($field)
Determins if a magic field is handled.
isSerializedField ($field)
Determins if a field is on the serialized list.
merge (Boo_Io $io)
Merges data from a Boo_Io object.
open ($booId)
Opens the object.
openSession ($key= 'boo_id')
Opens object in session.
preloadPost ($override=true)
Preloads values from fields into $_POST.
removeArrayField ($field)
Removes a field from the array fields list.
removeArrayFields (array $fields)
Removes fields from the list of array fields.
removeEncryptedField ($field)
Removes a field from the encrypted fields list.
removeEncryptedFields (array $fields)
Removes fields from the list of encrypted fields.
removeField ($field)
Removes a field.
removeFields (array $fields)
Removes multiple fields.
removeIgnoredField ($field)
Removes a field from the ignored fields list.
removeIgnoredFields (array $fields)
Removes fields from the list of ignored fields.
removeMagicField ($field)
Removes a field from the magic fields list.
removeMagicFields (array $fields)
Removes fields from the list of magic fields.
removeSerializedField ($field)
Removes a field from the serialized fields list.
removeSerializedFields (array $fields)
Removes fields from the list of serialized fields.
save ()
Saves the fields to the database.
saveAs ($booId)
Allows you to save current instance of the object as a differnt Boo ID.
saveSession ($key= 'boo_id')
set ($field, $value)
Sets a field.
setArrayField ($field)
Adds a field to the array list.
setArrayFields (array $fields)
Sets the list of array fields.
setEncryptedField ($field)
Adds a field to the encrypted list.
setEncryptedFields (array $fields)
Sets the list of encrypted fields.
setField ($field, $value)
Sets a field.
setFields (array $fields)
Sets multiple fields.
setIgnoredField ($field)
Adds a field to the ignored list.
setIgnoredFields (array $fields)
Sets the list of ignored fields.
setMagicField ($field)
Adds a field to the magic list.
setMagicFields (array $fields)
Sets the list of magic fields.
setSerializedField ($field)
Adds a field to the serialized list.
setSerializedFields (array $fields)
Sets the list of serialized fields.
Static Public Member Functions
static exists ($search, $column, $tableName, $primaryKey)
Determins if an item exists in a given column.
Protected Member Functions
afterDelete ($result)
Called after Boo_Io::delete().
afterMerge ($result)
Called after Boo_Io::merge().
afterOpen ($result)
Called after Boo_Io::open().
afterSave ($result)
Called after Boo_Io::save().
beforeDelete ()
Called before Boo_Io::delete().
beforeMerge ($io)
Called before Boo_Io::merge().
beforeOpen ($booId)
Called before Boo_Io::open().
beforeSave ()
Called before Boo_Io::save().
Protected Attributes
$arrayFields = array()
Array fields list.
$booId = false
Boo ID.
$encryptedFields = array()
Encrypted fields list.
$fields = array()
Fields list.
$handledMagicFields
List of magic fields that this class handles.
$ignoredFields = array()
Ignored fields list.
$magicFields = array()
Magic field list.
$serializedFields = array()
Serialized fields list.
Private Member Functions
setBooId ($booId)
Sets the Boo ID.
Detailed Description
IO class.
This class is used for sloppy database input and output. It is extended by other objects to provide the user with a simple way to add fields to an object. Currently it can only interact with a single table.
The Boo ID concept is a generic reference to the unique ID for each row of a given table. In a typical table of users the Boo ID would likely be the user ID column. If no unique column exists for a given table then you should create a column called boo_id and designate it an autonumber and primary key (try phpMyAdmin for this). The Boo ID will be the value of the column designated by Boo_Io::setPrimaryKey().
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 23 of file Io.php.
Constructor & Destructor Documentation
Boo_Io::__construct ($ tableName = false, $ primaryKey = false)
Default constructor.
Handles shorthand object initialization.
Parameters:
string $tableName[optional] The table name.
string $primaryKey[optional] The primary key.
Returns:
void.
Reimplemented from Boo_Db.
Definition at line 94 of file Io.php.
References Boo_Db::$primaryKey, and Boo_Db::$tableName.
Member Function Documentation
Boo_Io::addArrayField ($ field)
Adds a field to the array list.
Parameters:
string $field The field name to make serialized.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already an array.
Definition at line 351 of file Io.php.
References setArrayField().
Referenced by addArrayFields().
Boo_Io::addArrayFields (array $ fields)
Adds fields to the list of array fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 729 of file Io.php.
References addArrayField().
Referenced by merge().
Boo_Io::addEncryptedField ($ field)
Adds a field to the encrypted list.
Provides API compatibility. Performs the same function as Boo_IO::setEncryptedField().
Parameters:
string $field The field name to encrypt.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already encrypted.
Definition at line 309 of file Io.php.
References setEncryptedField().
Referenced by addEncryptedFields().
Boo_Io::addEncryptedFields (array $ fields)
Adds fields to the list of encrypted fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 653 of file Io.php.
References addEncryptedField().
Referenced by merge().
Boo_Io::addField ($ field, $ value)
Adds field.
Provides API compatibility. Functionally identical to Boo_Io::setField().
Parameters:
string $field The field to add.
string $value The value of the field.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 298 of file Io.php.
References setField().
Boo_Io::addFields (array $ fields)
Adds multiple fields.
This function will not remove existing fields.
Parameters:
array $fields An array of fields. Key is field name, value is field value.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 633 of file Io.php.
References setField().
Referenced by merge(), and open().
Boo_Io::addIgnoredField ($ field)
Adds a field to the ignored list.
Provides API compatibility. Performs the same function as Boo_IO::setIgnoredField().
Parameters:
string $field The field name to ignore.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already ignored.
Definition at line 321 of file Io.php.
References setIgnoredField().
Referenced by addIgnoredFields().
Boo_Io::addIgnoredFields (array $ fields)
Adds fields to the list of ignored fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 672 of file Io.php.
References addIgnoredField().
Referenced by merge().
Boo_Io::addMagicField ($ field)
Adds a field to the magic list.
Parameters:
string $field The field name to make magic.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already magic.
Definition at line 331 of file Io.php.
References setMagicField().
Referenced by addMagicFields().
Boo_Io::addMagicFields (array $ fields)
Adds fields to the list of magic fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 691 of file Io.php.
References addMagicField().
Referenced by merge().
Boo_Io::addSerializedField ($ field)
Adds a field to the serialized list.
Parameters:
string $field The field name to make serialized.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already serialized.
Definition at line 341 of file Io.php.
References setSerializedField().
Referenced by addSerializedFields().
Boo_Io::addSerializedFields (array $ fields)
Adds fields to the list of serialized fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 710 of file Io.php.
References addSerializedField().
Referenced by merge().
Boo_Io::afterClose ($ result)
Called after Boo_Io::close().
Parameters:
bool $result The result of Boo_Io::close().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1637 of file Io.php.
Referenced by close().
Boo_Io::afterDelete ($ result) [protected]
Called after Boo_Io::delete().
Parameters:
bool $result The result of Boo_Io::delete().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1448 of file Io.php.
Referenced by delete().
Boo_Io::afterMerge ($ result) [protected]
Called after Boo_Io::merge().
Parameters:
bool $result The result of Boo_Io::merge().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1213 of file Io.php.
Referenced by merge().
Boo_Io::afterOpen ($ result) [protected]
Called after Boo_Io::open().
Parameters:
bool $result The result of Boo_Io::open().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1576 of file Io.php.
Referenced by open().
Boo_Io::afterSave ($ result) [protected]
Called after Boo_Io::save().
Parameters:
bool $result The result of Boo_Io::save().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1394 of file Io.php.
Referenced by save().
Boo_Io::beforeClose ()
Called before Boo_Io::close().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1627 of file Io.php.
Referenced by close().
Boo_Io::beforeDelete () [protected]
Called before Boo_Io::delete().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1438 of file Io.php.
Referenced by delete().
Boo_Io::beforeMerge ($ io) [protected]
Called before Boo_Io::merge().
Parameters:
Boo_Io $io The object to merge.
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1203 of file Io.php.
References $io.
Referenced by merge().
Boo_Io::beforeOpen ($ booId) [protected]
Called before Boo_Io::open().
Parameters:
int $booId The Boo ID.
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 1566 of file Io.php.
References $booId.
Referenced by open().
Boo_Io::beforeSave () [protected]
Called before Boo_Io::save().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Reimplemented in Boo_User.
Definition at line 1384 of file Io.php.
Referenced by save().
Boo_Io::clearArrayFields ()
Clears the list of array fields.
Returns:
bool Function always returns TRUE.
Definition at line 911 of file Io.php.
Boo_Io::clearEncryptedFields ()
Clears the list of encrypted fields.
Returns:
bool Function always returns TRUE.
Definition at line 871 of file Io.php.
Boo_Io::clearFields ()
Clears the list of fields.
Returns:
bool Function always returns TRUE.
Definition at line 861 of file Io.php.
Boo_Io::clearIgnoredFields ()
Clears the list of ignored fields.
Returns:
bool Function always returns TRUE.
Definition at line 881 of file Io.php.
Boo_Io::clearMagicFields ()
Clears the list of magic fields.
Returns:
bool Function always returns TRUE.
Definition at line 891 of file Io.php.
Boo_Io::clearSerializedFields ()
Clears the list of serialized fields.
Returns:
bool Function always returns TRUE.
Definition at line 901 of file Io.php.
Boo_Io::clearSession ($ key = 'boo_io')
Clears session.
Parameters:
string $key[optional] The session key.
Returns:
bool Returns TRUE if key exists, FALSE otherwise.
Definition at line 1688 of file Io.php.
Boo_Io::close ()
Close the object.
Provides API function for future implementation.
Todo:
Implement this function and preform cleanup.
Returns:
bool Always returns TRUE.
Definition at line 1587 of file Io.php.
References afterClose(), and beforeClose().
Boo_Io::count ()
Counts all the rows in the table.
Returns:
int Returns the row count, FALSE on failure.
Definition at line 1456 of file Io.php.
References $e, and Boo_Db::connect().
Boo_Io::delete ()
Deletes and item for the database.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1402 of file Io.php.
References $e, afterDelete(), beforeDelete(), and Boo_Db::connect().
static Boo_Io::exists ($ search, $ column, $ tableName, $ primaryKey) [static]
Determins if an item exists in a given column.
Parameters:
string $search The search string.
string $column The column name.
string $tableName The table name.
mixed $primaryKey The primary key for the table, should be a Boo ID.
Returns:
mixed Returns Boo ID on success, FALSE on failure.
Reimplemented in Boo_User.
Definition at line 1710 of file Io.php.
References $booId, $e, Boo_Db::$primaryKey, Boo_Db::$tableName, Boo_Db::connect(), and Boo_Validator::isSqlSafe().
Referenced by Boo_Group::isGroupId(), and Boo_Group::isName().
Boo_Io::fixNulls (array $ excludeFields = array())
Converts empty strings in fields to null.
Returns:
int Returns the number of fields changed.
Parameters:
array $excludeFields[optional] Fields to exclude.
Definition at line 1606 of file Io.php.
Boo_Io::get ($ field)
Gets a field value.
API shorthand for Boo_Io::getField();
Parameters:
string $field The field name.
Returns:
bool Returns the value of the field if successful, FALSE otherwise.
Definition at line 480 of file Io.php.
References getField().
Boo_Io::getArrayFields ()
Gets the array of array fields.
Returns:
array The array of array fields. Key is field name, value is field value.
Definition at line 956 of file Io.php.
Referenced by merge().
Boo_Io::getBooId ()
Gets the Boo ID.
Boo ID will be unique for each item in a table.
Returns:
int The Boo ID.
Definition at line 1146 of file Io.php.
Referenced by Boo_User::beforeSave().
Boo_Io::getCreated ()
Gets the time the object was created.
Returns:
int Unix timestamp of when the object was created if present, FALSE otherwise.
Definition at line 1803 of file Io.php.
Boo_Io::getEncryptedFields ()
Gets the array of encrypted fields.
Returns:
array The array of encrypted fields. Key is field name, value is field value.
Definition at line 928 of file Io.php.
Referenced by merge().
Boo_Io::getField ($ field)
Gets a field value.
Parameters:
string $field The field name.
Returns:
bool Returns the value of the field if successful, FALSE otherwise.
Definition at line 489 of file Io.php.
Referenced by get().
Boo_Io::getFields ()
Returns array of fields.
Returns:
array The fields. Key is field name, value is field value.
Definition at line 921 of file Io.php.
Referenced by merge().
Boo_Io::getHandledMagicFields ()
Returns an array of handled magic fields.
Returns:
array Handled magic fields.
Definition at line 1028 of file Io.php.
Boo_Io::getIgnoredFields ()
Gets the array of ignored fields.
Returns:
array The array of ignored fields. Key is field name, value is field value.
Definition at line 935 of file Io.php.
Referenced by merge().
Boo_Io::getIp ()
Gets the IP for the object.
Returns:
string The IP for the object if present, FALSE otherwise.
Definition at line 1822 of file Io.php.
Referenced by handleMagicFields(), and Boo_User::login().
Boo_Io::getMagicFields ()
Gets the array of magic fields.
Returns:
array The array of magic fields. Key is field name, value is field value.
Definition at line 942 of file Io.php.
Referenced by merge().
Boo_Io::getModified ()
Gets the time the object was modified.
Returns:
int Unix timestamp of when the object was modified if present, FALSE otherwise.
Definition at line 1810 of file Io.php.
Boo_Io::getSafeFields ()
Returns an array of fields that are safe to open or save.
Will not include fields that are ignored.
Returns:
array Returns array of safe fields on success, FALSE otherwise.
Definition at line 1099 of file Io.php.
References isIgnoredField().
Referenced by hasSafeFields(), preloadPost(), and save().
Boo_Io::getSerializedFields ()
Gets the array of serialized fields.
Returns:
array The array of serialized fields. Key is field name, value is field value.
Definition at line 949 of file Io.php.
Boo_Io::getUuid ()
Gets the UUID for the object.
Returns:
string The UUID for the object if present, FALSE otherwise.
Definition at line 1816 of file Io.php.
Referenced by handleMagicFields().
Boo_Io::handleMagicFields ()
Handles magic fields.
Function is called by Boo_Io::save() after Boo_Io::beforeSave().
Returns:
bool Returns TRUE if magic fields were handled, FALSE otherwise.
Definition at line 1764 of file Io.php.
References getIp(), getUuid(), hasMagicFields(), and isMagicField().
Referenced by save().
Boo_Io::hasArrayFields ()
Determins if object has any array fields.
Returns:
bool Returns TRUE if array fields are present, FALSE otherwise.
Definition at line 1080 of file Io.php.
Referenced by merge().
Boo_Io::hasEncryptedFields ()
Determins if object has encrpyted fields.
Returns:
bool Returns TRUE if encrypted fields are present, FALSE otherwise.
Definition at line 1052 of file Io.php.
Referenced by merge().
Boo_Io::hasFields ()
Determins if object has fields.
Returns:
bool Returns TRUE if fields are present, FALSE otherwise.
Definition at line 1045 of file Io.php.
Boo_Io::hasIgnoredFields ()
Determins if object has ignored fields.
Returns:
bool Returns TRUE if ingnored fields are present, FALSE otherwise.
Definition at line 1059 of file Io.php.
Referenced by merge().
Boo_Io::hasMagicFields ()
Determins if object has magic fields.
Returns:
bool Returns TRUE if magic fields are present, FALSE otherwise.
Definition at line 1066 of file Io.php.
Referenced by handleMagicFields(), and merge().
Boo_Io::hasSafeFields ()
Determins if object has safe fields.
Returns:
bool Returns TRUE if safe fields are present, FALSE otherwise.
Definition at line 1087 of file Io.php.
References getSafeFields().
Boo_Io::hasSerializedFields ()
Determins if object has serialized fields.
Returns:
bool Returns TRUE if serialized fields are present, FALSE otherwise.
Definition at line 1073 of file Io.php.
Referenced by merge().
Boo_Io::htmlDebugDiv (array $ attrs = array())
Prints HTML for debuging.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
string HTML debug information.
Definition at line 1829 of file Io.php.
Boo_Io::isArrayField ($ field)
Determins if a field is on the array list.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if it is an array field, FALSE otherwise.
Definition at line 1019 of file Io.php.
Referenced by save().
Boo_Io::isEmpty ()
Definition at line 1699 of file Io.php.
Referenced by merge().
Boo_Io::isEncryptedField ($ field)
Determins if a field is on the encrypted list.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if it is ignored, FALSE otherwise.
Definition at line 975 of file Io.php.
Referenced by save().
Boo_Io::isField ($ field)
Determins if a field exists.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if field exists, FALSE otherwise.
Definition at line 964 of file Io.php.
Boo_Io::isIgnoredField ($ field)
Determins if a field is on the ignored list.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if it is ignored, FALSE otherwise.
Definition at line 986 of file Io.php.
Referenced by getSafeFields().
Boo_Io::isMagicField ($ field)
Determins if a field is on the magic list.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if it is magic, FALSE otherwise.
Definition at line 997 of file Io.php.
Referenced by handleMagicFields().
Boo_Io::isMagicFieldHandled ($ field)
Determins if a magic field is handled.
Returns:
bool Returns TRUE if field is handled, FALSE otherwise.
Parameters:
string $field The field name.
Definition at line 1035 of file Io.php.
Boo_Io::isSerializedField ($ field)
Determins if a field is on the serialized list.
Parameters:
string $field The field.
Returns:
bool Returns TRUE if it is serialized, FALSE otherwise.
Definition at line 1008 of file Io.php.
Referenced by save().
Boo_Io::merge (Boo_Io $ io)
Merges data from a Boo_Io object.
Parameters:
Boo_Io $io The object to merge.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1154 of file Io.php.
References addArrayFields(), addEncryptedFields(), addFields(), addIgnoredFields(), addMagicFields(), addSerializedFields(), afterMerge(), beforeMerge(), getArrayFields(), getEncryptedFields(), getFields(), getIgnoredFields(), getMagicFields(), hasArrayFields(), hasEncryptedFields(), hasIgnoredFields(), hasMagicFields(), hasSerializedFields(), and isEmpty().
Boo_Io::open ($ booId)
Opens the object.
Loads values from database.
Parameters:
int $booId The Boo ID.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Reimplemented in Boo_User.
Definition at line 1480 of file Io.php.
References $booId, $e, addFields(), afterOpen(), beforeOpen(), Boo_Db::connect(), and Boo_Validator::isNull().
Referenced by Boo_Group::__construct().
Boo_Io::openSession ($ key = 'boo_id')
Opens object in session.
Parameters:
string $key[optional] The session key.
Returns:
Returns TRUE on success, FALSE otherwise.
Definition at line 1665 of file Io.php.
Boo_Io::preloadPost ($ override = true)
Preloads values from fields into $_POST.
This only works well if the $_POST keys are the same as Boo_Io fields. Using Boo_Html_Form_Xml::preloadPost() is safer for many uses.
See also:
Boo_Html_Form_Xml::preloadPost()
Parameters:
bool $override[optional] Override existing values.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 108 of file Io.php.
References $fields, and getSafeFields().
Boo_Io::removeArrayField ($ field)
Removes a field from the array fields list.
Parameters:
string $field The field to remove.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 458 of file Io.php.
Referenced by removeArrayFields().
Boo_Io::removeArrayFields (array $ fields)
Removes fields from the list of array fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 843 of file Io.php.
References removeArrayField().
Boo_Io::removeEncryptedField ($ field)
Removes a field from the encrypted fields list.
Parameters:
string $field The field to remove.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 378 of file Io.php.
Referenced by removeEncryptedFields().
Boo_Io::removeEncryptedFields (array $ fields)
Removes fields from the list of encrypted fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 767 of file Io.php.
References removeEncryptedField().
Boo_Io::removeField ($ field)
Removes a field.
Parameters:
string $field The field name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 361 of file Io.php.
Referenced by removeFields().
Boo_Io::removeFields (array $ fields)
Removes multiple fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 748 of file Io.php.
References removeField().
Boo_Io::removeIgnoredField ($ field)
Removes a field from the ignored fields list.
Parameters:
string $field The field to remove.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 398 of file Io.php.
Referenced by removeIgnoredFields().
Boo_Io::removeIgnoredFields (array $ fields)
Removes fields from the list of ignored fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 786 of file Io.php.
References removeIgnoredField().
Boo_Io::removeMagicField ($ field)
Removes a field from the magic fields list.
Parameters:
string $field The field to remove.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 418 of file Io.php.
Referenced by removeMagicFields().
Boo_Io::removeMagicFields (array $ fields)
Removes fields from the list of magic fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 805 of file Io.php.
References removeMagicField().
Boo_Io::removeSerializedField ($ field)
Removes a field from the serialized fields list.
Parameters:
string $field The field to remove.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 438 of file Io.php.
Referenced by removeSerializedFields().
Boo_Io::removeSerializedFields (array $ fields)
Removes fields from the list of serialized fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 824 of file Io.php.
References removeSerializedField().
Boo_Io::save ()
Saves the fields to the database.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1235 of file Io.php.
References $e, afterSave(), beforeSave(), Boo_Db::connect(), Boo_Csv::fixLastComma(), getSafeFields(), handleMagicFields(), isArrayField(), isEncryptedField(), Boo_Validator::isNull(), and isSerializedField().
Referenced by Boo_User::login(), and saveAs().
Boo_Io::saveAs ($ booId)
Allows you to save current instance of the object as a differnt Boo ID.
Returns:
bool Returns the result of Boo_Io::save() after Boo ID is changed.
Parameters:
int $booId
Definition at line 1222 of file Io.php.
References $booId, save(), and setBooId().
Boo_Io::saveSession ($ key = 'boo_id')
Saves object to session.
Parameters:
string $key[optional] The session key.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1647 of file Io.php.
Boo_Io::set ($ field, $ value)
Sets a field.
API shorthand for Boo_Io::setField().
Parameters:
string $field The field to set.
string $value The value of the field.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 142 of file Io.php.
References setField().
Boo_Io::setArrayField ($ field)
Adds a field to the array list.
Provides API compatibility. Performs the same function as Boo_Io::addArrayField().
Parameters:
string $field The field name to protect.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already an array.
Definition at line 273 of file Io.php.
Referenced by addArrayField(), and setArrayFields().
Boo_Io::setArrayFields (array $ fields)
Sets the list of array fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 611 of file Io.php.
References setArrayField().
Boo_Io::setBooId ($ booId) [private]
Sets the Boo ID.
Parameters:
mixed $booId The Boo ID.
Returns:
bool Returns TRUE on success, FALSE on failure.
Definition at line 1127 of file Io.php.
References $booId.
Referenced by saveAs().
Boo_Io::setEncryptedField ($ field)
Adds a field to the encrypted list.
Parameters:
string $field The field name to encrypt.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already encrypted.
Definition at line 174 of file Io.php.
Referenced by addEncryptedField(), and setEncryptedFields().
Boo_Io::setEncryptedFields (array $ fields)
Sets the list of encrypted fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 528 of file Io.php.
References setEncryptedField().
Boo_Io::setField ($ field, $ value)
Sets a field.
Parameters:
string $field The field to set.
string $value The value of the field.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 151 of file Io.php.
Referenced by addField(), addFields(), set(), and setFields().
Boo_Io::setFields (array $ fields)
Sets multiple fields.
This function will clear the list of fields prior to setting them.
Parameters:
array $fields An array of fields. Key is field name, value is field value.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 507 of file Io.php.
References setField().
Boo_Io::setIgnoredField ($ field)
Adds a field to the ignored list.
Parameters:
string $field The field name to ignore.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already ignored.
Definition at line 196 of file Io.php.
Referenced by Boo_User::__construct(), addIgnoredField(), and setIgnoredFields().
Boo_Io::setIgnoredFields (array $ fields)
Sets the list of ignored fields.
Boo_Io will not save fields that are ignored. This function will clear the list of ignored fields before replacing it.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 551 of file Io.php.
References setIgnoredField().
Boo_Io::setMagicField ($ field)
Adds a field to the magic list.
Provides API compatibility. Performs the same function as Boo_Io::addMagicField().
Parameters:
string $field The field name to protect.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already magic.
Definition at line 220 of file Io.php.
Referenced by addMagicField(), and setMagicFields().
Boo_Io::setMagicFields (array $ fields)
Sets the list of magic fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 571 of file Io.php.
References setMagicField().
Referenced by Boo_User::__construct().
Boo_Io::setSerializedField ($ field)
Adds a field to the serialized list.
Provides API compatibility. Performs the same function as Boo_Io::addSerializedField().
Parameters:
string $field The field name to protect.
Returns:
bool Returns TRUE on success, FALSE otherwise. Will return TRUE if field is already serialized.
Definition at line 249 of file Io.php.
Referenced by Boo_User::__construct(), addSerializedField(), and setSerializedFields().
Boo_Io::setSerializedFields (array $ fields)
Sets the list of serialized fields.
Parameters:
array $fields An array of fields. Keys are numeric, values are the field names.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 591 of file Io.php.
References setSerializedField().
Member Data Documentation
Boo_Io::$arrayFields = array() [protected]
Array fields list.
Boo will automaticly store and retrieve these fileds while still allowing SQL queries in the following form: SELECT * FROM table_name WHERE value LIKE '|search|';
Attention:
This method violates table normalization rules. In most cases you should use joins instead.
Warning:
Only stores array values, keys are permanently lost.
Definition at line 76 of file Io.php.
Boo_Io::$booId = false [protected]
Boo ID.
The Boo ID is a unique ID for each item, usualy the primary key of a table.
Definition at line 83 of file Io.php.
Referenced by beforeOpen(), exists(), open(), saveAs(), and setBooId().
Boo_Io::$encryptedFields = array() [protected]
Encrypted fields list.
Boo will encrypt fields on this list with BOO_AES_KEY before saving into database. Fields will be unencrypted when opened.
Definition at line 37 of file Io.php.
Boo_Io::$fields = array() [protected]
Fields list.
Keys are field names, values are the field values.
Definition at line 29 of file Io.php.
Referenced by preloadPost().
Boo_Io::$handledMagicFields [protected]
Initial value:
 array(
        'created', 'modified', 'uuid', 'ip')
List of magic fields that this class handles.
Definition at line 57 of file Io.php.
Boo_Io::$ignoredFields = array() [protected]
Ignored fields list.
Numerically indexed array of field names to ignore. Boo will not save fields on this list, however it will store them during the same instance.
Definition at line 45 of file Io.php.
Boo_Io::$magicFields = array() [protected]
Magic field list.
Boo will automaticly manipulated these fields.
Definition at line 52 of file Io.php.
Boo_Io::$serializedFields = array() [protected]
Serialized fields list.
Boo will automaticly serialize and unserialize these fileds.
Definition at line 65 of file Io.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Io.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.