API Documentation for Boo-2.0.x: Boo_Group Class Reference
Boo_Group Class Reference
Group class.
Public Member Functions
__construct ($groupId=false)
Default constructor.
getDescription ()
Gets the group description.
getName ()
Gets the groups name.
getPermissions ()
Gets the group permissions.
isPermsisions ($permissions)
Determins if permissions are valid.
setDescription ($description)
Sets the groups description.
setName ($name)
Sets the group name.
setPermissions ($permissions)
Group permissions.
Static Public Member Functions
static getGroupIdByName ($name)
Returns the group ID given a group name.
static getGroups ()
Gets array of groups.
static isGroupId ($groupId)
Determines if a group ID already exists.
static isName ($name)
Determines if a group name already exists.
Public Attributes
const PRIMARY_KEY = 'group_id'
Primary key.
const TABLE_NAME = 'boo_groups'
Table name.
Detailed Description
Group class.
Used to manipulate groups.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2007 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.7.0
Definition at line 16 of file Group.php.
Constructor & Destructor Documentation
Boo_Group::__construct ($ groupId = false)
Default constructor.
Parameters:
int $groupId[optional] Group ID.
Returns:
void.
Definition at line 33 of file Group.php.
References Boo_Io::open().
Member Function Documentation
Boo_Group::getDescription ()
Gets the group description.
Returns:
string Returns the groups description if set, FALSE otherwise.
Definition at line 167 of file Group.php.
static Boo_Group::getGroupIdByName ($ name) [static]
Returns the group ID given a group name.
Parameters:
string $name The group name.
Returns:
int Group ID on success, FALSE on failure.
Definition at line 182 of file Group.php.
References $e, and Boo_Db::connect().
static Boo_Group::getGroups () [static]
Gets array of groups.
Returns:
Returns array of groups, key is the group ID, value is the group name.
Definition at line 49 of file Group.php.
References $e, and Boo_Db::connect().
Boo_Group::getName ()
Gets the groups name.
Returns:
string Returns the groups name if set, FALSE otherwise.
Definition at line 143 of file Group.php.
Boo_Group::getPermissions ()
Gets the group permissions.
Returns:
int Returns group permissions on success, FALSE otherwise.
Definition at line 174 of file Group.php.
static Boo_Group::isGroupId ($ groupId) [static]
Determines if a group ID already exists.
Parameters:
int $groupId The group ID.
Returns:
bool Returns TRUE if group ID is already in the database, FALSE otherwise.
Definition at line 229 of file Group.php.
References Boo_Io::exists().
Referenced by Boo_User::setGroupId().
static Boo_Group::isName ($ name) [static]
Determines if a group name already exists.
Parameters:
int $name The group name.
Returns:
bool Returns TRUE if group name is already in the database, FALSE otherwise.
Definition at line 219 of file Group.php.
References Boo_Io::exists().
Boo_Group::isPermsisions ($ permissions)
Determins if permissions are valid.
See also:
Boo_Group::setPermissions().
Parameters:
int $permissions The permissions.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 111 of file Group.php.
Boo_Group::setDescription ($ description)
Sets the groups description.
Parameters:
string $description The group description.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 151 of file Group.php.
References Boo_Validator::isString(), and strtodb().
Boo_Group::setName ($ name)
Sets the group name.
Parameters:
string $name The group name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 127 of file Group.php.
References Boo_Validator::isString(), and strtodb().
Boo_Group::setPermissions ($ permissions)
Group permissions.
Permissions are simmilar to GNU/Linux:
1 = --x
2 = -w-
3 = -wx
4 = r--
5 = r-x
6 = rw-
7 = rwx
Parameters:
int $permissions The permissions.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Todo:
Fix permisions.
Definition at line 94 of file Group.php.
Member Data Documentation
const Boo_Group::PRIMARY_KEY = 'group_id'
Primary key.
Definition at line 26 of file Group.php.
const Boo_Group::TABLE_NAME = 'boo_groups'
Table name.
Definition at line 21 of file Group.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Group.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.