API Documentation for Boo-2.0.x: Boo_Format Class Reference
Boo_Format Class Reference
Format class.
Public Member Functions
__construct ()
Default constructor.
Static Public Member Functions
static format ($value, $formatRule)
Formats a value.
static formatCardNumber ($cardNumber, $format=0)
Formats a card number.
static formatEmail ($email, $format=0)
Formats email address.
static formatExpDate ($expDate, $format=0)
Formats expiration date.
static formatPhoneExtension ($phoneExt, $format=0)
Formats phone extension.
static formatPhoneNumber ($phoneNumber, $format=0)
Formats phone number.
static formatPrice ($price, $format=0)
Formats prices.
static formatSocialSecurityNumber ($ssNumber, $format=0)
Formats a Socical Security number.
static formatUri ($uri, $format=0)
Formats URI.
static formatUrl ($url, $format=0)
Formats URL.
static formatZip ($zip, $format=0)
Formats ZIP code.
Detailed Description
Format class.
This class is used for basic input formating.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 16 of file Format.php.
Constructor & Destructor Documentation
Boo_Format::__construct ()
Default constructor.
Returns:
void.
Definition at line 22 of file Format.php.
Member Function Documentation
static Boo_Format::format ($ value, $ formatRule) [static]
Formats a value.
Use # in the format rule to represent the value.
Parameters:
string $value The value to format.
string $formatRule The format rule.
Returns:
mixed The value if format was successful, FALSE otherwise.
Definition at line 375 of file Format.php.
References quote().
Referenced by Boo_Html_Form_Xml::handleMakeIo().
static Boo_Format::formatCardNumber ($ cardNumber, $ format = 0) [static]
Formats a card number.
Possible formats are:
0 = 5424000000000015
Parameters:
string $cardNumber The card number.
int $format[optional] The format.
Returns:
string Formated card number on success, FALSE on failure.
Todo:
Add more formats.
Definition at line 217 of file Format.php.
References Boo_Validator::isCardNumber(), and Boo_Helper::removeNonNumeric().
static Boo_Format::formatEmail ($ email, $ format = 0) [static]
Formats email address.
Parameters:
string $email The email address.
int $format[optional] The format.
Returns:
bool Returns formated email address on success, FALSE on failure.
Todo:
Add additional formats.
Definition at line 296 of file Format.php.
References Boo_Validator::isEmail().
Referenced by Boo_User::setEmail().
static Boo_Format::formatExpDate ($ expDate, $ format = 0) [static]
Formats expiration date.
Expiration date can be in the following formats:
MMYY
MM/YY
MM-YY
MMYYYY
MM/YYYY
MM-YYYY
YYYY-MM-DD
YYYY/MM/DD
Possible formats are:
0 = MMDD
Parameters:
string $expDate The expiration date.
int $format[optional] The format.
Todo:
Add support for other formats.
Returns:
string Formated expiration date on success, FALSE on failure.
Definition at line 250 of file Format.php.
References Boo_Validator::isNull(), and Boo_Helper::removeNonNumeric().
static Boo_Format::formatPhoneExtension ($ phoneExt, $ format = 0) [static]
Formats phone extension.
Parameters:
string $phoneExt The phone extension.
int $format[optional] The format.
Possible formats are:
0 = 1234
1 = x1234
Returns:
string Formated phone extension, FALSE on failure.
Definition at line 126 of file Format.php.
References Boo_Helper::removeNonNumeric().
static Boo_Format::formatPhoneNumber ($ phoneNumber, $ format = 0) [static]
Formats phone number.
Parameters:
string $phoneNumber The phone number.
int $format[optional] The format.
Possible formats are:
0 = 8003682669
1 = 800-368-2669
2 = (800) 368-2669
3 = 800.368.2669
Returns:
string Formated phone number, FALSE on failure.
Definition at line 74 of file Format.php.
References Boo_Validator::isPhoneNumber(), and Boo_Helper::removeNonNumeric().
Referenced by Boo_User::setPhoneNumber(), and Boo_User::setSmsNumber().
static Boo_Format::formatPrice ($ price, $ format = 0) [static]
Formats prices.
Parameters:
string $price The price.
string $format[optional] The format.
Returns:
bool Returns formated price on success, FALSE on failure.
Todo:
Add additional formats.
Definition at line 337 of file Format.php.
References Boo_Validator::isNull(), Boo_Validator::isPrice(), and Boo_Helper::removeCurrencySymbol().
static Boo_Format::formatSocialSecurityNumber ($ ssNumber, $ format = 0) [static]
Formats a Socical Security number.
Parameters:
string $ssNumber The Social Security number.
int $format[optional] The format.
Returns:
bool Returns formated Social Security number on success, FALSE on failure.
Todo:
Add additional formats.
Definition at line 315 of file Format.php.
References Boo_Validator::isSocialSecurityNumber().
static Boo_Format::formatUri ($ uri, $ format = 0) [static]
Formats URI.
Parameters:
string $url The URI.
int $format[optional] The format.
Returns:
string Returns formated URI on success, FALSE on failure.
Todo:
Finish function.
Definition at line 51 of file Format.php.
References Boo_Helper::addHttp().
static Boo_Format::formatUrl ($ url, $ format = 0) [static]
Formats URL.
Parameters:
string $url The URL.
int $format[optional] The format.
Returns:
string Returns formated URL on success, FALSE on failure.
Todo:
Finish function.
Definition at line 33 of file Format.php.
References Boo_Helper::addHttp().
static Boo_Format::formatZip ($ zip, $ format = 0) [static]
Formats ZIP code.
Parameters:
string $zip The ZIP code.
int $format[optional] The format.
Possible formats are:
0 = 123451234
1 = 12345-1234
Returns:
string Formated ZIP code, FALSE on failure.
Todo:
International support.
Definition at line 166 of file Format.php.
References Boo_Validator::isZip(), and Boo_Helper::removeNonNumeric().
Referenced by Boo_User::setZip().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Format.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.