API Documentation for Boo-2.0.x: Boo_User Class Reference
Boo_User Class Reference
User class.
Public Member Functions
__construct ($user=false)
Default constructor.
addSetting ($name, $value)
Adds a user setting.
addSettings (array $settings)
Adds settings to the users settings.
auth ()
Authorize user.
beforeSave ()
clearSettings ()
Clears users settings.
getAccountId ()
Gets the users account ID.
getApartmentNumber ()
Gets the users apartment number.
getAuthToken ()
getCarrierId ()
Gets the users carrier ID.
getCity ()
Gets the users city.
getCompany ()
Gets the users company.
getCountry ()
Gets the users country code.
getCountryCode ()
Gets the users country code.
getCountryName ()
Gets the users country name.
getEmail ()
Gets the users email address.
getEmailLink ($subject=false)
Gets the users email address link.
getFaxNumber ()
Gets the users fax number.
getFirstName ()
Gets the users first name.
getGroupId ()
Gets the users group ID.
getLastIp ()
Gets the time of the users last IP.
getLastLogin ()
Gets the time of the users last login.
getLastName ()
Gets the users last name.
getName ()
Gets the users name.
getPasswordHash ()
Gets the users password hash.
getPhoneNumber ()
Gets the users phone number.
getSalt ()
Gets the users password salt.
getSetting ($name)
Gets a user setting.
getSettings ()
Gets array of users settings.
getSmsNumber ()
Gets the users SMS number.
getState ()
Gets the users state code.
getStateCode ()
Gets the users state code.
getStateName ()
Gets the users state name.
getStatus ()
Gets the users status.
getStreet ()
Gets the users street.
getUserId ()
Gets the users ID.
getUsername ()
getWebsite ()
Gets the users website.
getZip ()
Gets the users ZIP code.
hasAccount ()
hasAddress ()
Determins if a user has a full address.
hasApartmentNumber ()
Determins if user has an apartment number.
hasSetting ($key)
Determins if a user has a setting.
htmlAddressSpan (array $attrs=array())
Returns address as html.
htmlAuthA (array $attrs=array())
htmlEmailA (array $attrs=array(), $subject=false)
Gets the users email address as a HTML anchor.
htmlUserA (array $attrs=array())
Gets the users link as a HTML anchor.
htmlWebsiteA (array $attrs=array())
Gets the users website as a HTML anchor.
isAuth ()
Determins if a session is authorized.
isAuthTokenValid ($authToken)
isPrivate ()
Determins if a users profile is private.
isRoot ()
Determins if user is a member of the root group.
isStatusOK ()
login ($username=false, $password=false)
Login the user.
logout ()
Logout user.
open ($user)
Opens the user object.
openAccount ($accountId=false)
openImages ($userId=false)
removeSetting ($name)
Removes a users settings.
setAccountId ($accountId)
Sets the users account ID.
setApartmentNumber ($apt)
Sets the users apartment number.
setCarrierId ($carrierId)
Sets the users carrier ID.
setCity ($city)
Sets the users city.
setCompany ($company)
Sets the users company.
setCountry ($country)
Sets the users country.
setCountryCode ($code)
Sets the users country code.
setCountryName ($name)
Sets the users country.
setEmail ($email)
Sets the users email address.
setFaxNumber ($faxNumber)
Sets the users fax number.
setFirstName ($name)
Sets the users first name.
setGroupId ($groupId)
Sets the users group ID.
setLastName ($name)
Sets the users last name.
setPassword ($password)
Sets the users password.
setPhoneNumber ($phoneNumber)
Sets the users phone number.
setPrivate ($opt)
Sets users private status.
setSetting ($name, $value)
Sets a user setting.
setSettings (array $settings)
Sets the users settings.
setSmsNumber ($smsNumber)
Sets the users SMS number.
setState ($state)
Sets the users state.
setStateCode ($code)
Sets the users state code.
setStateName ($name)
Sets the users state.
setStatus ($status)
Set users status.
setStreet ($street)
Sets the users street.
setUsername ($username)
Sets the users username.
setWebsite ($website)
Sets the users website.
setZip ($zip)
Sets the users ZIP code.
verifyUserIdHash ()
Verifys a session hash to be sure the user ID was not changed without our knowning.
Static Public Member Functions
static exists ($search, $column, $tableName=self::TABLE_NAME, $primaryKey=self::PRIMARY_KEY)
Determins if an item exists in a given column.
static getFieldByUserId ($field, $userId)
Gets a field given an ID.
static getSessionUserId ()
Gets the current user ID from the session.
static getUserIdByEmail ($email)
Gets a user ID given an email address.
static getUserIdByUsername ($username)
Gets a user ID given a username.
static isEmail ($email)
Determines if an email address already exists.
static isUser ($user)
Determins if a user already exists.
static isUserId ($userId)
Determines if a user ID already exists.
static isUsername ($username)
Determines if a username already exists.
Public Attributes
const MAX_USERNAME_LENGTH = 32
Maximum length of username.
const MIN_USERNAME_LENGTH = 4
Minimum length of username.
const PRIMARY_KEY = 'user_id'
Primary key.
const TABLE_NAME = 'boo_users'
Table name.
Detailed Description
User class.
This class is used to create and manipulate users.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.9.5
Definition at line 16 of file User.php.
Constructor & Destructor Documentation
Boo_User::__construct ($ user = false)
Default constructor.
Parameters:
int $user[optional] User to open.
Returns:
void.
Definition at line 51 of file User.php.
References $user, open(), setCountryCode(), setGroupId(), Boo_Io::setIgnoredField(), Boo_Io::setMagicFields(), Boo_Io::setSerializedField(), and setStatus().
Member Function Documentation
Boo_User::addSetting ($ name, $ value)
Adds a user setting.
Provides API compatibility.
Parameters:
string $name The setting name.
mixed $value The setting value.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1184 of file User.php.
References setSetting().
Boo_User::addSettings (array $ settings)
Adds settings to the users settings.
Parameters:
array $settings The array of settings.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1205 of file User.php.
Boo_User::auth ()
Authorize user.
Returns:
Returns TRUE on success, FALSE otherwise.
Definition at line 938 of file User.php.
References $userId, _server(), and getUserId().
Referenced by login().
Boo_User::beforeSave ()
Preform checks befor saving the user object.
Returns:
bool Returns TRUE on success, FALSE on failure.
Reimplemented from Boo_Io.
Definition at line 1057 of file User.php.
References Boo_Io::getBooId().
Boo_User::clearSettings ()
Clears users settings.
Returns:
bool Returns TRUE on success, FALSE on failure.
Definition at line 1235 of file User.php.
Referenced by setSettings().
static Boo_User::exists ($ search, $ column, $ tableName = self::TABLE_NAME, $ primaryKey = self::PRIMARY_KEY) [static]
Determins if an item exists in a given column.
Shortcut function for Boo_User.
Parameters:
string $search The search string.
string $column The column name.
string $tableName[optional] The table name.
mixed $primaryKey[optional] The primary key for the table, should be a Boo ID.
Returns:
mixed Returns Boo ID on success, FALSE on failure.
Reimplemented from Boo_Io.
Definition at line 1375 of file User.php.
References Boo_Db::$primaryKey, and Boo_Db::$tableName.
Referenced by getUserIdByEmail(), getUserIdByUsername(), isEmail(), isUserId(), and isUsername().
Boo_User::getAccountId ()
Gets the users account ID.
Returns:
int Returns the users account ID if set, FALSE otherwise.
Definition at line 139 of file User.php.
Referenced by hasAccount(), and openAccount().
Boo_User::getApartmentNumber ()
Gets the users apartment number.
Returns:
string Returns the users apartment number if set, FALSE otherwise.
Definition at line 378 of file User.php.
Referenced by hasApartmentNumber(), and htmlAddressSpan().
Boo_User::getAuthToken ()
Definition at line 828 of file User.php.
References getPasswordHash(), getSalt(), and getUserId().
Referenced by htmlAuthA(), and isAuthTokenValid().
Boo_User::getCarrierId ()
Gets the users carrier ID.
Returns:
int The carrier ID.
Definition at line 645 of file User.php.
Boo_User::getCity ()
Gets the users city.
Returns:
string Returns the users city if set, FALSE otherwise.
Definition at line 410 of file User.php.
Referenced by hasAddress(), and htmlAddressSpan().
Boo_User::getCompany ()
Gets the users company.
Returns:
string Returns the users company if set, FALSE otherwise.
Definition at line 331 of file User.php.
Boo_User::getCountry ()
Gets the users country code.
Provides API compatibility.
See also:
Boo_Validator::$countries.
Returns:
string Country code in strtoupper.
Definition at line 580 of file User.php.
Boo_User::getCountryCode ()
Gets the users country code.
See also:
Boo_Validator::$countries.
Returns:
string Country code in strtoupper.
Definition at line 588 of file User.php.
Boo_User::getCountryName ()
Gets the users country name.
See also:
Boo_Validator::$countries.
Returns:
string Country name.
Definition at line 596 of file User.php.
References Boo_Helper::getCountryNameByCode().
Referenced by hasAddress(), and htmlAddressSpan().
Boo_User::getEmail ()
Gets the users email address.
Returns:
string The users email address.
Definition at line 872 of file User.php.
Boo_User::getEmailLink ($ subject = false)
Gets the users email address link.
Parameters:
string $subject[optional] The subject.
Returns:
string The users email address link as a URL, FALSE on failure.
Definition at line 880 of file User.php.
Referenced by htmlEmailA().
Boo_User::getFaxNumber ()
Gets the users fax number.
Returns:
string The fax number if available, empty string otherwise.
Definition at line 693 of file User.php.
static Boo_User::getFieldByUserId ($ field, $ userId) [static]
Gets a field given an ID.
Parameters:
string $field The field
int $userId The user ID.
Returns:
mixed Returns the value of the field if successful, FALSE otherwise.
Definition at line 1345 of file User.php.
References $user, and $userId.
Boo_User::getFirstName ()
Gets the users first name.
Returns:
string Returns the users first name if set, FALSE otherwise.
Definition at line 266 of file User.php.
Boo_User::getGroupId ()
Gets the users group ID.
Returns:
int Returns the users group ID if set, FALSE otherwise.
Definition at line 115 of file User.php.
Referenced by isRoot().
Boo_User::getLastIp ()
Gets the time of the users last IP.
Returns:
int Unix timestamp of the last IP used by the user.
Definition at line 931 of file User.php.
Boo_User::getLastLogin ()
Gets the time of the users last login.
Returns:
int Unix timestamp of the last login.
Definition at line 924 of file User.php.
Boo_User::getLastName ()
Gets the users last name.
Returns:
string Returns the users last name if set, FALSE otherwise.
Definition at line 290 of file User.php.
Boo_User::getName ()
Gets the users name.
Formated as first name space last name if both are present, otherwise just the name that is set.
Returns:
string Returns the users name if set, FALSE otherwise.
Definition at line 300 of file User.php.
Referenced by htmlAddressSpan().
Boo_User::getPasswordHash ()
Gets the users password hash.
Returns:
string The password hash.
Definition at line 815 of file User.php.
Referenced by getAuthToken().
Boo_User::getPhoneNumber ()
Gets the users phone number.
Returns:
string The phone number if available, empty string otherwise.
Definition at line 718 of file User.php.
Boo_User::getSalt ()
Gets the users password salt.
Returns:
string The password salt.
Definition at line 821 of file User.php.
Referenced by getAuthToken().
static Boo_User::getSessionUserId () [static]
Gets the current user ID from the session.
Returns:
int Returns user ID on success, FALSE otherwise.
Definition at line 1406 of file User.php.
References $userId.
Boo_User::getSetting ($ name)
Gets a user setting.
Parameters:
string $name The name of the setting.
Returns:
mixed Returns setting on success, FALSE on failure.
Definition at line 1263 of file User.php.
Boo_User::getSettings ()
Gets array of users settings.
Returns:
array Returns array of users settings, FALSE on failure.
Definition at line 1279 of file User.php.
Boo_User::getSmsNumber ()
Gets the users SMS number.
Returns:
string The SMS number if available, empty string otherwise.
Definition at line 669 of file User.php.
Boo_User::getState ()
Gets the users state code.
Provides API compatibility.
See also:
Boo_Validator::$states.
Returns:
string State code in strtoupper.
Definition at line 487 of file User.php.
Boo_User::getStateCode ()
Gets the users state code.
See also:
Boo_Validator::$states.
Returns:
string State code in strtoupper.
Definition at line 495 of file User.php.
Referenced by hasAddress(), and htmlAddressSpan().
Boo_User::getStateName ()
Gets the users state name.
See also:
Boo_Validator::$states.
Returns:
string State name.
Definition at line 503 of file User.php.
References Boo_Helper::getStateNameByCode().
Boo_User::getStatus ()
Gets the users status.
Returns:
int The users status, FALSE on failure.
Definition at line 169 of file User.php.
Boo_User::getStreet ()
Gets the users street.
Returns:
string Returns the users street if set, FALSE otherwise.
Definition at line 355 of file User.php.
Referenced by hasAddress(), and htmlAddressSpan().
Boo_User::getUserId ()
Gets the users ID.
Returns:
int The users ID.
Definition at line 725 of file User.php.
Referenced by auth(), getAuthToken(), htmlAuthA(), and openImages().
static Boo_User::getUserIdByEmail ($ email) [static]
Gets a user ID given an email address.
Parameters:
string $email The email address.
Returns:
int Returns the user ID if successful, FALSE otherwise.
Definition at line 1396 of file User.php.
References exists().
Referenced by isUser(), and open().
static Boo_User::getUserIdByUsername ($ username) [static]
Gets a user ID given a username.
Parameters:
string $username The username.
Returns:
int Returns the user ID if successful, FALSE otherwise.
Definition at line 1385 of file User.php.
References exists().
Referenced by isUser(), and open().
Boo_User::getUsername ()
Gets the users username.
Returns:
string The users usersname.
Definition at line 782 of file User.php.
Referenced by login().
Boo_User::getWebsite ()
Gets the users website.
Returns:
string Returns the users website if set, FALSE otherwise.
Definition at line 218 of file User.php.
Boo_User::getZip ()
Gets the users ZIP code.
Returns:
string ZIP code.
Definition at line 620 of file User.php.
Referenced by hasAddress(), and htmlAddressSpan().
Boo_User::hasAccount ()
Definition at line 68 of file User.php.
References getAccountId().
Boo_User::hasAddress ()
Determins if a user has a full address.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1417 of file User.php.
References getCity(), getCountryName(), getStateCode(), getStreet(), and getZip().
Boo_User::hasApartmentNumber ()
Determins if user has an apartment number.
Attention:
Zero is a valid apartment number.
Returns:
bool Returns TRUE if apartment number is present, FALSE otherwise.
Definition at line 386 of file User.php.
References getApartmentNumber(), and Boo_Validator::isNull().
Referenced by htmlAddressSpan().
Boo_User::hasSetting ($ key)
Determins if a user has a setting.
Parameters:
string $key The setting key.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1223 of file User.php.
Boo_User::htmlAddressSpan (array $ attrs = array())
Returns address as html.
Uses tags.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
string Address as html.
Definition at line 1429 of file User.php.
References getApartmentNumber(), getCity(), getCountryName(), getName(), getStateCode(), getStreet(), getZip(), and hasApartmentNumber().
Boo_User::htmlAuthA (array $ attrs = array())
Definition at line 833 of file User.php.
References getAuthToken(), and getUserId().
Boo_User::htmlEmailA (array $ attrs = array(), $ subject = false)
Gets the users email address as a HTML anchor.
Parameters:
array $attrs[optional] Array of attributes.
string $subject[optional] The subject.
Returns:
Boo_Html The users link as a HTML anchor, FALSE on failure.
Definition at line 900 of file User.php.
References getEmailLink().
Boo_User::htmlUserA (array $ attrs = array())
Gets the users link as a HTML anchor.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
Boo_Html The users link as a HTML anchor, FALSE on failure.
Definition at line 733 of file User.php.
Boo_User::htmlWebsiteA (array $ attrs = array())
Gets the users website as a HTML anchor.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
Boo_Html The users link as a HTML anchor, FALSE on failure.
Definition at line 226 of file User.php.
Boo_User::isAuth ()
Determins if a session is authorized.
Returns:
bool Returns TRUE if authorized, FALSE otherwise.
Definition at line 970 of file User.php.
References verifyUserIdHash().
Boo_User::isAuthTokenValid ($ authToken)
Definition at line 823 of file User.php.
References getAuthToken().
static Boo_User::isEmail ($ email) [static]
Determines if an email address already exists.
Parameters:
string $email The email address.
Returns:
bool Returns TRUE if email address is already in the database, FALSE otherwise.
Definition at line 1299 of file User.php.
References exists().
Boo_User::isPrivate ()
Determins if a users profile is private.
Returns:
bool Returns TRUE if private, FALSE otherwise.
Definition at line 194 of file User.php.
Boo_User::isRoot ()
Determins if user is a member of the root group.
Returns:
bool Returns TRUE if user is a member of the root group, FALSE otherwise.
Definition at line 1458 of file User.php.
References getGroupId().
Boo_User::isStatusOK ()
Determins if a users status is OK.
Returns:
bool Returns TRUE if user is OK, FALSE otherwise.
Warning:
This function will return TRUE for any positive status not just BOO_STATUS_OK.
Definition at line 176 of file User.php.
Referenced by login().
static Boo_User::isUser ($ user) [static]
Determins if a user already exists.
Parameters:
mixed $user The user to open. Accepts a user ID, email address, or username.
Returns:
bool Returns TRUE on success, FALSE on failure.
Definition at line 1310 of file User.php.
References $user, $userId, getUserIdByEmail(), getUserIdByUsername(), and Boo_Validator::isEmail().
static Boo_User::isUserId ($ userId) [static]
Determines if a user ID already exists.
Parameters:
int $userId The user ID.
Returns:
bool Returns TRUE if user ID is already in the database, FALSE otherwise.
Definition at line 1332 of file User.php.
References $userId, and exists().
static Boo_User::isUsername ($ username) [static]
Determines if a username already exists.
Parameters:
string $username The username.
Returns:
bool Returns TRUE if username is already in the database, FALSE otherwise.
Definition at line 1288 of file User.php.
References exists().
Boo_User::login ($ username = false, $ password = false)
Login the user.
Parameters:
string $username[optional] The username. If it is not set then Boo_User::getUsername() will be used.
string $password[optional] The password. If it is not set then Boo_User::getPassword() will be used.
Returns:
Returns TRUE if login was successful, FALSE otherwise.
Definition at line 986 of file User.php.
References $e, $userId, auth(), Boo_Db::connect(), Boo_Io::getIp(), getUsername(), isStatusOK(), open(), and Boo_Io::save().
Boo_User::logout ()
Logout user.
Returns:
bool Always returns TRUE.
Definition at line 1046 of file User.php.
Boo_User::open ($ user)
Opens the user object.
Parameters:
mixed $user The user to open. Accepts a user ID, email address, or username.
Returns:
bool Returns TRUE on success, FALSE on failure.
Reimplemented from Boo_Io.
Definition at line 1094 of file User.php.
References $user, $userId, getUserIdByEmail(), getUserIdByUsername(), and Boo_Validator::isEmail().
Referenced by __construct(), and login().
Boo_User::openAccount ($ accountId = false)
Definition at line 72 of file User.php.
References getAccountId().
Boo_User::openImages ($ userId = false)
Definition at line 1116 of file User.php.
References $userId, and getUserId().
Boo_User::removeSetting ($ name)
Removes a users settings.
Parameters:
string $name The name of the setting.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1245 of file User.php.
Boo_User::setAccountId ($ accountId)
Sets the users account ID.
Parameters:
int $accountId The account id.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 123 of file User.php.
Boo_User::setApartmentNumber ($ apt)
Sets the users apartment number.
Parameters:
string $apt The apartment number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 363 of file User.php.
References Boo_Validator::isApartmentNumber(), and strtodb().
Boo_User::setCarrierId ($ carrierId)
Sets the users carrier ID.
See also:
Boo_SMS
Parameters:
int $carrierId The carrier ID.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 629 of file User.php.
Boo_User::setCity ($ city)
Sets the users city.
Parameters:
string $city The city.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 394 of file User.php.
References Boo_Validator::isCity(), and strtodb().
Boo_User::setCompany ($ company)
Sets the users company.
Parameters:
string $company The company.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 315 of file User.php.
References Boo_Validator::isString(), and strtodb().
Boo_User::setCountry ($ country)
Sets the users country.
Parameters:
string $country The country as a country code or country name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 511 of file User.php.
References Boo_Validator::isCountryCode(), Boo_Validator::isCountryName(), setCountryCode(), and setCountryName().
Boo_User::setCountryCode ($ code)
Sets the users country code.
Country code is the two letter abbreviation.
See also:
Boo_Validator::$countries.
Parameters:
string $code The country code.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 560 of file User.php.
References Boo_Validator::isCountryCode().
Referenced by __construct(), and setCountry().
Boo_User::setCountryName ($ name)
Sets the users country.
Parameters:
string $country The country as a country name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 538 of file User.php.
References Boo_Validator::isCountryName().
Referenced by setCountry().
Boo_User::setEmail ($ email)
Sets the users email address.
Parameters:
string $email The email address.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 856 of file User.php.
References Boo_Format::formatEmail(), and Boo_Validator::isEmail().
Boo_User::setFaxNumber ($ faxNumber)
Sets the users fax number.
Parameters:
string $faxNumber The fax number
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 677 of file User.php.
References Boo_Validator::isPhoneNumber().
Boo_User::setFirstName ($ name)
Sets the users first name.
Parameters:
string $name The first name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 250 of file User.php.
References Boo_Validator::isName(), and strtodb().
Boo_User::setGroupId ($ groupId)
Sets the users group ID.
Parameters:
int $groupId The group ID.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 99 of file User.php.
References Boo_Group::isGroupId().
Referenced by __construct().
Boo_User::setLastName ($ name)
Sets the users last name.
Parameters:
string $name The last name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 274 of file User.php.
References Boo_Validator::isName(), and strtodb().
Boo_User::setPassword ($ password)
Sets the users password.
Parameters:
string $password The password.
Returns:
bool Returns TRUE on success, FALSE on failure.
Definition at line 790 of file User.php.
References Boo_Validator::isPassword().
Boo_User::setPhoneNumber ($ phoneNumber)
Sets the users phone number.
Parameters:
string $phoneNumber The phone number
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 701 of file User.php.
References Boo_Format::formatPhoneNumber(), and Boo_Validator::isPhoneNumber().
Boo_User::setPrivate ($ opt)
Sets users private status.
Parameters:
bool $opt Private status.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 184 of file User.php.
Boo_User::setSetting ($ name, $ value)
Sets a user setting.
Parameters:
string $name The setting name.
mixed $value The setting value.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Todo:
Add support for more complex settings.
Definition at line 1142 of file User.php.
Referenced by addSetting().
Boo_User::setSettings (array $ settings)
Sets the users settings.
Parameters:
array $settings The array of settings.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1166 of file User.php.
References clearSettings().
Boo_User::setSmsNumber ($ smsNumber)
Sets the users SMS number.
Parameters:
string $smsNumber The SMS number
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 653 of file User.php.
References Boo_Format::formatPhoneNumber(), and Boo_Validator::isPhoneNumber().
Boo_User::setState ($ state)
Sets the users state.
Parameters:
string $state The state as a state code or state name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 418 of file User.php.
References Boo_Validator::isStateCode(), Boo_Validator::isStateName(), setStateCode(), and setStateName().
Boo_User::setStateCode ($ code)
Sets the users state code.
State code is the two letter abbreviation.
See also:
Boo_Validator::$states.
Parameters:
string $code The state code.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 467 of file User.php.
References Boo_Validator::isStateCode().
Referenced by setState().
Boo_User::setStateName ($ name)
Sets the users state.
Parameters:
string $state The state as a state name.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 445 of file User.php.
References Boo_Helper::getStateCodeByName(), and Boo_Validator::isStateName().
Referenced by setState().
Boo_User::setStatus ($ status)
Set users status.
Possible values are:
BOO_STATUS_OK
BOO_STATUS_CLOSED
BOO_STATUS_SUSPENDED
BOO_STATUS_DISABLED
BOO_STATUS_PENDING
BOO_STATUS_UNKNOWN
You may use other integer values of your own. Statuses that indicate a user is in good standing (and allowed to login) should be greater than or equal to 1. Statuses that indicate a users account is closed, suspended, or otherwise inaccesable (and not allowed to login) be less than or equal to 0.
Parameters:
int $status User status.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 160 of file User.php.
Referenced by __construct().
Boo_User::setStreet ($ street)
Sets the users street.
Parameters:
string $street The street.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 339 of file User.php.
References Boo_Validator::isStreet(), and strtodb().
Boo_User::setUsername ($ username)
Sets the users username.
Setting the username to an already existing username will generate an E_USER_WARNING and return FALSE.
Parameters:
string $username The username.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 761 of file User.php.
References Boo_Validator::isUsername().
Boo_User::setWebsite ($ website)
Sets the users website.
Parameters:
string $website The website.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 202 of file User.php.
References Boo_Validator::isUrl().
Boo_User::setZip ($ zip)
Sets the users ZIP code.
Parameters:
string $zip The ZIP code.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 604 of file User.php.
References Boo_Format::formatZip(), and Boo_Validator::isZip().
Boo_User::verifyUserIdHash ()
Verifys a session hash to be sure the user ID was not changed without our knowning.
Returns:
bool Returns TRUE if verified, FALSE otherwise.
Definition at line 956 of file User.php.
References _server().
Referenced by isAuth().
Member Data Documentation
const Boo_User::MAX_USERNAME_LENGTH = 32
Maximum length of username.
Definition at line 37 of file User.php.
Referenced by Boo_Validator::isUsername().
const Boo_User::MIN_USERNAME_LENGTH = 4
Minimum length of username.
Definition at line 42 of file User.php.
Referenced by Boo_Validator::isUsername().
const Boo_User::PRIMARY_KEY = 'user_id'
Primary key.
Used for static functions. For non static functions see Boo_Db::setPrimaryKey().
Definition at line 32 of file User.php.
const Boo_User::TABLE_NAME = 'boo_users'
Table name.
Used for static functions. For non static functions see Boo_Db::setTableName().
Definition at line 24 of file User.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/User.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.