API Documentation for Boo-2.0.x: Boo_Sms Class Reference
Boo_Sms Class Reference
SMS class.
Public Member Functions
__construct ()
Default constructor.
getBody ()
Returns body.
getCarrierDomain ()
Returns carrier domain.
getCarrierId ()
Returns carrier ID.
getCarrierName ()
Returns carrier name.
getEmail ()
Returns email.
getPhoneNumber ()
Returns phone number.
getSubject ()
Returns subject.
isValid ()
send ()
Sends the message. Sends the message. Phone number and carrier ID must be set priory to calling the send method. This function requires Swift.
setBody ($body)
Sets the body.
setCarrierId ($carrierId)
Sets the carrier ID.
setPhoneNumber ($phoneNumber)
Sets the phone number.
setSubject ($subject)
Sets the subject.
Static Public Member Functions
static formatPhoneNumber ($phoneNumber)
Formats a phone number.
static getCarrierDomainById ($carrierId)
Returns carrier domain for a given carrier ID.
static getCarrierDomains ()
Returns array of carrier domains.
static getCarrierNameById ($carrierId)
Returns carrier name for a given carrier ID.
static getCarrierNames ()
Returns array of carrier names.
static getCarriers ()
Returns array of carriers.
static htmlCarrierSelect ($sticky=true, array $attrs=array())
Returns a HTML drop-down list of carriers.
static htmlCarrierSelect2 ($sticky=true)
Returns a HTML drop-down list of carriers.
static isCarrierId ($carrierId)
Determins if carrier ID is valid.
static isPhoneNumber ($phoneNumber)
Determins if a phone number is valid.
Protected Attributes
$body = null
The message body.
$carrierId = 0
The carrier ID.
$phoneNumber = 0
The phone number.
$subject = null
The message subject.
Static Protected Attributes
static $carriers
Array of carriers.
Detailed Description
SMS class.
This class is used to send a SMS (Short Message Service).
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Required:
http://www.swiftmailer.org/ Swift Mailer (included in BOO_LIB_DIR)
See also:
http://www.swiftmailer.org/wikidocs/
Definition at line 18 of file Sms.php.
Constructor & Destructor Documentation
Boo_Sms::__construct ()
Default constructor.
Returns:
void.
Definition at line 73 of file Sms.php.
Member Function Documentation
static Boo_Sms::formatPhoneNumber ($ phoneNumber) [static]
Formats a phone number.
Returns:
mixed On success returns formated phone number, FALSE otherwise.
Parameters:
string $phoneNumber The phone number to format.
Definition at line 188 of file Sms.php.
References $phoneNumber.
Referenced by isPhoneNumber(), and setPhoneNumber().
Boo_Sms::getBody ()
Returns body.
Returns:
string Returns the body of the message.
Definition at line 308 of file Sms.php.
Boo_Sms::getCarrierDomain ()
Returns carrier domain.
Returns:
string Carrier domain, FALSE is returned if carrier ID is not set.
Definition at line 241 of file Sms.php.
References getCarrierDomainById().
static Boo_Sms::getCarrierDomainById ($ carrierId) [static]
Returns carrier domain for a given carrier ID.
Parameters:
int $carrierId The carrier ID.
Returns:
string The carrier daomin on success, FALSE otherwise.
Definition at line 122 of file Sms.php.
References $carrierId.
Referenced by getCarrierDomain(), and getEmail().
static Boo_Sms::getCarrierDomains () [static]
Returns array of carrier domains.
Returns:
array Carrier domains. The index is the carrier ID. The value is the carier domain.
Definition at line 107 of file Sms.php.
Boo_Sms::getCarrierId ()
Returns carrier ID.
Returns:
int Carrier ID, NULL is returned if carrier ID is not set.
Definition at line 227 of file Sms.php.
Boo_Sms::getCarrierName ()
Returns carrier name.
Returns:
string Carrier name, FALSE is returned if carrier ID is not set.
Definition at line 233 of file Sms.php.
References getCarrierNameById().
static Boo_Sms::getCarrierNameById ($ carrierId) [static]
Returns carrier name for a given carrier ID.
Parameters:
int $carrierId The carrier ID.
Returns:
string The carrier name on success, FALSE otherwise.
Definition at line 94 of file Sms.php.
References $carrierId.
Referenced by getCarrierName().
static Boo_Sms::getCarrierNames () [static]
Returns array of carrier names.
Returns:
array Carrier names. The index is the carrier ID. The value is the carrier name.
Definition at line 79 of file Sms.php.
Referenced by htmlCarrierSelect(), and htmlCarrierSelect2().
static Boo_Sms::getCarriers () [static]
Returns array of carriers.
Returns:
array Multidimensional array of carriers.
Definition at line 135 of file Sms.php.
Boo_Sms::getEmail ()
Returns email.
Returns:
string Email used to send SMS.
8003682669@tmomail.net
Definition at line 251 of file Sms.php.
References getCarrierDomainById().
Referenced by send().
Boo_Sms::getPhoneNumber ()
Returns phone number.
Returns:
string Phone number, NULL is returned if phone number is not set.
Definition at line 172 of file Sms.php.
Boo_Sms::getSubject ()
Returns subject.
Returns:
string Returns the subject of the message.
Definition at line 286 of file Sms.php.
static Boo_Sms::htmlCarrierSelect ($ sticky = true, array $ attrs = array()) [static]
Returns a HTML drop-down list of carriers.
Parameters:
bool $sticky[optional] If set to TRUE the drop down list will be sticky.
array $attrs[optional] Array of attributes to add to the HTML select.
Returns:
string HTML drop-down list of all avalible carriers.
Since:
2.0.0 Carrier IDs were renumbered.
Definition at line 385 of file Sms.php.
References $select, and getCarrierNames().
static Boo_Sms::htmlCarrierSelect2 ($ sticky = true) [static]
Returns a HTML drop-down list of carriers.
This function is usefull for creating an HTML select of the avalible carriers. The value for each option will be set to the carrier ID. If the selected value is 0 no carrier was chosen from the drop-down list.
This function is not dependent on Boo_Html_Select. If you have the entire Boo Framework installed you should use Boo_Sms::htmlCarrierSelect() instead.
Parameters:
bool $sticky[optional] If set to TRUE the drop down list will be sticky.
Returns:
string HTML drop-down list of all avalible carriers.
Since:
2.0.0 Carrier IDs were renumbered.
 <select name="carrier" id="carrier">
 <option value="0">Select Carrier</option>
 <option value="5">Alaska Communications</option>
 <option value="10">Alltel</option>
 ...
 <option value="100">Virgin Mobile</option>
 </select>
Definition at line 420 of file Sms.php.
References getCarrierNames().
static Boo_Sms::isCarrierId ($ carrierId) [static]
Determins if carrier ID is valid.
Parameters:
int $carrierId The carrier ID to test.
Returns:
bool Returns TRUE if carrier ID is valid, FALSE otherwise.
Definition at line 142 of file Sms.php.
References $carrierId.
static Boo_Sms::isPhoneNumber ($ phoneNumber) [static]
Determins if a phone number is valid.
Returns:
bool Returns TRUE if phone number is valid, FALSE otherwise.
Parameters:
string $phoneNumber The phone number to test.
Definition at line 179 of file Sms.php.
References $phoneNumber, and formatPhoneNumber().
Boo_Sms::isValid ()
Determins if the message is valid.
Returns:
bool Returns TRUE if valid, FALSE otherwise.
Definition at line 355 of file Sms.php.
Referenced by send().
Boo_Sms::send ()
Sends the message. Sends the message. Phone number and carrier ID must be set priory to calling the send method. This function requires Swift.
Returns:
bool Returns TRUE if send was successful, FALSE otherwise.
 $sms->send();
Todo:
Add support for mail() function.
Definition at line 322 of file Sms.php.
References getEmail(), and isValid().
Boo_Sms::setBody ($ body)
Sets the body.
Parameters:
string $body The body.
Returns:
bool Function always returns TRUE.
Definition at line 294 of file Sms.php.
References $body.
Boo_Sms::setCarrierId ($ carrierId)
Sets the carrier ID.
Parameters:
int $carrierId The carrier ID.
Returns:
bool Returns TRUE if carrier ID is valid, FALSE otherwise.
Definition at line 212 of file Sms.php.
References $carrierId.
Boo_Sms::setPhoneNumber ($ phoneNumber)
Sets the phone number.
Parameters:
string $phoneNumber The phone number.
Returns:
bool Returns TRUE if phone number is valid, FALSE otherwise.
 $sms->setPhoneNumber('8003682669');
Todo:
Add support for non US phone numbers.
Definition at line 156 of file Sms.php.
References $phoneNumber, and formatPhoneNumber().
Boo_Sms::setSubject ($ subject)
Sets the subject.
Parameters:
string $subject The subject.
Returns:
bool Function always returns TRUE.
Definition at line 272 of file Sms.php.
References $subject.
Member Data Documentation
Boo_Sms::$body = null [protected]
The message body.
Definition at line 38 of file Sms.php.
Referenced by setBody().
Boo_Sms::$carrierId = 0 [protected]
The carrier ID.
Definition at line 28 of file Sms.php.
Referenced by getCarrierDomainById(), getCarrierNameById(), isCarrierId(), and setCarrierId().
Boo_Sms::$carriers [static, protected]
Initial value:
 array(
        5 => array('name' => 'Alaska Communications', 'domain' => 'msg.acsalaska.com'),
        10 => array('name' => 'Alltel', 'domain' => 'message.alltel.com'),
        15 => array('name' => 'AT&amp;T Wireless', 'domain' => 'txt.att.net'),
        20 => array('name' => 'Boost', 'domain' => 'myboostmobile.com'),
        25 => array('name' => 'Cellular South', 'domain' => 'csouth1.com'),
        30 => array('name' => 'Centennial Wireless', 'domain' => 'cwemail.com'),
        35 => array('name' => 'Cincinnati Bell', 'domain' => 'gocbw.com'),
        40 => array('name' => 'Cricket', 'domain' => 'sms.mycricket.com'),
        45 => array('name' => 'Helio', 'domain' => 'myhelio.com'),
        50 => array('name' => 'MetroPCS', 'domain' => 'mymetropcs.com'),
        55 => array('name' => 'Midwest Wireless', 'domain' => 'clearlydigital.com'),
        60 => array('name' => 'Nextel', 'domain' => 'messaging.nextel.com'),
        65 => array('name' => 'Qwest', 'domain' => 'qwestmp.com'),
        70 => array('name' => 'Sprint', 'domain' => 'messaging.sprintpcs.com'),
        75 => array('name' => 'SunCom Wireless', 'domain' => 'tms.suncom.com'),
        80 => array('name' => 'T-Mobile', 'domain' => 'tmomail.net'),
        85 => array('name' => 'Unicel', 'domain' => 'utext.com'),
        90 => array('name' => 'US Cellular', 'domain' => 'email.uscc.net'),
        95 => array('name' => 'Verizon Wireless', 'domain' => 'vtext.com'),
        100 => array('name' => 'Virgin Mobile', 'domain' => 'vmobl.com'))
Array of carriers.
Contains a multidimensional array of carrier information.
Since:
2.0.0 Carrier IDs were renumbered.
Definition at line 47 of file Sms.php.
Boo_Sms::$phoneNumber = 0 [protected]
The phone number.
Definition at line 23 of file Sms.php.
Referenced by formatPhoneNumber(), isPhoneNumber(), and setPhoneNumber().
Boo_Sms::$subject = null [protected]
The message subject.
Definition at line 33 of file Sms.php.
Referenced by setSubject().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Sms.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.