API Documentation for Boo-2.0.x: Boo_Html_FormControl Class Reference
Boo_Html_FormControl Class Reference
HTML form control class.
Public Member Functions
__construct ($element)
Default constructor.
getPostedValue ()
Returns posted value.
isSticky ()
Returns inputs stickiness.
setSticky ($opt)
Sets the inputs stickiness.
Protected Attributes
$sticky = true
Controls stickiness.
Detailed Description
HTML form control class.
This class is used to to manipulate HTML form controls. It is extened by Boo_Html_Input, Boo_Html_Select, and Boo_Html_Textarea.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 16 of file FormControl.php.
Constructor & Destructor Documentation
Boo_Html_FormControl::__construct ($ element)
Default constructor.
Parameters:
string $element The HTML element to create.
Returns:
void.
Reimplemented from Boo_Html.
Reimplemented in Boo_Html_Input.
Definition at line 28 of file FormControl.php.
References Boo_Html::$element.
Member Function Documentation
Boo_Html_FormControl::getPostedValue ()
Returns posted value.
Returns:
mixed Returns the posted value if set, FALSE otherwise.
Definition at line 55 of file FormControl.php.
References Boo_Html::getAttr(), and Boo_Html::hasAttr().
Referenced by Boo_Html_Select::getPostedIndex().
Boo_Html_FormControl::isSticky ()
Returns inputs stickiness.
Returns:
bool Returns TRUE if input is sticky, FALSE otherwise.
Reimplemented in Boo_Html_Input.
Definition at line 48 of file FormControl.php.
Referenced by Boo_Html_Select::html(), and Boo_Html_Textarea::htmlOpen().
Boo_Html_FormControl::setSticky ($ opt)
Sets the inputs stickiness.
Parameters:
bool $opt If input is sticky or not.
Returns:
bool Function always returns TRUE.
Reimplemented in Boo_Html_Input.
Definition at line 37 of file FormControl.php.
Member Data Documentation
Boo_Html_FormControl::$sticky = true [protected]
Controls stickiness.
Definition at line 21 of file FormControl.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html/FormControl.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.