API Documentation for Boo-2.0.x: Boo_Dialog_MessageBox Class Reference
Boo_Dialog_MessageBox Class Reference
Dialog messagebox class.
Public Member Functions
__construct ()
Default constructor.
addMessage ($message, array $attrs=array())
clearSession ()
getMessageCount ()
getMessages ()
html ()
merge (Boo_Html_List $list)
Merges list items from another list into this list.
openSession ()
saveSession ()
setIcon ($icon)
Sets the icon for the message box.
Public Attributes
$icon
$list
Detailed Description
Dialog messagebox class.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.0.0
Todo:
Rewrite with Smarty.
Definition at line 16 of file MessageBox.php.
Constructor & Destructor Documentation
Boo_Dialog_MessageBox::__construct ()
Default constructor.
Returns:
void.
Reimplemented from Boo_Dialog.
Definition at line 20 of file MessageBox.php.
References Boo_Html::addClass().
Member Function Documentation
Boo_Dialog_MessageBox::addMessage ($ message, array $ attrs = array())
Definition at line 32 of file MessageBox.php.
Boo_Dialog_MessageBox::clearSession ()
Definition at line 104 of file MessageBox.php.
References Boo_Html::getAttr().
Referenced by html().
Boo_Dialog_MessageBox::getMessageCount ()
Definition at line 110 of file MessageBox.php.
Boo_Dialog_MessageBox::getMessages ()
Definition at line 42 of file MessageBox.php.
Boo_Dialog_MessageBox::html ()
Definition at line 112 of file MessageBox.php.
References clearSession(), Boo_Html::htmlClose(), Boo_Html::htmlOpen(), and Boo_Html::setAttr().
Boo_Dialog_MessageBox::merge (Boo_Html_List $ list)
Merges list items from another list into this list.
Returns:
int Returns number of items merged.
Parameters:
Boo_Html_List $list The list object to merge.
Definition at line 56 of file MessageBox.php.
Boo_Dialog_MessageBox::openSession ()
Definition at line 88 of file MessageBox.php.
References $ol, and Boo_Html::getAttr().
Boo_Dialog_MessageBox::saveSession ()
Definition at line 79 of file MessageBox.php.
References Boo_Html::getAttr().
Boo_Dialog_MessageBox::setIcon ($ icon)
Sets the icon for the message box.
Returns:
bool Returns TRUE on success, FALSE otherwise
Parameters:
mixed $icon Accepts either a Boo_Html_Img object or a string to use as the image source.
Definition at line 65 of file MessageBox.php.
References $icon.
Member Data Documentation
Boo_Dialog_MessageBox::$icon
Definition at line 18 of file MessageBox.php.
Referenced by setIcon().
Boo_Dialog_MessageBox::$list
Definition at line 17 of file MessageBox.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Dialog/MessageBox.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.