API Documentation for Boo-2.0.x: Boo_Html_List Class Reference
Boo_Html_List Class Reference
HTML list class.
Public Member Functions
__construct ($element)
Default constructor.
addLi ($li)
Adds a list item.
clearLis ()
Clears all list items.
getCount ()
Returns list items count.
getCountByClass ($class)
Returns number of list items with a given class.
getLi ($index)
Returns a list item.
getLiById ($id)
Gets a list item by HTML ID.
getLiIndexById ($id)
Gets a list items index by HTML ID.
getLis ()
Retuns all list items.
html (array $attrs=array())
Returns html.
htmlDummyLi (array $attrs=array())
Returns a dummy list item.
isEmpty ()
Determines if list items is empty.
merge (Boo_Html_List $list)
Merges list items from another list into this list.
removeLi ($index)
Removes a list item.
removeLiByClass ($class)
Removes a list item.
removeLiById ($id)
Removes a list item by HTML ID.
setLi ($li, $index)
Sets a list item.
Protected Attributes
$lis = array()
List items array.
Detailed Description
HTML list class.
This class is used as a base class for all list elements.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 16 of file List.php.
Constructor & Destructor Documentation
Boo_Html_List::__construct ($ element)
Default constructor.
Parameters:
string $element The HTML element to create.
Returns:
void.
Reimplemented from Boo_Html.
Definition at line 28 of file List.php.
References Boo_Html::$element.
Member Function Documentation
Boo_Html_List::addLi ($ li)
Adds a list item.
Parameters:
mixed $li The list item to add.
Returns:
bool Returns index of item.
Definition at line 52 of file List.php.
Referenced by merge().
Boo_Html_List::clearLis ()
Clears all list items.
Returns:
bool Function always returns TRUE.
Definition at line 194 of file List.php.
Boo_Html_List::getCount ()
Returns list items count.
Returns:
int Number of list items.
Definition at line 201 of file List.php.
Referenced by html().
Boo_Html_List::getCountByClass ($ class)
Returns number of list items with a given class.
Will return zero if no items are found.
Returns:
int Returns number of list items with a given class.
Parameters:
string $class The search class.
Definition at line 211 of file List.php.
References Boo_Html::$count.
Boo_Html_List::getLi ($ index)
Returns a list item.
Parameters:
int $index The list item index.
Returns:
Boo_Html_Li The list item object on success, FALSE otherwise.
Definition at line 128 of file List.php.
Boo_Html_List::getLiById ($ id)
Gets a list item by HTML ID.
Returns:
Boo_Html_Li The list item object with the given ID, FALSE if not found.
Parameters:
string $id The search ID;
Definition at line 142 of file List.php.
Boo_Html_List::getLiIndexById ($ id)
Gets a list items index by HTML ID.
Returns:
int The list items index if found, FALSE if not found.
Parameters:
string $id The search id;
Definition at line 157 of file List.php.
Boo_Html_List::getLis ()
Retuns all list items.
Returns:
array Array of Boo_Html_Li objects.
Definition at line 188 of file List.php.
Referenced by merge().
Boo_Html_List::html (array $ attrs = array())
Returns html.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
string HTML for the element.
Reimplemented from Boo_Html.
Definition at line 251 of file List.php.
References Boo_Html::$count, Boo_Html::appendContent(), Boo_Html::clearContent(), getCount(), htmlDummyLi(), and isEmpty().
Boo_Html_List::htmlDummyLi (array $ attrs = array())
Returns a dummy list item.
This is used as a place holder for empty lists so they are valid xhtml.
Returns:
Boo_Html_Li A dummy list item.
Parameters:
array $attrs[optional] Array of attributes.
Definition at line 237 of file List.php.
Referenced by html().
Boo_Html_List::isEmpty ()
Determines if list items is empty.
Returns:
bool Returns TRUE if list items is empty, FALSE otherwise.
Reimplemented from Boo_Html.
Definition at line 227 of file List.php.
Referenced by html().
Boo_Html_List::merge (Boo_Html_List $ list)
Merges list items from another list into this list.
Returns:
int Returns number of items merged.
Parameters:
Boo_Html_List $list The list object to merge.
Definition at line 37 of file List.php.
References Boo_Html::$count, addLi(), and getLis().
Boo_Html_List::removeLi ($ index)
Removes a list item.
Parameters:
int $index The list item index.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 72 of file List.php.
Boo_Html_List::removeLiByClass ($ class)
Removes a list item.
Removes all list items with a specific class.
Parameters:
string $class The search class.
Returns:
bool Returns TRUE if a list item was removed, FALSE otherwise.
Definition at line 90 of file List.php.
Boo_Html_List::removeLiById ($ id)
Removes a list item by HTML ID.
Returns:
bool Returns TRUE if item was found and removed, FALSE otherwise.
Parameters:
string $id The search id;
Definition at line 172 of file List.php.
Boo_Html_List::setLi ($ li, $ index)
Sets a list item.
Parameters:
Boo_Html_Li $li The list item object.
int $index The list item index.
Returns:
bool Function always returns TRUE.
Definition at line 109 of file List.php.
Member Data Documentation
Boo_Html_List::$lis = array() [protected]
List items array.
Definition at line 21 of file List.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html/List.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.