API Documentation for Boo-2.0.x: Boo_Page Class Reference
Boo_Page Class Reference
Page class.
Public Member Functions
__construct ($user=false)
addCss ($href, $media= 'screen')
Adds a CSS file.
addJs ($src)
Adds a JavaScript file.
addPageCss ($href, $media=false)
Adds a CSS file.
addPageJs ($src)
Adds a JavaScript file.
allowGroup ($groupId)
allowGroupAdmin ()
allowGroupAnonymous ()
allowGroupEmpty ()
allowGroupRoot ()
allowGroupUser ()
excludeGroup ($groupId)
excludeGroupAdmin ()
excludeGroupAnonymous ()
excludeGroupEmpty ()
excludeGroupUser ()
forceSsl ()
Redirects users to the SSL version of the current page.
getTemplate ()
getTemplateCss ()
getTemplateJs ()
getTitle ()
getUser ()
Returns the current user.
hasTemplate ($template, $position=false)
Checks if page has a given template.
htmlBooCss ()
htmlBooJs ()
htmlConditionalCss ()
Creates conditional comments for IE.
htmlGeneratorMeta (array $attrs=array())
Returns meta generator tag for Boo.
htmlHeadAll ()
htmlPageCss ()
Returns the page specific CSS tags.
htmlPageJs ()
Returns the page specific JavaScript tags.
htmlTemplateCss ()
htmlTemplateJs ()
htmlTitle (array $attrs=array())
isAuth ()
isPostback ()
Determins if page is a postback.
isSsl ()
Determins if the page is secured with SSL.
isTemplate ($template)
Checks if page is a given template.
login ($username=false, $password=false, $redirect=true)
Login the user.
logout ($redirect=true)
Logout user.
redirect ($url= '/')
Redirects user to given URL.
requireAuth ($redirect=true)
Require authorization.
requireGroup ($group)
setTemplate ($template)
setTitle ($title)
Static Public Member Functions
static getIp ()
Returns IP address.
static headerContentType ($contentType= 'text/html', $charset= 'utf-8')
static headerNoCache ($contentLength=-1, $contentType= 'text/html', $charset= 'utf-8')
Public Attributes
$browser
Boo_Browser object.
$msgError
Boo_Dialog_MessageBox object.
$msgGlobal
Boo_Dialog_MessageBox object.
$msgSuccess
Boo_Dialog_MessageBox object.
$msgWarning
Boo_Dialog_MessageBox object.
$user
Boo_User object.
Protected Attributes
$pageCss = array()
Page specific JavaScript files.
$pageJs = array()
Page specific CSS files.
$template = 'default'
Page template.
Private Member Functions
setUser ($user)
Detailed Description
Page class.
This class is used to create and manipulate pages.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.8.4
Definition at line 16 of file Page.php.
Constructor & Destructor Documentation
Boo_Page::__construct ($ user = false)
Default constructor.
If the user is set a call to Boo_Page::setUser() is made with the supplied $user.
Parameters:
object $user[optional] The user.
Returns:
void This function does not set a return value.
Definition at line 84 of file Page.php.
References $user, $userId, and setUser().
Member Function Documentation
Boo_Page::addCss ($ href, $ media = 'screen')
Adds a CSS file.
Added for API compatibility.
Since:
2.0.0
See also:
Boo_Page::addPageCss()
Returns:
bool Function always returns TRUE.
Parameters:
string $href The href for the CSS file.
string $media[optional] The type of media for the CSS file.
Definition at line 456 of file Page.php.
References addPageCss().
Boo_Page::addJs ($ src)
Adds a JavaScript file.
Added for API compatibility.
Since:
2.0.0
See also:
Boo_Page::addPageJs()
Returns:
bool Function always returns TRUE.
Parameters:
string $src The source for the JavaScript file.
Definition at line 404 of file Page.php.
References addPageJs().
Boo_Page::addPageCss ($ href, $ media = false)
Adds a CSS file.
Since:
2.0.0
Returns:
bool Function always returns TRUE.
Parameters:
mixed $href The href for the CSS file or Boo_Html object.
string $media[optional] The type of media for the CSS file.
Definition at line 466 of file Page.php.
Referenced by addCss().
Boo_Page::addPageJs ($ src)
Adds a JavaScript file.
Since:
2.0.0
Returns:
bool Function always returns TRUE.
Parameters:
mixed $src The source for the JavaScript file or Boo_Html object.
Definition at line 413 of file Page.php.
Referenced by addJs().
Boo_Page::allowGroup ($ groupId)
Definition at line 800 of file Page.php.
References redirect().
Referenced by allowGroupAdmin(), allowGroupAnonymous(), allowGroupEmpty(), allowGroupRoot(), and allowGroupUser().
Boo_Page::allowGroupAdmin ()
Definition at line 822 of file Page.php.
References allowGroup().
Boo_Page::allowGroupAnonymous ()
Definition at line 826 of file Page.php.
References allowGroup().
Boo_Page::allowGroupEmpty ()
Definition at line 818 of file Page.php.
References allowGroup().
Boo_Page::allowGroupRoot ()
Definition at line 820 of file Page.php.
References allowGroup().
Boo_Page::allowGroupUser ()
Definition at line 824 of file Page.php.
References allowGroup().
Boo_Page::excludeGroup ($ groupId)
Definition at line 828 of file Page.php.
References redirect().
Referenced by excludeGroupAdmin(), excludeGroupAnonymous(), excludeGroupEmpty(), and excludeGroupUser().
Boo_Page::excludeGroupAdmin ()
Definition at line 848 of file Page.php.
References excludeGroup().
Boo_Page::excludeGroupAnonymous ()
Definition at line 852 of file Page.php.
References excludeGroup().
Boo_Page::excludeGroupEmpty ()
Definition at line 846 of file Page.php.
References excludeGroup().
Boo_Page::excludeGroupUser ()
Definition at line 850 of file Page.php.
References excludeGroup().
Boo_Page::forceSsl ()
Redirects users to the SSL version of the current page.
Function is ignored unless BOO_PRODUCTION is set to TRUE because SSL is rarely used in development enviroments.
Returns:
bool Returns TRUE if page is already secured with SSL.
Definition at line 254 of file Page.php.
References isSsl(), and redirect().
static Boo_Page::getIp () [static]
Returns IP address.
Returns:
mixed Returns the current users IP address if available, FALSE otherwise.
Definition at line 581 of file Page.php.
Boo_Page::getTemplate ()
Definition at line 280 of file Page.php.
Boo_Page::getTemplateCss ()
Definition at line 338 of file Page.php.
Referenced by htmlTemplateCss().
Boo_Page::getTemplateJs ()
Definition at line 321 of file Page.php.
Referenced by htmlTemplateJs().
Boo_Page::getTitle ()
Definition at line 567 of file Page.php.
Boo_Page::getUser ()
Returns the current user.
Returns:
object The user.
Definition at line 177 of file Page.php.
Boo_Page::hasTemplate ($ template, $ position = false)
Checks if page has a given template.
Parameters:
string $template The template to check.
int $position[optional] The required position of the template.
Returns:
bool Returns TRUE if page is that template, FALSE otherwise.
Definition at line 301 of file Page.php.
References $template.
static Boo_Page::headerContentType ($ contentType = 'text/html', $ charset = 'utf-8') [static]
Sets the Content-Type header.
This function is provided as a convenience.
Parameters:
string $contentType The content type, defaults to text/html.
string $charset The charset, defaults to utf-8.
Returns:
bool TURE if successful, FALSE otherwise.
Definition at line 649 of file Page.php.
Referenced by headerNoCache().
static Boo_Page::headerNoCache ($ contentLength = -1, $ contentType = 'text/html', $ charset = 'utf-8') [static]
Sets the headers for no cache.
This is usefull when making AJAX requests.
Parameters:
string $contentLength The content length, defaults to not set.
string $contentType The content type, defaults to text/html.
string $charset The charset, defaults to utf-8.
Returns:
bool Returns TURE if successful, FALSE otherwise.
Definition at line 619 of file Page.php.
References headerContentType().
Boo_Page::htmlBooCss ()
Definition at line 547 of file Page.php.
Referenced by htmlHeadAll().
Boo_Page::htmlBooJs ()
Definition at line 503 of file Page.php.
Referenced by htmlHeadAll().
Boo_Page::htmlConditionalCss ()
Creates conditional comments for IE.
Works with:
IE 6 = /css/ie6.css
IE 7 = /css/ie7.css
IE 8 = /css/ie8.css
Returns:
string Returns HTML conditional comments.
Definition at line 366 of file Page.php.
Referenced by htmlHeadAll().
Boo_Page::htmlGeneratorMeta (array $ attrs = array())
Returns meta generator tag for Boo.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
Boo_Html_Meta The meta generator tag for Boo.
Definition at line 859 of file Page.php.
Boo_Page::htmlHeadAll ()
Definition at line 378 of file Page.php.
References htmlBooCss(), htmlBooJs(), htmlConditionalCss(), htmlPageCss(), htmlPageJs(), htmlTemplateCss(), and htmlTemplateJs().
Boo_Page::htmlPageCss ()
Returns the page specific CSS tags.
Returns:
Boo_Html The page specific CSS tags.
Definition at line 488 of file Page.php.
Referenced by htmlHeadAll().
Boo_Page::htmlPageJs ()
Returns the page specific JavaScript tags.
Returns:
Boo_Html The page specific JavaScript tags.
Definition at line 430 of file Page.php.
Referenced by htmlHeadAll().
Boo_Page::htmlTemplateCss ()
Definition at line 340 of file Page.php.
References getTemplateCss().
Referenced by htmlHeadAll().
Boo_Page::htmlTemplateJs ()
Definition at line 323 of file Page.php.
References getTemplateJs().
Referenced by htmlHeadAll().
Boo_Page::htmlTitle (array $ attrs = array())
Definition at line 569 of file Page.php.
Boo_Page::isAuth ()
Determines if the user is authorized.
Provides a convenient API hook into the user object.
Returns:
bool TURE if authorized, FALSE otherwise.
Definition at line 797 of file Page.php.
Referenced by requireAuth().
Boo_Page::isPostback ()
Determins if page is a postback.
Returns:
bool Returns TRUE if page is a postback, FALSE otherwise.
Definition at line 238 of file Page.php.
Boo_Page::isSsl ()
Determins if the page is secured with SSL.
Returns:
bool Returns TRUE if page is secured with SSL, FALSE otherwise.
Definition at line 244 of file Page.php.
Referenced by forceSsl().
Boo_Page::isTemplate ($ template)
Checks if page is a given template.
Parameters:
string $template The template to check.
Returns:
bool Returns TRUE if page is that template, FALSE otherwise.
Todo:
Improve template support for child templates.
Definition at line 289 of file Page.php.
References $template.
Boo_Page::login ($ username = false, $ password = false, $ redirect = true)
Login the user.
Parameters:
string $username[optional] The username. If it is not set then Boo_User::getUsername() will be used.
string $password[optional] The password. If it is not set then Boo_User::getPassword() will be used.
mixed $redirect[optional] Redirect user to default URL if TRUE or to the value of $redirect if not FALSE.
Returns:
Returns TRUE if login was successful, FALSE otherwise.
Definition at line 690 of file Page.php.
References redirect().
Boo_Page::logout ($ redirect = true)
Logout user.
Parameters:
mixed $redirect[optional] Redirect user to default URL if TRUE or to the value of $redirect if not FALSE.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 660 of file Page.php.
References redirect().
Boo_Page::redirect ($ url = '/')
Redirects user to given URL.
Parameters:
string $url[optional] The URL to redirect to.
Returns:
void This function will always exit after redirect.
Definition at line 186 of file Page.php.
Referenced by allowGroup(), excludeGroup(), forceSsl(), login(), logout(), requireAuth(), and requireGroup().
Boo_Page::requireAuth ($ redirect = true)
Require authorization.
Parameters:
mixed $redirect[optional] Redirect user to default URL if TRUE or to the value of $redirect if not FALSE.
Returns:
bool Returns TRUE if authorized, FALSE otherwise. If $redirect is FALSE and authorization fails program will exit.
Definition at line 754 of file Page.php.
References isAuth(), and redirect().
Boo_Page::requireGroup ($ group)
Definition at line 592 of file Page.php.
References redirect().
Boo_Page::setTemplate ($ template)
Definition at line 268 of file Page.php.
References $template.
Boo_Page::setTitle ($ title)
Definition at line 557 of file Page.php.
Boo_Page::setUser ($ user) [private]
Sets the pages user.
This function is used to set the page user. The object should be of a type derived from Boo_User. It will overide the existing user. This is usefull if you want to extend the Boo_User object while retaning the functionality of the Boo_Page object. This method is called by the constructor.
See also:
Boo_User::__construct()
Parameters:
object $user The user.
Returns:
bool Function always returns TURE.
Definition at line 168 of file Page.php.
References $user.
Referenced by __construct().
Member Data Documentation
Boo_Page::$browser
Boo_Browser object.
This object is automatically initialized by the constructor if BOO_BROWSER is set to TRUE, otherwise $browser will be false.
Definition at line 23 of file Page.php.
Boo_Page::$msgError
Boo_Dialog_MessageBox object.
This object is automatically initialized by the constructor. Message box will contain any error messages generated by the page.
Definition at line 37 of file Page.php.
Boo_Page::$msgGlobal
Boo_Dialog_MessageBox object.
This object is automatically initialized by the constructor. Message box will contain any global messages generated by the page.
Definition at line 51 of file Page.php.
Boo_Page::$msgSuccess
Boo_Dialog_MessageBox object.
This object is automatically initialized by the constructor. Message box will contain any success messages generated by the page.
Definition at line 30 of file Page.php.
Boo_Page::$msgWarning
Boo_Dialog_MessageBox object.
This object is automatically initialized by the constructor. Message box will contain any warning messages generated by the page.
Definition at line 44 of file Page.php.
Boo_Page::$pageCss = array() [protected]
Page specific JavaScript files.
Definition at line 73 of file Page.php.
Boo_Page::$pageJs = array() [protected]
Page specific CSS files.
Definition at line 68 of file Page.php.
Boo_Page::$template = 'default' [protected]
Page template.
Definition at line 63 of file Page.php.
Referenced by hasTemplate(), isTemplate(), and setTemplate().
Boo_Page::$user
Boo_User object.
This object is automatically initialized by the constructor. User represents the current user accessing the page.
Definition at line 58 of file Page.php.
Referenced by __construct(), and setUser().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Page.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.