API Documentation for Boo-2.0.x: Boo_Lookup Class Reference
Boo_Lookup Class Reference
Lookup class.
Public Member Functions
__construct ($tableName=false, $primaryKey=false)
Default constructor.
addOrderBy ($columnName, $direction= 'ASC')
afterClose ($result)
Called after Boo_Lookup::close().
beforeClose ()
Called before Boo_Lookup::close().
clearCache ()
clearOrderBy ()
close ()
Close the object.
getArray ($value)
getAssocArray ($key, $value)
getCache ()
getFieldByPrimaryKey ($primaryKey, $field)
getOrderBy ()
getOrderBySql ()
getPrimaryKeyByField ($field, $value)
getSelectData ($key, $value)
hasCache ()
htmlCachePre ($attrs=array())
htmlSelect ($key, $value, $attrs=array())
isField ($field)
isFieldValue ($field, $value)
isPrimaryKey ($value)
open ($useCache=true)
removeOrderBy ($columnName)
setCache ($cache)
setOrderBy ($columnName, $direction= 'ASC')
Protected Member Functions
afterOpen ($result)
Called after Boo_Lookup::open().
beforeOpen ()
Called before Boo_Lookup::open().
Protected Attributes
$cache = false
Class instantance cache. Keeps DB requests to a minimum.
$orderBy = array()
Detailed Description
Lookup class.
This class is used to connect to retrieve lookup tables from a database.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.5
Definition at line 16 of file Lookup.php.
Constructor & Destructor Documentation
Boo_Lookup::__construct ($ tableName = false, $ primaryKey = false)
Default constructor.
Handles shorthand object initialization.
Parameters:
string $tableName[optional] The table name.
string $primaryKey[optional] The primary key.
Returns:
void.
Reimplemented from Boo_Db.
Definition at line 35 of file Lookup.php.
References Boo_Db::$primaryKey, Boo_Db::$tableName, Boo_Db::setPrimaryKey(), and Boo_Db::setTableName().
Member Function Documentation
Boo_Lookup::addOrderBy ($ columnName, $ direction = 'ASC')
Definition at line 76 of file Lookup.php.
References Boo_Validator::isSqlDirection(), and Boo_Validator::isSqlSafe().
Referenced by setOrderBy().
Boo_Lookup::afterClose ($ result)
Called after Boo_Lookup::close().
Parameters:
bool $result The result of Boo_Lookup::close().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 206 of file Lookup.php.
Referenced by close().
Boo_Lookup::afterOpen ($ result) [protected]
Called after Boo_Lookup::open().
Parameters:
bool $result The result of Boo_Lookup::open().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 165 of file Lookup.php.
Referenced by open().
Boo_Lookup::beforeClose ()
Called before Boo_Lookup::close().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 196 of file Lookup.php.
Referenced by close().
Boo_Lookup::beforeOpen () [protected]
Called before Boo_Lookup::open().
Returns:
bool Function always returns TRUE unless overridden by parent class.
Definition at line 155 of file Lookup.php.
Referenced by open().
Boo_Lookup::clearCache ()
Definition at line 210 of file Lookup.php.
Boo_Lookup::clearOrderBy ()
Definition at line 71 of file Lookup.php.
Referenced by setOrderBy().
Boo_Lookup::close ()
Close the object.
Provides API function for future implementation.
Todo:
Implement this function and preform cleanup.
Returns:
bool Always returns TRUE.
Definition at line 177 of file Lookup.php.
References afterClose(), and beforeClose().
Boo_Lookup::getArray ($ value)
Definition at line 242 of file Lookup.php.
References hasCache(), and isField().
Boo_Lookup::getAssocArray ($ key, $ value)
Definition at line 216 of file Lookup.php.
References hasCache(), and isField().
Referenced by getSelectData().
Boo_Lookup::getCache ()
Definition at line 374 of file Lookup.php.
Boo_Lookup::getFieldByPrimaryKey ($ primaryKey, $ field)
Definition at line 341 of file Lookup.php.
References Boo_Db::$primaryKey, hasCache(), isField(), and isPrimaryKey().
Boo_Lookup::getOrderBy ()
Definition at line 64 of file Lookup.php.
Boo_Lookup::getOrderBySql ()
Definition at line 46 of file Lookup.php.
Referenced by open().
Boo_Lookup::getPrimaryKeyByField ($ field, $ value)
Definition at line 317 of file Lookup.php.
References hasCache(), and isField().
Boo_Lookup::getSelectData ($ key, $ value)
Definition at line 276 of file Lookup.php.
References getAssocArray().
Referenced by htmlSelect().
Boo_Lookup::hasCache ()
Definition at line 372 of file Lookup.php.
Referenced by getArray(), getAssocArray(), getFieldByPrimaryKey(), getPrimaryKeyByField(), isField(), and isFieldValue().
Boo_Lookup::htmlCachePre ($ attrs = array())
Definition at line 385 of file Lookup.php.
Boo_Lookup::htmlSelect ($ key, $ value, $ attrs = array())
Definition at line 264 of file Lookup.php.
References $select, and getSelectData().
Boo_Lookup::isField ($ field)
Definition at line 280 of file Lookup.php.
References hasCache().
Referenced by getArray(), getAssocArray(), getFieldByPrimaryKey(), getPrimaryKeyByField(), and isFieldValue().
Boo_Lookup::isFieldValue ($ field, $ value)
Definition at line 291 of file Lookup.php.
References hasCache(), and isField().
Referenced by isPrimaryKey().
Boo_Lookup::isPrimaryKey ($ value)
Definition at line 313 of file Lookup.php.
References isFieldValue().
Referenced by getFieldByPrimaryKey().
Boo_Lookup::open ($ useCache = true)
Definition at line 110 of file Lookup.php.
References $e, afterOpen(), beforeOpen(), Boo_Db::connect(), and getOrderBySql().
Boo_Lookup::removeOrderBy ($ columnName)
Definition at line 98 of file Lookup.php.
Boo_Lookup::setCache ($ cache)
Definition at line 376 of file Lookup.php.
References $cache.
Boo_Lookup::setOrderBy ($ columnName, $ direction = 'ASC')
Definition at line 66 of file Lookup.php.
References addOrderBy(), and clearOrderBy().
Member Data Documentation
Boo_Lookup::$cache = false [protected]
Class instantance cache. Keeps DB requests to a minimum.
Definition at line 22 of file Lookup.php.
Referenced by setCache().
Boo_Lookup::$orderBy = array() [protected]
Definition at line 24 of file Lookup.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Lookup.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.