API Documentation for Boo-2.0.x: Boo_Html_Form_Xml Class Reference
Boo_Html_Form_Xml Class Reference
XML HTML form class.
Public Member Functions
__construct ($id=false)
Default constructor.
clearPost ()
Unsets the $_POST array.
getErrors ()
Gets the errors.
getErrorsArray ()
Gets errors as simple array.
getFilename ()
Returns the filename.
getIo ()
Gets the Boo_Io object;.
getValidationMethod ()
Gets the validation method.
html (array $attrs=array())
Returns the HTML for the form.
isPostback ()
Determins if form is posted.
isValid ()
Determins if the form is valid.
loadXmlForm ($filename=false, $force=false)
Loads form from XML file.
makeIo ()
Makes the IO object so you can use it.
open ($id, $filename=false)
Open form with an ID.
preloadPost (Boo_IO $io, $override=true)
Preloads values into $_POST.
setErrors (Boo_Html_Ol $errors)
Sets the errors object.
setFilename ($filename)
Sets the filename for the XML file.
setValidationMethod ($method)
Sets the validation method.
validate ()
Validates a form.
Public Attributes
$io
Boo_Io object for form.
Protected Member Functions
handleFormChild (SimpleXMLElement $child)
Handles a form child.
handleMakeIo (SimpleXMLElement $child)
Handles making the IO object.
handlePreloadPostXml (SimpleXMLElement $child, Boo_IO $io, $override)
Handles preloading values from XML file into $_POST.
handleValidateXml (SimpleXMLElement $child, &$totalValid)
isFormControl ($childName)
Determins if a child is a form control.
isFormControlHtml ($childName)
Determins if a child is a HTML form control.
isFormControlPhp ($childName)
Determins if a child is a PHP form control.
preloadPostXml (Boo_IO $io, $override)
Preloads values from XML file into $_POST.
validateXml ()
Validates a form using the XML validation method.
Protected Attributes
$errors
Boo_Html_Ol object for validation errors.
$filename = false
XML filename.
$validationMethod = 'xml'
The validation method.
$xmlForm = false
SimpleXMLElement object representing the form.
Private Member Functions
getFormContorlChildAttrs (SimpleXMLElement $child)
Returns a list of attributes added to the element.
handleFormControlChild (SimpleXMLElement $child)
Adds from contorls to existing Boo_Html item.
Detailed Description
XML HTML form class.
This class is used to generate HTML forms from an XML file.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.5
Definition at line 16 of file Xml.php.
Constructor & Destructor Documentation
Boo_Html_Form_Xml::__construct ($ id = false)
Default constructor.
Parameters:
string $id[optional] Form ID to open.
Returns:
void.
Reimplemented from Boo_Html.
Definition at line 49 of file Xml.php.
References Boo_Html_Form::__construct(), and open().
Member Function Documentation
Boo_Html_Form_Xml::clearPost ()
Unsets the $_POST array.
Returns:
bool Function always returns TRUE.
Definition at line 897 of file Xml.php.
Boo_Html_Form_Xml::getErrors ()
Gets the errors.
Returns:
Boo_Html_Ol Error list as an HTML object.
Definition at line 243 of file Xml.php.
Boo_Html_Form_Xml::getErrorsArray ()
Gets errors as simple array.
Returns:
array Errors in an array.
Todo:
This could be more efficent and it removes lots of other usefull info like classes.
Definition at line 251 of file Xml.php.
References $errors.
Boo_Html_Form_Xml::getFilename ()
Returns the filename.
Returns:
string The filename.
Definition at line 132 of file Xml.php.
Boo_Html_Form_Xml::getFormContorlChildAttrs (SimpleXMLElement $ child) [private]
Returns a list of attributes added to the element.
Parameters:
SimpleXMLElement $child The child.
Returns:
array The array of attributes, attributes used by the system are not returned.
Definition at line 452 of file Xml.php.
Referenced by handleFormControlChild().
Boo_Html_Form_Xml::getIo ()
Gets the Boo_Io object;.
Added for API compatibility. Boo_Html_Form_Xml::$io is public so this is technically not needed.
Returns:
Boo_Io Returns the Boo_Io object.
Definition at line 545 of file Xml.php.
References makeIo().
Boo_Html_Form_Xml::getValidationMethod ()
Gets the validation method.
Returns:
string The validation method.
Definition at line 89 of file Xml.php.
Boo_Html_Form_Xml::handleFormChild (SimpleXMLElement $ child) [protected]
Handles a form child.
Parameters:
SimpleXMLElement $child The form child.
Returns:
bool Returns TRUE on success, FALSE otherwise. Function is recursive.
Definition at line 824 of file Xml.php.
References Boo_Html::$attributes, Boo_Html::appendContent(), handleFormControlChild(), isFormControl(), isFormControlHtml(), and isFormControlPhp().
Referenced by html().
Boo_Html_Form_Xml::handleFormControlChild (SimpleXMLElement $ child) [private]
Adds from contorls to existing Boo_Html item.
Parameters:
SimpleXMLElement $child The XML child element.
Returns:
string Returns HTML on success, FALSE otherwise.
Todo:
Write a better array merge function.
Definition at line 616 of file Xml.php.
References $input, getFormContorlChildAttrs(), if, and Boo_Validator::isNull().
Referenced by handleFormChild().
Boo_Html_Form_Xml::handleMakeIo (SimpleXMLElement $ child) [protected]
Handles making the IO object.
Used recursivly by Boo_Html_Form_Xml::makeIo().
Returns:
bool Returns TRUE if form is valid, FALSE otherwise.
Parameters:
SimpleXMLElement $child The Simple XML child element.
Definition at line 561 of file Xml.php.
References $io, Boo_Format::format(), isFormControl(), and isValid().
Referenced by makeIo().
Boo_Html_Form_Xml::handlePreloadPostXml (SimpleXMLElement $ child, Boo_IO $ io, $ override) [protected]
Handles preloading values from XML file into $_POST.
This function is recursive.
Parameters:
SimpleXMLElement $child The current child element.
Boo_IO $io The Boo_IO object to use data.
bool $override Override existing values.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 330 of file Xml.php.
References isFormControl().
Referenced by preloadPostXml().
Boo_Html_Form_Xml::handleValidateXml (SimpleXMLElement $ child, &$ totalValid) [protected]
Used recursivly by Boo_Html_Form_Xml::validateXml().
Returns:
bool Returns TRUE on success, FALSE on error.
Parameters:
SimpleXMLElement $child Simple XML child element.
bool $totalValid Keeps track of the validity of the entire form.
Definition at line 383 of file Xml.php.
References _post(), isFormControl(), and word_bool().
Referenced by validateXml().
Boo_Html_Form_Xml::html (array $ attrs = array())
Returns the HTML for the form.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
string The HTML for the form, FALSE on error.
Reimplemented from Boo_Html.
Definition at line 908 of file Xml.php.
References Boo_Html::appendContent(), Boo_Html::getAttr(), handleFormChild(), and loadXmlForm().
Boo_Html_Form_Xml::isFormControl ($ childName) [protected]
Determins if a child is a form control.
Parameters:
string $childName The child name
Returns:
bool Returns TRUE if child is a form control, FALSE otherwise.
Definition at line 479 of file Xml.php.
Referenced by handleFormChild(), handleMakeIo(), handlePreloadPostXml(), and handleValidateXml().
Boo_Html_Form_Xml::isFormControlHtml ($ childName) [protected]
Determins if a child is a HTML form control.
Parameters:
string $childName The child name
Returns:
bool Returns TRUE if child is a HTML form control, FALSE otherwise.
Definition at line 506 of file Xml.php.
Referenced by handleFormChild().
Boo_Html_Form_Xml::isFormControlPhp ($ childName) [protected]
Determins if a child is a PHP form control.
Parameters:
string $childName The child name
Returns:
bool Returns TRUE if child is a PHP form control, FALSE otherwise.
Definition at line 516 of file Xml.php.
Referenced by handleFormChild().
Boo_Html_Form_Xml::isPostback ()
Determins if form is posted.
Definition at line 885 of file Xml.php.
References Boo_Html::getAttr().
Boo_Html_Form_Xml::isValid ()
Determins if the form is valid.
Returns:
bool Returns TRUE if form is valid, FALSE otherwise.
Reimplemented from Boo_Html.
Definition at line 282 of file Xml.php.
References validate().
Referenced by handleMakeIo().
Boo_Html_Form_Xml::loadXmlForm ($ filename = false, $ force = false)
Loads form from XML file.
Parameters:
string $filename[optional] The XML filename.
bool $force[optional] Force load even if form is already loaded.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 141 of file Xml.php.
References Boo_Html::$count, $filename, $form, $xml, Boo_Html::getAttr(), Boo_Html::setAttr(), setFilename(), and Boo_Helper::toFilenameCase().
Referenced by html(), makeIo(), open(), preloadPostXml(), and validateXml().
Boo_Html_Form_Xml::makeIo ()
Makes the IO object so you can use it.
Must be called before saving the IO object.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 527 of file Xml.php.
References handleMakeIo(), and loadXmlForm().
Referenced by getIo().
Boo_Html_Form_Xml::open ($ id, $ filename = false)
Open form with an ID.
This funciton provides API compatiblity. The same result can be achieved using Boo_Html_Form::loadXmlForm().
Parameters:
string $id The form ID.
string $filename The filename to open.
Returns:
bool Returns TRUE on success, FALSE on failure.
Definition at line 100 of file Xml.php.
References $filename, loadXmlForm(), and Boo_Html::setAttr().
Referenced by __construct().
Boo_Html_Form_Xml::preloadPost (Boo_IO $ io, $ override = true)
Preloads values into $_POST.
Parameters:
Boo_IO $io The Boo_Io object to use data.
bool $override[optional] Override existing values.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 291 of file Xml.php.
References preloadPostXml().
Boo_Html_Form_Xml::preloadPostXml (Boo_IO $ io, $ override) [protected]
Preloads values from XML file into $_POST.
Parameters:
Boo_IO $io The Boo_IO object to use data.
bool $override Override existing values.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 309 of file Xml.php.
References handlePreloadPostXml(), and loadXmlForm().
Referenced by preloadPost().
Boo_Html_Form_Xml::setErrors (Boo_Html_Ol $ errors)
Sets the errors object.
Parameters:
Boo_Html_Ol $errors The errors object.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 227 of file Xml.php.
References Boo_Html::isValid().
Boo_Html_Form_Xml::setFilename ($ filename)
Sets the filename for the XML file.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
string $filename The filename to set.
Definition at line 110 of file Xml.php.
References $filename.
Referenced by loadXmlForm().
Boo_Html_Form_Xml::setValidationMethod ($ method)
Sets the validation method.
Possible methods are:
xml
Parameters:
string $method The validation method.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Todo:
Add more validation methods.
Definition at line 70 of file Xml.php.
Boo_Html_Form_Xml::validate ()
Validates a form.
Returns:
bool Returns TRUE if valid, FALSE otherwise.
Definition at line 267 of file Xml.php.
References validateXml().
Referenced by isValid().
Boo_Html_Form_Xml::validateXml () [protected]
Validates a form using the XML validation method.
Parameters:
string $id[optional] Form ID.
Returns:
bool Returns TRUE if valid, FALSE otherwise.
Definition at line 365 of file Xml.php.
References handleValidateXml(), and loadXmlForm().
Referenced by validate().
Member Data Documentation
Boo_Html_Form_Xml::$errors [protected]
Boo_Html_Ol object for validation errors.
Definition at line 27 of file Xml.php.
Referenced by getErrorsArray().
Boo_Html_Form_Xml::$filename = false [protected]
XML filename.
Definition at line 42 of file Xml.php.
Referenced by loadXmlForm(), open(), and setFilename().
Boo_Html_Form_Xml::$io
Boo_Io object for form.
Definition at line 32 of file Xml.php.
Referenced by handleMakeIo().
Boo_Html_Form_Xml::$validationMethod = 'xml' [protected]
The validation method.
See also:
Boo_Html_Form::setValidationMethod() for possible methods.
Definition at line 22 of file Xml.php.
Boo_Html_Form_Xml::$xmlForm = false [protected]
SimpleXMLElement object representing the form.
Definition at line 37 of file Xml.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html/Form/Xml.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.