API Documentation for Boo-2.0.x: Boo_Helper Class Reference
Boo_Helper Class Reference
Helper class.
Static Public Member Functions
static addHttp ($url)
Adds http://.
static addHttps ($url)
Adds https://.
static getCountryNameByCode ($code)
Returns country name.
static getFileExtension ($filename)
Returns file extension.
static getStateCodeByName ($name)
Returns state code.
static getStateNameByCode ($code)
Returns state name.
static getUniqueMd5 ()
Returns a unique MD5 string.
static getUuid ()
Generates a Universally Unique IDentifier, version 4.
static removeCurrencySymbol ($price)
Removes the currency symbol.
static removeNonDecimal ($string)
Removes non decimal characters.
static removeNonNumeric ($string)
Removes non numeric characters.
static toCamelCase ($underscoredWord)
Returns the given lower case and underscored word as a lower camel caseed word.
static toFilenameCase ($mixedCase)
Returns given string in filename case.
static toPascalCase ($underscoredWord)
Returns the given lower case and underscored word as a Pascal case word.
static toUnderscoreCase ($camelCase)
Returns the given word as an underscored word.
Detailed Description
Helper class.
The helper class is used to preform many common functions that do not necessarily belong in other classes.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 17 of file Helper.php.
Member Function Documentation
static Boo_Helper::addHttp ($ url) [static]
Adds http://.
Adds http:// to the $url. If https:// or http:// is present then the original $url is returned.
Parameters:
string $url The url.
Returns:
string The formatted url.
Definition at line 82 of file Helper.php.
Referenced by Boo_Format::formatUri(), and Boo_Format::formatUrl().
static Boo_Helper::addHttps ($ url) [static]
Adds https://.
Adds https:// to the $url. If http:// is present, it is replaced with https://.
Parameters:
string $url The url.
Returns:
string The formatted url.
Definition at line 100 of file Helper.php.
static Boo_Helper::getCountryNameByCode ($ code) [static]
Returns country name.
Parameters:
string $code The country code.
Returns:
string The country name.
Definition at line 155 of file Helper.php.
References Boo_Validator::$countries.
Referenced by Boo_User::getCountryName().
static Boo_Helper::getFileExtension ($ filename) [static]
Returns file extension.
Updated to use PHP function pathinfo() instead. If the file is a backup file (ends in a tilde) then a tilde is returned regardles of extension.
Parameters:
string $filename The filename.
Returns:
string The file extension. If no file extension is included NULL returned, FALSE on error.
Definition at line 217 of file Helper.php.
Referenced by cFile(), and count_files().
static Boo_Helper::getStateCodeByName ($ name) [static]
Returns state code.
Parameters:
string $name The state name.
Returns:
string The state code.
Definition at line 135 of file Helper.php.
References Boo_Validator::$states.
Referenced by Boo_User::setStateName().
static Boo_Helper::getStateNameByCode ($ code) [static]
Returns state name.
Parameters:
string $code The state code.
Returns:
string The state name.
Definition at line 119 of file Helper.php.
References Boo_Validator::$states.
Referenced by Boo_User::getStateName().
static Boo_Helper::getUniqueMd5 () [static]
Returns a unique MD5 string.
Returns:
string Unique MD5 string.
Definition at line 239 of file Helper.php.
static Boo_Helper::getUuid () [static]
Generates a Universally Unique IDentifier, version 4.
See also:
http://www.ietf.org/rfc/rfc4122.txt
http://en.wikipedia.org/wiki/UUID
Returns:
string A UUID, made up of 32 hex digits and 4 hyphens.
Definition at line 250 of file Helper.php.
static Boo_Helper::removeCurrencySymbol ($ price) [static]
Removes the currency symbol.
You must correctly set BOO_CURRENCY_SYMBOL in your config file for this function to work.
Parameters:
string $price The price.
Returns:
string The formated price.
Definition at line 199 of file Helper.php.
Referenced by Boo_Format::formatPrice(), and Boo_Validator::isPrice().
static Boo_Helper::removeNonDecimal ($ string) [static]
Removes non decimal characters.
Removes all characters except [0123456789.] from a string.
Parameters:
string $string The string.
Returns:
string The formated string.
Definition at line 186 of file Helper.php.
static Boo_Helper::removeNonNumeric ($ string) [static]
Removes non numeric characters.
Removes all characters except [0123456789] from a string.
Parameters:
string $string The string.
Returns:
string The formated string.
Definition at line 173 of file Helper.php.
Referenced by Boo_Format::formatCardNumber(), Boo_Format::formatExpDate(), Boo_Format::formatPhoneExtension(), Boo_Format::formatPhoneNumber(), and Boo_Format::formatZip().
static Boo_Helper::toCamelCase ($ underscoredWord) [static]
Returns the given lower case and underscored word as a lower camel caseed word.
Parameters:
string $underscoredWord Word to convert.
Returns:
string Lower camel case word. likeThis.
Since:
2.0.0
Definition at line 39 of file Helper.php.
References toPascalCase().
Referenced by c().
static Boo_Helper::toFilenameCase ($ mixedCase) [static]
Returns given string in filename case.
Returns:
The string in filename case. like_this or like-this.
Parameters:
string $mixedCase The string to convert.
Since:
2.0.5
Definition at line 69 of file Helper.php.
References toUnderscoreCase().
Referenced by Boo_Html_Form_Xml::loadXmlForm().
static Boo_Helper::toPascalCase ($ underscoredWord) [static]
Returns the given lower case and underscored word as a Pascal case word.
Parameters:
string $underscoredWord Word to convert.
Returns:
string Pascal case word. LikeThis.
Copyright:
Copyright 2005-2008, Cake Software Foundation, Inc. (http://www.cakefoundation.org)
License:
http://www.opensource.org/licenses/mit-license.php The MIT License
Since:
2.0.0
Definition at line 28 of file Helper.php.
Referenced by toCamelCase().
static Boo_Helper::toUnderscoreCase ($ camelCase) [static]
Returns the given word as an underscored word.
Parameters:
string $camelCase Camel cased word to be underscorized.
Returns:
string Underscored version of the camel case word. like_this.
Copyright:
Copyright 2005-2008, Cake Software Foundation, Inc. (http://www.cakefoundation.org)
License:
http://www.opensource.org/licenses/mit-license.php The MIT License
Since:
2.0.0
Definition at line 58 of file Helper.php.
Referenced by toFilenameCase().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Helper.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.