API Documentation for Boo-2.0.x: Boo_AuthorizeNet Class Reference
Boo_AuthorizeNet Class Reference
Authorize.Net class.
Public Member Functions
__construct ()
Loads default values.
checkMd5 ()
getApprovalCode ()
The six-digit alphanumeric approval code.
getAvsResultCode ()
Indicates the result of AVS.
getCardCodeResponseCode ()
Indicates results of card code verification.
getCavvResponseCode ()
Indicates the results of cardholder authentication verification.
getField ($name)
Returns the field value.
getFieldsEncoded ()
Returns fields in field-value pairs.
getMd5Hash ()
Gets the MD5 hash.
getMode ()
Gets the current mode.
getResponse ()
The gateway response.
getResponseCode ()
Indicates the result of the transaction.
getResponseCodeWord ()
Returns the word associated with the response code.
getResponseReasonCode ()
A code representing details about the transaction.
getResponseReasonText ()
Brief description of the result.
getResponseSubcode ()
A code used by the system for internal transaction tracking.
getTransactionId ()
The transaction identification number.
getUrl ()
Gets the current URL.
htmlResultsUl (array $attrs=array(), $debug=BOO_DEBUG)
Gets the results as a HTML unordred list.
htmlTestForm (array $attrs=array())
Returns HTML test form.
isApproved ()
Determins if transaction is approved.
isDeclined ()
Determins if transaction is declined.
isError ()
Determins if transaction caused an error.
isHold ()
Determins if transaction is being held for review.
loadPost ()
Loads values from $_POST.
send ()
Sends the request to Authorize.Net.
setField ($name, $value)
Sets field value.
setMode ($mode)
testRequest ($value=true)
Sets the request to test mode.
Static Public Member Functions
static getCardTypes ()
Gets the card types.
static getExpDateMonths ()
Get expiration date months.
static getExpDateYears ()
Get the expiration date years.
Protected Attributes
$approvalCode = ''
Approval code. See AIM guide.
$avsResultCode = ''
AVS result code.
$cardCodeResponseCode = ''
Card code response code.
$cavvResponseCode = ''
CAVV response code.
$fields = array()
Fields array.
$md5Hash = ''
MD5 hash of transaction.
$mode = 'live'
Transaction mode.
$response = ''
Response. See AIM guide.
$responseCode = 0
Response code.
$responseReasonCode = 0
Response resone code. See AIM guide.
$responseReasonText = ''
Response resone text. See AIM guide.
$responseSubcode = 0
$transactionId = ''
Transaction identifier.
$url = 'https://secure.authorize.net/gateway/transact.dll'
Transaction URL. Must be secure!
Static Protected Attributes
static $cardTypes
Array of card types.
static $expDateMonths
Array of expiration date months.
static $expDateYears
Array of expiration date years.
Detailed Description
Authorize.Net class.
Implements the Authorize.Net AIM connection method.
Test credit card numbers.
370000000000002 = American Express.
6011000000000012 = Discover.
5424000000000015 = MasterCard.
4007000000027 = Visa.
4222222222222 = Test account, set amount to desired response reason code.
The following constants must be defined:
BOO_AUTHORIZE_NET_LOGIN_ID = Your Authorize.Net API Login ID.
BOO_AUTHORIZE_NET_TRAN_KEY = Your Authorize.Net Transaction Key.
BOO_AUTHORIZE_NET_DEFAULT_MODE = The Authorize.Net default mode (set to 'live', 'test', or 'certification').
BOO_AUTHORIZE_NET_MD5 = Your Authorize.Net MD5 hash, leave blank if your not sure.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Required:
http://curl.haxx.se/ cURL version 7.15.0 or greater. SSL support must be enabled.
See also:
http://ramaboo.com/code/authorizenet/ Advanced Integration Method (AIM) Developer Guide
http://www.authorize.net/support/aim_guide.pdf
http://curl.haxx.se/docs/install.html
Definition at line 33 of file AuthorizeNet.php.
Constructor & Destructor Documentation
Boo_AuthorizeNet::__construct ()
Loads default values.
Returns:
void.
Definition at line 150 of file AuthorizeNet.php.
References setMode().
Member Function Documentation
Boo_AuthorizeNet::checkMd5 ()
Checks the gateway MD5 response to make sure that it is correct.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 244 of file AuthorizeNet.php.
References getField().
Boo_AuthorizeNet::getApprovalCode ()
The six-digit alphanumeric approval code.
Returns:
string The approval code.
Definition at line 375 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getAvsResultCode ()
Indicates the result of AVS.
Posible values are:
A = Address (Street) matches, ZIP does not.
B = Address information not provided for AVS check.
E = AVS error.
G = Non-U.S. Card Issuing Bank.
N = No Match on Address (Street) or ZIP.
P = AVS not applicable for this transaction.
R = Retry - System unavailable or timed out.
S = Service not supported by issuer.
U = Address information is unavailable.
W = 9 digit ZIP matches, Address (Street) does not.
X = Address (Street) and 9 digit ZIP match.
Y = Address (Street) and 5 digit ZIP match.
Z = 5 digit ZIP matches, Address (Street) does not.
Returns:
string AVS result code.
Definition at line 397 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getCardCodeResponseCode ()
Indicates results of card code verification.
Posible values are:
M = Match.
N = No match.
P = Not processed.
S = Should have been present.
U = Issuer unable to process request.
Returns:
string The card code response code.
Definition at line 419 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
static Boo_AuthorizeNet::getCardTypes () [static]
Gets the card types.
Returns:
array Returns card types, key is a single letter, value is common name.
Definition at line 185 of file AuthorizeNet.php.
Boo_AuthorizeNet::getCavvResponseCode ()
Indicates the results of cardholder authentication verification.
Posible values are:
null (or empty string) = CAVV not validated.
0 = CAVV not validated because erroneous data was submitted.
1 = CAVV failed validation.
2 = CAVV passed validation.
3 = CAVV validation could not be performed; issuer attempt incomplete.
4 = CAVV validation could not be performed; issuer system error.
5 = Reserved for future use.
6 = Reserved for future use.
7 = CAVV attempt - failed validation - issuer available (U.S.-issued card/non-U.S acquirer).
8 = CAVV attempt - passed validation - issuer available (U.S.-issued card/non-U.S. acquirer).
9 = CAVV attempt - failed validation - issuer unavailable (U.S.-issued card/non-U.S. acquirer).
A = CAVV attempt - passed validation - issuer unavailable (U.S.-issued card/non-U.S. acquirer).
B = CAVV passed validation, information only, no liability shift.
Returns:
string The cardholder authentication verification value response code.
Definition at line 441 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
static Boo_AuthorizeNet::getExpDateMonths () [static]
Get expiration date months.
Returns:
array Returns expiration date months, key is 2 digit month, value is 2 digit month.
Definition at line 171 of file AuthorizeNet.php.
static Boo_AuthorizeNet::getExpDateYears () [static]
Get the expiration date years.
Returns:
array Returns expiration date years, key is 2 digit year, value is 4 digit year.
Definition at line 178 of file AuthorizeNet.php.
Boo_AuthorizeNet::getField ($ name)
Returns the field value.
Parameters:
string $name The field name.
Returns:
bool The field value if successful, FALSE otherwise.
Definition at line 476 of file AuthorizeNet.php.
Referenced by checkMd5().
Boo_AuthorizeNet::getFieldsEncoded ()
Returns fields in field-value pairs.
Returns:
string The fields in field-value pairs.
Definition at line 488 of file AuthorizeNet.php.
Referenced by send().
Boo_AuthorizeNet::getMd5Hash ()
Gets the MD5 hash.
Returns:
string The MD5 hash.
Definition at line 237 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getMode ()
Gets the current mode.
Returns:
string The mode.
Definition at line 225 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getResponse ()
The gateway response.
Returns:
string The gateway response.
Definition at line 275 of file AuthorizeNet.php.
Boo_AuthorizeNet::getResponseCode ()
Indicates the result of the transaction.
Posible values are:
0 = Response code is not yet set.
1 = This transaction has been approved.
2 = This transaction has been declined.
3 = There has been an error processing this transaction.
4 = This transaction is being held for review.
Returns:
int The response code.
Definition at line 289 of file AuthorizeNet.php.
Referenced by getResponseCodeWord(), and htmlResultsUl().
Boo_AuthorizeNet::getResponseCodeWord ()
Returns the word associated with the response code.
Possible return values are:
unset
approved
declined
error
held
Returns:
string The word associated with the response code (lowercase), FALSE on failure.
Definition at line 303 of file AuthorizeNet.php.
References getResponseCode().
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getResponseReasonCode ()
A code representing details about the transaction.
Returns:
int The response reason code.
Definition at line 363 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getResponseReasonText ()
Brief description of the result.
Returns:
int The response reason text.
Definition at line 369 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getResponseSubcode ()
A code used by the system for internal transaction tracking.
Returns:
int The response subcode.
Definition at line 357 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getTransactionId ()
The transaction identification number.
10 digit number.
Returns:
string The transaction id.
Definition at line 405 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::getUrl ()
Gets the current URL.
Returns:
string The URL.
Definition at line 231 of file AuthorizeNet.php.
Referenced by htmlResultsUl().
Boo_AuthorizeNet::htmlResultsUl (array $ attrs = array(), $ debug = BOO_DEBUG)
Gets the results as a HTML unordred list.
Parameters:
array $attrs[optional] Array of attributes.
bool $debug[optional] Debug mode.
Returns:
Boo_Html_Ul The results link as a HTML unordred list, FALSE on failure.
Warning:
This method will display sensitive information including everything sent to Authorize.Net. Be careful how you use it!
Definition at line 616 of file AuthorizeNet.php.
References $ul, getApprovalCode(), getAvsResultCode(), getCardCodeResponseCode(), getCavvResponseCode(), getMd5Hash(), getMode(), getResponseCode(), getResponseCodeWord(), getResponseReasonCode(), getResponseReasonText(), getResponseSubcode(), getTransactionId(), and getUrl().
Boo_AuthorizeNet::htmlTestForm (array $ attrs = array())
Returns HTML test form.
This function is usefully for generating a simple HTML form for testing Authorize.Net transactions. This form should only be used for testing purposes and is not secure.
Parameters:
array $attrs[optional] Array of attributes.
Returns:
Boo_Html_Form The HTML form on success, FALSE otherwise.
Definition at line 587 of file AuthorizeNet.php.
References $form, and $ol.
Boo_AuthorizeNet::isApproved ()
Determins if transaction is approved.
Returns:
bool Returns TRUE if approved, FALSE otherwise.
Definition at line 333 of file AuthorizeNet.php.
Boo_AuthorizeNet::isDeclined ()
Determins if transaction is declined.
Returns:
bool Returns TURE if declined, FALSE otherwise.
Definition at line 339 of file AuthorizeNet.php.
Boo_AuthorizeNet::isError ()
Determins if transaction caused an error.
Returns:
bool Returns TRUE if error, FALSE otherwise.
Definition at line 345 of file AuthorizeNet.php.
Boo_AuthorizeNet::isHold ()
Determins if transaction is being held for review.
Returns:
bool Returns TRUE if transaction is on hold, FALSE otherwise.
Definition at line 351 of file AuthorizeNet.php.
Boo_AuthorizeNet::loadPost ()
Loads values from $_POST.
Returns:
int Returns number of values loaded, 0 if nothing was loaded.
Definition at line 551 of file AuthorizeNet.php.
References setField().
Boo_AuthorizeNet::send ()
Sends the request to Authorize.Net.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 502 of file AuthorizeNet.php.
References getFieldsEncoded().
Boo_AuthorizeNet::setField ($ name, $ value)
Sets field value.
Parameters:
string $name The field name.
string $value The field value.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
Definition at line 450 of file AuthorizeNet.php.
Referenced by loadPost(), and testRequest().
Boo_AuthorizeNet::setMode ($ mode)
Sets the mode.
Posible values are:
live = For production use.
test = Test mode.
certification = Certification mode.
Parameters:
string $mode The mode.
Returns:
bool Returns TURE if mode was set, FALSE otherwise.
Warning:
Test mode and certification mode can cause problems try Boo_AuthorizeNet::testRequest() if you recieve error 13.
Definition at line 201 of file AuthorizeNet.php.
References $mode.
Referenced by __construct().
Boo_AuthorizeNet::testRequest ($ value = true)
Sets the request to test mode.
Returns:
bool Function always returns TRUE.
Parameters:
bool $value[optional] Set to TRUE for test mode, FALSE for normal mode.
Definition at line 569 of file AuthorizeNet.php.
References setField().
Member Data Documentation
Boo_AuthorizeNet::$approvalCode = '' [protected]
Approval code. See AIM guide.
Definition at line 74 of file AuthorizeNet.php.
Boo_AuthorizeNet::$avsResultCode = '' [protected]
AVS result code.
See also:
Boo_AuthorizeNet::getAvsResultCode()
Definition at line 80 of file AuthorizeNet.php.
Boo_AuthorizeNet::$cardCodeResponseCode = '' [protected]
Card code response code.
See also:
Boo_AuthorizeNet::getCardCodeResponseCode()
Definition at line 99 of file AuthorizeNet.php.
Boo_AuthorizeNet::$cardTypes [static, protected]
Initial value:
 array(
        'v' => 'Visa',
        'm' => 'MasterCard',
        'a' => 'American Express',
        'd' => 'Discover')
Array of card types.
Definition at line 140 of file AuthorizeNet.php.
Boo_AuthorizeNet::$cavvResponseCode = '' [protected]
CAVV response code.
See also:
Boo_AuthorizeNet::getCavvResponseCode()
Definition at line 105 of file AuthorizeNet.php.
Boo_AuthorizeNet::$expDateMonths [static, protected]
Initial value:
 array(
        '01' => '01', '02' => '02', '03' => '03', '04' => '04',
        '05' => '05', '06' => '06', '07' => '07', '08' => '08',
        '09' => '09', '10' => '10', '11' => '11', '12' => '12')
Array of expiration date months.
Definition at line 122 of file AuthorizeNet.php.
Boo_AuthorizeNet::$expDateYears [static, protected]
Initial value:
 array(
        '09' => '2009', '10' => '2010', '11' => '2011', '12' => '2012',
        '13' => '2013', '14' => '2014', '15' => '2015', '16' => '2016',
        '17' => '2017', '18' => '2018', '19' => '2019', '20' => '2020',
        '21' => '2021', '22' => '2022', '23' => '2023', '24' => '2024',
        '25' => '2025', '26' => '2026', '27' => '2027', '28' => '2028')
Array of expiration date years.
Definition at line 130 of file AuthorizeNet.php.
Boo_AuthorizeNet::$fields = array() [protected]
Fields array.
Definition at line 38 of file AuthorizeNet.php.
Boo_AuthorizeNet::$md5Hash = '' [protected]
MD5 hash of transaction.
Definition at line 93 of file AuthorizeNet.php.
Boo_AuthorizeNet::$mode = 'live' [protected]
Transaction mode.
See also:
Boo_AuthorizeNet::setMode();
Definition at line 111 of file AuthorizeNet.php.
Referenced by setMode().
Boo_AuthorizeNet::$response = '' [protected]
Response. See AIM guide.
Definition at line 44 of file AuthorizeNet.php.
Boo_AuthorizeNet::$responseCode = 0 [protected]
Response code.
See also:
Boo_AuthorizeNet::getResponseCode()
Definition at line 50 of file AuthorizeNet.php.
Boo_AuthorizeNet::$responseReasonCode = 0 [protected]
Response resone code. See AIM guide.
Definition at line 62 of file AuthorizeNet.php.
Boo_AuthorizeNet::$responseReasonText = '' [protected]
Response resone text. See AIM guide.
Definition at line 68 of file AuthorizeNet.php.
Boo_AuthorizeNet::$responseSubcode = 0 [protected]
Response subcode. See AIM guide.
Definition at line 56 of file AuthorizeNet.php.
Boo_AuthorizeNet::$transactionId = '' [protected]
Transaction identifier.
10 digit string.
Warning:
Do not store as INT. Value can be greater than 2147483647 or 4294967295. BIGINT or CHAR(10) are safe.
Definition at line 88 of file AuthorizeNet.php.
Boo_AuthorizeNet::$url = 'https://secure.authorize.net/gateway/transact.dll' [protected]
Transaction URL. Must be secure!
Definition at line 117 of file AuthorizeNet.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/AuthorizeNet.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.