API Documentation for Boo-2.0.x: Boo_Error Class Reference
Boo_Error Class Reference
Error class.
Public Member Functions
__construct ()
Default constructor.
dbError (array $ignore=array(), $tableName= 'boo_errors', $primaryKey= 'error_id')
emailError (array $ignore=array())
getCookie ()
getCreated ()
getDomain ()
getEnv ()
getError ()
getErrorString ()
getFilename ()
getFiles ()
getGet ()
getGlobals ()
getIp ()
getLine ()
getPost ()
getRequest ()
getServer ()
getSession ()
getSymbols ()
getUserAgent ()
getUuid ()
handleError ($error, $errorString, $filename, $line, $symbols)
htmlErrorDiv (array $attrs=array())
logError (array $ignore=array(), $filename=BOO_ERROR_LOG_FILE)
setError ($error, $errorString, $filename, $line, $symbols)
smsError (array $ignore=array())
Static Public Member Functions
static errorHandlerCallback ($error, $errorString, $filename, $line, $symbols)
Error handler callback method.
static getErrorName ($error)
static isCritical ($error)
Determins if an error is critical.
static start ($errorTypes=false)
Automaticly setup error handing to default settings.
Protected Attributes
$cookie = ''
$created = 0
Timestamp of error.
$domain = BOO_DOMAIN
Domain name.
$env = ''
$error = 0
Error number.
$errorString = ''
Error string.
$filename = ''
Filename.
$files = ''
$get = ''
$globals = ''
Local copies of PHP superglobals as serialized data.
$ip = ''
IP Address.
$line = 0
Line number.
$post = ''
$request = ''
$server = ''
$session = ''
$symbols = ''
Symbols table as serialized data.
$userAgent = ''
User agent.
$uuid = ''
Error UUID.
Detailed Description
Error class.
Used to handle PHP errors.
Error constant values:
E_ERROR = 1
E_WARNING = 2
E_PARSE = 4
E_NOTICE = 8
E_CORE_ERROR = 16
E_CORE_WARNING = 32
E_COMPILE_ERROR = 64
E_COMPILE_WARNING = 128
E_USER_ERROR = 256
E_USER_WARNING = 512
E_USER_NOTICE = 1024
E_ALL = 32767 in PHP 6, 30719 in PHP 5.3.x, 6143 in PHP 5.2.x
E_STRICT = 2048
E_RECOVERABLE_ERROR = 4096
E_DEPRECATED = 8192 since PHP 5.3.0
E_USER_DEPRECATED = 16384 since PHP 5.3.0
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.8.1
Definition at line 34 of file Error.php.
Constructor & Destructor Documentation
Boo_Error::__construct ()
Default constructor.
Copies superglobals to the class instance and serializes them.
See also:
http://us3.php.net/reserved.variables
Returns:
void.
Definition at line 98 of file Error.php.
References $cookie, $e, $env, $files, $get, $globals, $post, $request, $server, $session, getIp(), getUuid(), and globals().
Member Function Documentation
Boo_Error::dbError (array $ ignore = array(), $ tableName = 'boo_errors', $ primaryKey = 'error_id')
Definition at line 309 of file Error.php.
References $io, and globals().
Referenced by handleError().
Boo_Error::emailError (array $ ignore = array())
Definition at line 375 of file Error.php.
References $e, and getErrorName().
Referenced by handleError().
static Boo_Error::errorHandlerCallback ($ error, $ errorString, $ filename, $ line, $ symbols) [static]
Error handler callback method.
Parameters:
int $error Error level.
string $errorString Error message.
string $filename Filename that caused the error.
string $line The line number
array $symbols The active symbols table.
Returns:
bool Function always returns FALSE.
Definition at line 675 of file Error.php.
References $error, $errorString, $filename, $line, and $symbols.
Boo_Error::getCookie ()
Definition at line 220 of file Error.php.
Boo_Error::getCreated ()
Definition at line 232 of file Error.php.
Boo_Error::getDomain ()
Definition at line 198 of file Error.php.
Boo_Error::getEnv ()
Definition at line 226 of file Error.php.
Boo_Error::getError ()
Definition at line 200 of file Error.php.
static Boo_Error::getErrorName ($ error) [static]
Definition at line 236 of file Error.php.
References $error.
Referenced by emailError(), htmlErrorDiv(), logError(), and smsError().
Boo_Error::getErrorString ()
Definition at line 202 of file Error.php.
Boo_Error::getFilename ()
Definition at line 204 of file Error.php.
Boo_Error::getFiles ()
Definition at line 218 of file Error.php.
Boo_Error::getGet ()
Definition at line 214 of file Error.php.
Boo_Error::getGlobals ()
Definition at line 210 of file Error.php.
References globals().
Boo_Error::getIp ()
Definition at line 230 of file Error.php.
Referenced by __construct().
Boo_Error::getLine ()
Definition at line 206 of file Error.php.
Boo_Error::getPost ()
Definition at line 216 of file Error.php.
Boo_Error::getRequest ()
Definition at line 224 of file Error.php.
Boo_Error::getServer ()
Definition at line 212 of file Error.php.
Boo_Error::getSession ()
Definition at line 222 of file Error.php.
Boo_Error::getSymbols ()
Definition at line 208 of file Error.php.
Boo_Error::getUserAgent ()
Definition at line 228 of file Error.php.
Boo_Error::getUuid ()
Definition at line 234 of file Error.php.
Referenced by __construct().
Boo_Error::handleError ($ error, $ errorString, $ filename, $ line, $ symbols)
Definition at line 631 of file Error.php.
References $error, $errorString, $filename, $line, $symbols, dbError(), emailError(), htmlErrorDiv(), setError(), and smsError().
Boo_Error::htmlErrorDiv (array $ attrs = array())
Definition at line 449 of file Error.php.
References getErrorName(), and globals().
Referenced by handleError().
static Boo_Error::isCritical ($ error) [static]
Determins if an error is critical.
Errors that are not considered critical:
E_NOTICE
E_USER_NOTICE
E_USER_WARNING
E_DEPRECATED
E_USER_DEPRECATED
E_ALL
Errors that are considered critical:
E_ERROR
E_WARNING
E_PARSE
E_CORE_ERROR
E_CORE_WARNING
E_COMPILE_WARNING
E_COMPILE_ERROR
E_USER_ERROR
E_STRICT
E_RECOVERABLE_ERROR
Parameters:
int $error The error code.
Returns:
bool Returns TRUE if error is critical, FALSE othereise.
Definition at line 602 of file Error.php.
References $error.
Boo_Error::logError (array $ ignore = array(), $ filename = BOO_ERROR_LOG_FILE)
Definition at line 340 of file Error.php.
References $filename, getErrorName(), and Boo_Log::write().
Boo_Error::setError ($ error, $ errorString, $ filename, $ line, $ symbols)
Definition at line 180 of file Error.php.
References $e, $error, $errorString, $filename, $line, and $symbols.
Referenced by handleError().
Boo_Error::smsError (array $ ignore = array())
Definition at line 427 of file Error.php.
References $sms, and getErrorName().
Referenced by handleError().
static Boo_Error::start ($ errorTypes = false) [static]
Automaticly setup error handing to default settings.
Returns:
string Returns the result of set_error_handler().
See also:
http://us.php.net/set_error_handler
Parameters:
int $errorTypes[optional] Can be used to mask the triggering of Boo_Error::errorHandlerCallback().
Definition at line 657 of file Error.php.
Member Data Documentation
Boo_Error::$cookie = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$created = 0 [protected]
Timestamp of error.
Definition at line 83 of file Error.php.
Boo_Error::$domain = BOO_DOMAIN [protected]
Domain name.
Definition at line 38 of file Error.php.
Boo_Error::$env = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$error = 0 [protected]
Error number.
Definition at line 43 of file Error.php.
Referenced by errorHandlerCallback(), getErrorName(), handleError(), isCritical(), and setError().
Boo_Error::$errorString = '' [protected]
Error string.
Definition at line 48 of file Error.php.
Referenced by errorHandlerCallback(), handleError(), and setError().
Boo_Error::$filename = '' [protected]
Filename.
Definition at line 53 of file Error.php.
Referenced by errorHandlerCallback(), handleError(), logError(), and setError().
Boo_Error::$files = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$get = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$globals = '' [protected]
Local copies of PHP superglobals as serialized data.
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$ip = '' [protected]
IP Address.
Definition at line 78 of file Error.php.
Boo_Error::$line = 0 [protected]
Line number.
Definition at line 58 of file Error.php.
Referenced by errorHandlerCallback(), handleError(), and setError().
Boo_Error::$post = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$request = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$server = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$session = '' [protected]
Definition at line 68 of file Error.php.
Referenced by __construct().
Boo_Error::$symbols = '' [protected]
Symbols table as serialized data.
Definition at line 63 of file Error.php.
Referenced by errorHandlerCallback(), handleError(), and setError().
Boo_Error::$userAgent = '' [protected]
User agent.
Definition at line 73 of file Error.php.
Boo_Error::$uuid = '' [protected]
Error UUID.
Definition at line 88 of file Error.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Error.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.