API Documentation for Boo-2.0.x: Boo_Validator Class Reference
Boo_Validator Class Reference
Validator class.
Public Member Functions
__construct ()
Default constructor.
Static Public Member Functions
static getCountries ()
Returns an array of countries.
static getGreekLetters ()
Gets the greek letters array.
static getStates ()
Returns an array of states.
static getTrueFalse ()
Gets the true or false array.
static getYesNo ()
Validates a value.
static isAlpha ($string, $min=false, $max=false)
Determins if a value is alphabetic.
static isAlphaNum ($string, $min=false, $max=false)
Determins if a value is alphanumeric.
static isAlphaNumExtended ($string, $min=false, $max=false, $firstChar=false)
Determins if a value is alphanumeric plus some common characters.
static isAlphaNumPlus ($string, $min=false, $max=false, $firstChar=false)
Determins if a value is alphanumeric plus the undersocre.
static isApartmentNumber ($apt, $min=1, $max=16)
Determins if a value is an apartment number or not.
static isBasename ($basename)
Determins if a string is a valid basename.
static isBooId ($id)
static isCardNumber ($cardNumber)
Determins if a credit card number is valid.
static isCardNumberMasked ($cardNumber)
Determins if a credit card number is masked.
static isChecked ($value)
Determines if a checkbox is checked.
static isCity ($city, $min=2, $max=32)
Determins if a value is a city or not.
static isCountry ($country)
Determins if value is a country name or country code.
static isCountryCode ($code)
Determins if a country code is valid.
static isCountryName ($name)
Determins if a country name is valid.
static isDate ($date)
static isDateFormat ($date, $format)
Determins if a string is a date of a given format.
static isEmail ($email)
Determins if an email address is valid.
static isEmailAvailable ($email)
Determines if a email address is availiable.
static isEven ($value)
Determins if a value is even.
static isExpDate ($expDate)
Determins if an expiration date is valid.
static isFilename ($filename)
Determins if a string is a valid filename.
static isFloat ($string, $min=false, $max=false)
Determins if a string is a float.
static isHex ($string, $min=false, $max=false)
Determins if string contains only hexadecimal characters.
static isHtml ($string)
Determins if a value contains html.
static isInt ($string, $min=false, $max=false)
Determins if a string is an integer.
static isName ($name, $min=2, $max=32)
Determins if a value is a name or not.
static isNull ($string)
Determins if a value is null.
static isNumeric ($string, $min=false, $max=false)
Determins if a string is numeric.
static isOdd ($value)
Determins if a value is odd.
static isPassword ($password)
Determins if a password is valid.
static isPhoneExtension ($phoneExt)
Determins if a phone extension is valid.
static isPhoneNumber ($phoneNumber)
Determins if a phone number is valid.
static isPostMatch ($value, $post)
Determins if a value matchs the posted value with a given key.
static isPrice ($string, $min=false, $max=false)
Determins if a string is a price.
static isPrintable ($string, $min=false, $max=false)
Determins if string contains only ASCII printable characters.
static isRequired ($value)
Determins if a required value is set.
static isSocialSecurityNumber ($ssNumber)
Determins if string is a Social Security number.
static isSqlDirection ($string)
Determins if string is an SQL direction.
static isSqlSafe ($string, $min=false, $max=false)
Checks if string is safe to use in an SQL statement.
static isState ($state)
Determins if value is a state name or state code.
static isStateCode ($code)
Determins if a state code is valid.
static isStateName ($name)
Determins if a state name is valid.
static isStreet ($street, $min=2, $max=48)
Determins if a value is a street or not.
static isString ($string, $min=false, $max=false)
Determins if a value is a string or not.
static isTrueFalse ($value, $allowWord=false)
Determins if value is true or false (1 or 0).
static isTrueFalseWord ($value)
Determins if value is a true or false word.
static isUpload ($name)
Determins if a file has been uploaded ok.
static isUploadBlank ($name)
Determins if an uploaded file has a blank name.
static isUploadExtension ($name)
Determins if an uploaded file has a valid extension.
static isUploadExtensionAllowed ($name, $extensions)
Determins if file extension is allowed on an uploaded file.
static isUploadPartial ($name)
Determins if an uploaded file was only partially upaded.
static isUploadRequired ($name)
Determins if a file has been uploaded ok.
static isUploadSize ($name)
Determins if uploaded file is less than the maximum size.
static isUri ($uri)
Determins if a URI is valid.
static isUrl ($url)
Determins if a URL is valid.
static isUsername ($username)
Determines if a username is valid.
static isUsernameAvailable ($username)
Determines if a username is availiable.
static isVin ($vin)
Validates a vehical identification number aginst the ISO 3779 standard.
static isYesNo ($value, $allowWord=false)
Determins if value is a yes or no (1 or 0).
static isYesNoWord ($value)
Determins if value is a yes or no word.
static isZip ($zip)
Determins if a ZIP code is valid.
static validate ($value, $validationRule, $required=true)
Static Protected Attributes
static $countries
Array of countries.
static $greekLetters
Array of Greek letters.
static $states
Array of states.
static $trueFalse
Quick array for doing true and false.
static $yesNo
Quick array for doing yes and no.
Detailed Description
Validator class.
This class is used to validate data.
Boo validation functions ignore leading and trailing whitespace. For example Boo_Validator::isInt(" 16 ") will return TRUE.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.0
Definition at line 19 of file Validator.php.
Constructor & Destructor Documentation
Boo_Validator::__construct ()
Default constructor.
Returns:
void.
Definition at line 394 of file Validator.php.
Member Function Documentation
static Boo_Validator::getCountries () [static]
Returns an array of countries.
Returns:
array Array of states. Key is the country code, value is country name with the first letter capitalized.
Definition at line 406 of file Validator.php.
Referenced by Boo_Html_Select::htmlCountriesSelect().
static Boo_Validator::getGreekLetters () [static]
Gets the greek letters array.
Returns:
array Returns greek letters array. The key is the value of the lettter, value is the English word.
Definition at line 439 of file Validator.php.
static Boo_Validator::getStates () [static]
Returns an array of states.
Returns:
array Array of states. Key is the state code, value is state name with the first letter capitalized.
Definition at line 400 of file Validator.php.
Referenced by Boo_Html_Select::htmlStatesSelect().
static Boo_Validator::getTrueFalse () [static]
Gets the true or false array.
Returns:
array Returns true or false array. The key is the integer, value is the word.
Definition at line 447 of file Validator.php.
static Boo_Validator::getYesNo () [static]
Validates a value.
Use # (pound sign) in the validation rule to represent the value.
You should only use this function if you need to store a validation rule as a string of text such as in an xml file for use with Boo_Form. Calling member functions directly is much more efficient.
Parameters:
string $value The value to validate.
string $validationRule The validation code (must be valid PHP).
bool $required[optional] Value is required (not null).
Returns:
bool Returns TRUE if validation was successful, FALSE otherwise.
 Boo_Validator::validate(5, "Boo_Validator::isInt(#, 3, 8);", true);
 // returns TRUE
Gets the yes or no array.
Returns:
array Returns yes or no array. The key is the integer, value is the word.
Definition at line 431 of file Validator.php.
static Boo_Validator::isAlpha ($ string, $ min = false, $ max = false) [static]
Determins if a value is alphabetic.
Alphabetic is defined as [A-Za-z].
Parameters:
string $string The value to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
Returns:
bool Returns TRUE if value is alphabetic, FALSE otherwise.
See also:
http://us3.php.net/manual/en/function.ctype-alpha.php
Definition at line 511 of file Validator.php.
Referenced by isAlphaNumExtended(), and isAlphaNumPlus().
static Boo_Validator::isAlphaNum ($ string, $ min = false, $ max = false) [static]
Determins if a value is alphanumeric.
Alphanumeric is defined as [A-Za-z0-9].
Parameters:
string $string The value to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
Returns:
bool Returns TRUE if value is alphanumeric, FALSE otherwise.
See also:
http://us3.php.net/manual/en/function.ctype-alnum.php
Definition at line 537 of file Validator.php.
static Boo_Validator::isAlphaNumExtended ($ string, $ min = false, $ max = false, $ firstChar = false) [static]
Determins if a value is alphanumeric plus some common characters.
Alphanumeric is defined as [A-Za-z0-9_-.()].
Parameters:
string $string The value to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
bool $firstChar[optional] If TRUE the first character must be a letter.
Returns:
bool Returns TRUE if value is alphanumeric, FALSE otherwise.
Todo:
Maybe add more characters.
Definition at line 595 of file Validator.php.
References isAlpha().
Referenced by isApartmentNumber().
static Boo_Validator::isAlphaNumPlus ($ string, $ min = false, $ max = false, $ firstChar = false) [static]
Determins if a value is alphanumeric plus the undersocre.
Alphanumeric is defined as [A-Za-z0-9_].
Parameters:
string $string The value to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
bool $firstChar[optional] If TRUE the first character must be a letter.
Returns:
bool Returns TRUE if value is alphanumeric, FALSE otherwise.
Definition at line 563 of file Validator.php.
References isAlpha().
Referenced by isUsername(), and Boo_Twitter::setUsername().
static Boo_Validator::isApartmentNumber ($ apt, $ min = 1, $ max = 16) [static]
Determins if a value is an apartment number or not.
Provides API compatibility.
Attention:
Apartment numbers do not have to be numeric.
Parameters:
string $apt The apartment number to test.
integer $min[optional] The minimum length of the apartment number.
integer $max[optional] The maximum length of the apartment number.
Todo:
Improve support and provide additional tests.
Returns:
bool Returns TRUE if it is a street, FALSE otherwise.
Definition at line 978 of file Validator.php.
References isAlphaNumExtended().
Referenced by Boo_User::setApartmentNumber().
static Boo_Validator::isBasename ($ basename) [static]
Determins if a string is a valid basename.
Warning:
Function does not clean basenames of unsafe characters.
Parameters:
string $basename The basename to test
Returns:
bool Returns TRUE if basename is valid, FALSE otherwise.
Todo:
This function could be much better.
Definition at line 1693 of file Validator.php.
References isString().
static Boo_Validator::isBooId ($ id) [static]
Definition at line 812 of file Validator.php.
static Boo_Validator::isCardNumber ($ cardNumber) [static]
Determins if a credit card number is valid.
Warning:
Uses the Luhn algorithm to check for validity. This may not work correctly for more obsucre credit cards.
See also:
http://en.wikipedia.org/wiki/Luhn_algorithm
Returns:
bool Returns TRUE if card number is valid, FALSE otherwise.
Parameters:
string $cardNumber The card number to test.
Definition at line 1128 of file Validator.php.
Referenced by Boo_Format::formatCardNumber().
static Boo_Validator::isCardNumberMasked ($ cardNumber) [static]
Determins if a credit card number is masked.
Checks if the first 4 digits of the card number are ****. This function is used to check account information after a user has submited updates. If the card number is masked then they have likely not updated it and it can be ignored (not saved). This is just a quick check and should only be used to determin if a card number should be saved or not. It does not check against manipulation of the card number itself.
Warning:
This function does not check the validity of the masked credit card number
Returns:
bool Returns TRUE if credit card number is masked, FALSE otherwise.
Parameters:
object $cardNumber
Definition at line 1108 of file Validator.php.
static Boo_Validator::isChecked ($ value) [static]
Determines if a checkbox is checked.
Because of the way PHP handles checkboxes this is the same as Boo_Validator::isRequired(). Included for API compatibility.
Parameters:
string $value
Returns:
bool Returns TRUE if checkbox is checked, FALSE otherwise.
Definition at line 1532 of file Validator.php.
References isRequired().
static Boo_Validator::isCity ($ city, $ min = 2, $ max = 32) [static]
Determins if a value is a city or not.
Provides API compatibility.
Parameters:
string $street The city to test.
integer $min[optional] The minimum length of the city.
integer $max[optional] The maximum length of the city.
Todo:
Improve support and provide additional tests.
Returns:
bool Returns TRUE if it is a city, FALSE otherwise.
Definition at line 993 of file Validator.php.
References isString().
Referenced by Boo_User::setCity().
static Boo_Validator::isCountry ($ country) [static]
Determins if value is a country name or country code.
Returns:
bool Returns TRUE if country is a valid country name or country code.
Parameters:
string $country The country name or code to test.
Definition at line 903 of file Validator.php.
References isCountryCode(), and isCountryName().
static Boo_Validator::isCountryCode ($ code) [static]
Determins if a country code is valid.
Returns:
bool Returns TRUE if country code is valid, FALSE otherwise.
Parameters:
string $code The country code to test.
Definition at line 912 of file Validator.php.
Referenced by isCountry(), Boo_User::setCountry(), and Boo_User::setCountryCode().
static Boo_Validator::isCountryName ($ name) [static]
Determins if a country name is valid.
Returns:
bool Returns TRUE if country code is valid, FALSE otherwise.
Parameters:
string $name The country name to test.
Definition at line 926 of file Validator.php.
Referenced by isCountry(), Boo_User::setCountry(), and Boo_User::setCountryName().
static Boo_Validator::isDate ($ date) [static]
Definition at line 823 of file Validator.php.
static Boo_Validator::isDateFormat ($ date, $ format) [static]
Determins if a string is a date of a given format.
This only supports time formats supported by the PHP date() function and strtotime().
Parameters:
string $date The date to test.
mixed $format The date format. Accepts a single format as a string or an array of formats.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Todo:
Test function.
Definition at line 838 of file Validator.php.
static Boo_Validator::isEmail ($ email) [static]
Determins if an email address is valid.
Returns:
bool Returns TRUE if email address is valid, FALSE otherwise.
Parameters:
string $email The email address to test.
Definition at line 1033 of file Validator.php.
Referenced by Boo_Format::formatEmail(), isEmailAvailable(), Boo_User::isUser(), Boo_User::open(), Boo_User::setEmail(), and Boo_Twitter::showUserByEmail().
static Boo_Validator::isEmailAvailable ($ email) [static]
Determines if a email address is availiable.
Parameters:
string $email The email address.
Returns:
bool Returns TRUE if email address is available, FALSE if already in use.
Definition at line 1406 of file Validator.php.
References isEmail().
static Boo_Validator::isEven ($ value) [static]
Determins if a value is even.
Parameters:
mixed $value The value to test.
Returns:
bool Returns TRUE if value is even, FALSE otherwise.
Definition at line 1427 of file Validator.php.
static Boo_Validator::isExpDate ($ expDate) [static]
Determins if an expiration date is valid.
Expiration date can be in the following formats:
MMYY
MM/YY
MM-YY
MMYYYY
MM/YYYY
MM-YYYY
YYYY-MM-DD
YYYY/MM/DD
See also:
Boo_Format::formatExpDate
Parameters:
string $expDate The expiration date to test.
Returns:
bool Returns TRUE if expiration date is valid, FALSE otherwise.
Definition at line 1175 of file Validator.php.
static Boo_Validator::isFilename ($ filename) [static]
Determins if a string is a valid filename.
Warning:
Function does not clean filenames of unsafe characters.
Parameters:
string $filename The filename to test
Returns:
bool Returns TRUE if filename is valid, FALSE otherwise.
Todo:
This function could be much better.
Definition at line 1680 of file Validator.php.
References isString().
static Boo_Validator::isFloat ($ string, $ min = false, $ max = false) [static]
Determins if a string is a float.
Parameters:
string $string The test string.
int $min Minimum value of the number.
int $max Maximum value of the number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 737 of file Validator.php.
static Boo_Validator::isHex ($ string, $ min = false, $ max = false) [static]
Determins if string contains only hexadecimal characters.
See also:
Boo_Charset::getHex().
Parameters:
string $string The string to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
Returns:
bool Returns TRUE if string contains only hexadecimal characters, FALSE otherwise.
Definition at line 655 of file Validator.php.
static Boo_Validator::isHtml ($ string) [static]
Determins if a value contains html.
Parameters:
mixed $string The string to test.
Returns:
bool Returns TRUE if tags are found, FALSE if no tags are found.
Definition at line 1438 of file Validator.php.
static Boo_Validator::isInt ($ string, $ min = false, $ max = false) [static]
Determins if a string is an integer.
Preforms the same function as the built in PHP function ctype_digit() except this will allow negative integers and does not require a string variable.
Parameters:
string $string The test string.
int $min Minimum value of the number.
int $max Maximum value of the number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
See also:
http://us3.php.net/manual/en/function.ctype-digit.php
Definition at line 796 of file Validator.php.
Referenced by Boo_LoremIpsum::getWords(), Boo_LoremIpsum::htmlPs(), Boo_LoremIpsum::htmlUl(), and Boo_Qrbg::setPort().
static Boo_Validator::isName ($ name, $ min = 2, $ max = 32) [static]
Determins if a value is a name or not.
Provides API compatibility.
Parameters:
string $name The name to test.
integer $min[optional] The minimum length of the name.
integer $max[optional] The maximum length of the name.
Todo:
Improve support and provide additional tests.
Returns:
bool Returns TRUE if it is a name, FALSE otherwise.
Definition at line 947 of file Validator.php.
References isString().
Referenced by Boo_User::setFirstName(), and Boo_User::setLastName().
static Boo_Validator::isNull ($ string) [static]
Determins if a value is null.
Important! This is not the same as is_null().
The following values are considered null:
A string with only spaces.
An empty string.
NULL.
FALSE.
An empty array.
Parameters:
mixed $string The string to test.
Returns:
bool Returns TRUE if value is null, FALSE otherwise.
Todo:
Fix to test objects.
Definition at line 1461 of file Validator.php.
Referenced by Boo_Format::formatExpDate(), Boo_Format::formatPrice(), Boo_Html_Select::getDefaultIndex(), Boo_Csv::getFields(), Boo_Html_Select::getSelectedIndex(), Boo_Html_Form_Xml::handleFormControlChild(), Boo_User::hasApartmentNumber(), Boo_Html_Select::hasTitle(), Boo_Html_Select::html(), isRequired(), Boo_Io::open(), Boo_Io::save(), Boo_Html::setAttr(), and Boo_Html_Select::setTitle().
static Boo_Validator::isNumeric ($ string, $ min = false, $ max = false) [static]
Determins if a string is numeric.
Preforms the same function as the built in PHP function is_numeric().
Parameters:
string $string The test string.
int $min Minimum value of the number.
int $max Maximum value of the number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
See also:
http://us3.php.net/manual/en/function.is-numeric.php
Definition at line 713 of file Validator.php.
static Boo_Validator::isOdd ($ value) [static]
Determins if a value is odd.
Parameters:
mixed $value The value to test.
Returns:
bool Returns TRUE if value is odd, FALSE otherwise.
Definition at line 1416 of file Validator.php.
static Boo_Validator::isPassword ($ password) [static]
Determins if a password is valid.
Parameters:
string $password The password.
Returns:
bool Returns TRUE if password is valid, FALSE otherwise.
Todo:
Add support for complex password testing.
Definition at line 1483 of file Validator.php.
References isString().
Referenced by Boo_User::setPassword(), and Boo_Qrbg::setPassword().
static Boo_Validator::isPhoneExtension ($ phoneExt) [static]
Determins if a phone extension is valid.
Valid formats are:
x123456
123456
Where 123456 can be any number from 1 to 999999.
Returns:
bool Returns TRUE if extension is valid, FALSE otherwise.
Parameters:
string $phoneExt The phone extension to test.
Definition at line 1074 of file Validator.php.
static Boo_Validator::isPhoneNumber ($ phoneNumber) [static]
Determins if a phone number is valid.
Returns:
bool Returns TRUE if phone number is valid, FALSE otherwise.
Parameters:
string $phoneNumber The phone number to test.
Definition at line 1043 of file Validator.php.
Referenced by Boo_Format::formatPhoneNumber(), Boo_User::setFaxNumber(), Boo_User::setPhoneNumber(), and Boo_User::setSmsNumber().
static Boo_Validator::isPostMatch ($ value, $ post) [static]
Determins if a value matchs the posted value with a given key.
Parameters:
string $value The value to test.
string $post The key for the $_POST array.
Returns:
bool Returns TRUE if they match, FALSE otherwise.
Definition at line 1505 of file Validator.php.
static Boo_Validator::isPrice ($ string, $ min = false, $ max = false) [static]
Determins if a string is a price.
The maximum price is 16 characters or 14 with 2 decimal places. This is the same as MySQL 5 datatype decimal(16,2).
Parameters:
string $string The test string.
int $min Minimum value of the number.
int $max Maximum value of the number.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 764 of file Validator.php.
References Boo_Helper::removeCurrencySymbol().
Referenced by Boo_Format::formatPrice().
static Boo_Validator::isPrintable ($ string, $ min = false, $ max = false) [static]
Determins if string contains only ASCII printable characters.
See also:
Boo_Charset::getPrintable().
Parameters:
string $string The string to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
Returns:
bool Returns TRUE if string contains only ASCII printable characters, FALSE otherwise.
Definition at line 625 of file Validator.php.
References Boo_Charset::getPrintable().
static Boo_Validator::isRequired ($ value) [static]
Determins if a required value is set.
Parameters:
mixed $value The value to test.
Returns:
bool Returns TRUE if value is set, FALSE otherwise.
Definition at line 1493 of file Validator.php.
References isNull().
Referenced by isChecked().
static Boo_Validator::isSocialSecurityNumber ($ ssNumber) [static]
Determins if string is a Social Security number.
Social Security number can be in any format. Use Boo_Format::formatSocialSecurityNumber() if you want the data properly formated.
Warning:
This function is only a rough validator as it does not check for reserved numbers such as 666-xx-xxxx or xxx-xx-0000, etc.
Returns:
bool Returns TRUE if string is a Socical Security number, FALSE otherwise.
Parameters:
string $ssNumber The string to test.
See also:
http://en.wikipedia.org/wiki/Social_security_number
Definition at line 687 of file Validator.php.
Referenced by Boo_Format::formatSocialSecurityNumber().
static Boo_Validator::isSqlDirection ($ string) [static]
Determins if string is an SQL direction.
Used by the ORDER BY SQL statment. Possible directions are:
ASC
DESC
Returns:
bool Returns TRUE if string is an SQL direction, FALSE otherwise.
Parameters:
string $string The string to test.
Definition at line 1254 of file Validator.php.
Referenced by Boo_Lookup::addOrderBy().
static Boo_Validator::isSqlSafe ($ string, $ min = false, $ max = false) [static]
Checks if string is safe to use in an SQL statement.
Safe characters are all letters, numbers, dash, and the underscore.
Parameters:
$string The string to test.
integer $min[optional] The minimum length of the name.
integer $max[optional] The maximum length of the name.
Returns:
bool Returns TRUE if string is safe, FALSE otherwise.
Definition at line 1226 of file Validator.php.
Referenced by Boo_Lookup::addOrderBy(), Boo_Io::exists(), Boo_Db::setPrimaryKey(), and Boo_Db::setTableName().
static Boo_Validator::isState ($ state) [static]
Determins if value is a state name or state code.
Returns:
bool Returns TRUE if state is a valid state name or state code.
Parameters:
string $state The state name or code to test.
Definition at line 864 of file Validator.php.
References isStateCode(), and isStateName().
static Boo_Validator::isStateCode ($ code) [static]
Determins if a state code is valid.
Returns:
bool Returns TRUE if state code is valid, FALSE otherwise.
Parameters:
string $code The state code to test.
Definition at line 873 of file Validator.php.
Referenced by isState(), Boo_User::setState(), and Boo_User::setStateCode().
static Boo_Validator::isStateName ($ name) [static]
Determins if a state name is valid.
Returns:
bool Returns TRUE if state name is valid, FALSE otherwise.
Parameters:
string $name The state name to test.
Definition at line 887 of file Validator.php.
Referenced by isState(), Boo_User::setState(), and Boo_User::setStateName().
static Boo_Validator::isStreet ($ street, $ min = 2, $ max = 48) [static]
Determins if a value is a street or not.
Provides API compatibility.
Parameters:
string $street The street to test.
integer $min[optional] The minimum length of the street.
integer $max[optional] The maximum length of the street.
Todo:
Improve support and provide additional tests.
Returns:
bool Returns TRUE if it is a street, FALSE otherwise.
Definition at line 962 of file Validator.php.
References isString().
Referenced by Boo_User::setStreet().
static Boo_Validator::isString ($ string, $ min = false, $ max = false) [static]
Determins if a value is a string or not.
Parameters:
string $string The value to test.
integer $min[optional] The minimum length of the string.
integer $max[optional] The maximum length of the string.
Returns:
bool Returns TRUE if it is a string, FALSE otherwise.
Definition at line 485 of file Validator.php.
Referenced by isBasename(), isCity(), isFilename(), isName(), isPassword(), isStreet(), Boo_Twitter::setApplicationSource(), Boo_User::setCompany(), Boo_Group::setDescription(), Boo_Group::setName(), and Boo_Twitter::setPassword().
static Boo_Validator::isTrueFalse ($ value, $ allowWord = false) [static]
Determins if value is true or false (1 or 0).
Returns:
bool Returns TRUE if true or false, FALSE otherwise.
Parameters:
string $value The value to test.
bool $allowWord[optional] Allow words 'true' and 'false' to be used as well.
Definition at line 1734 of file Validator.php.
References isTrueFalseWord().
static Boo_Validator::isTrueFalseWord ($ value) [static]
Determins if value is a true or false word.
Returns:
bool Returns TRUE if value is a 'true' or 'false' (case insensitive), FALSE otherwise.
Parameters:
string $value The value to test.
Definition at line 1751 of file Validator.php.
References array_change_value_case().
Referenced by isTrueFalse().
static Boo_Validator::isUpload ($ name) [static]
Determins if a file has been uploaded ok.
Will not cause error if nothing was uploaded.
See also:
Boo_Validator::isUploadRequired().
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1545 of file Validator.php.
static Boo_Validator::isUploadBlank ($ name) [static]
Determins if an uploaded file has a blank name.
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1601 of file Validator.php.
static Boo_Validator::isUploadExtension ($ name) [static]
Determins if an uploaded file has a valid extension.
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1659 of file Validator.php.
static Boo_Validator::isUploadExtensionAllowed ($ name, $ extensions) [static]
Determins if file extension is allowed on an uploaded file.
Parameters:
string $name The name of the file as an key in the $_FILES array.
array $extensions The array of allowed extensions.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1638 of file Validator.php.
static Boo_Validator::isUploadPartial ($ name) [static]
Determins if an uploaded file was only partially upaded.
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1619 of file Validator.php.
static Boo_Validator::isUploadRequired ($ name) [static]
Determins if a file has been uploaded ok.
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1563 of file Validator.php.
static Boo_Validator::isUploadSize ($ name) [static]
Determins if uploaded file is less than the maximum size.
Attention:
Wierd logic, but its tested and works.
Parameters:
string $name The name of the file as an key in the $_FILES array.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 1583 of file Validator.php.
static Boo_Validator::isUri ($ uri) [static]
Determins if a URI is valid.
Returns:
bool Returns TRUE if URI is valid, FALSE otherwise.
Parameters:
string $uri The URI to test.
Definition at line 1013 of file Validator.php.
static Boo_Validator::isUrl ($ url) [static]
Determins if a URL is valid.
Returns:
bool Returns TRUE if URL is valid, FALSE otherwise.
Parameters:
string $uri The URL to test.
Definition at line 1023 of file Validator.php.
Referenced by Boo_User::setWebsite().
static Boo_Validator::isUsername ($ username) [static]
Determines if a username is valid.
Provides API compatibility.
Parameters:
string $username The username.
Returns:
bool Returns TRUE if username is valid, FALSE if already in use.
Definition at line 1386 of file Validator.php.
References isAlphaNumPlus(), Boo_User::MAX_USERNAME_LENGTH, and Boo_User::MIN_USERNAME_LENGTH.
Referenced by isUsernameAvailable(), Boo_User::setUsername(), and Boo_Qrbg::setUsername().
static Boo_Validator::isUsernameAvailable ($ username) [static]
Determines if a username is availiable.
Parameters:
string $username The username.
Returns:
bool Returns TRUE if username is available, FALSE if already in use.
Definition at line 1396 of file Validator.php.
References isUsername().
static Boo_Validator::isVin ($ vin) [static]
Validates a vehical identification number aginst the ISO 3779 standard.
1M8GDM9AXKP042788 is a valid VIN (used for testing).
See also:
http://ramaboo.com/code/is_vin/
http://code.google.com/p/isvin/
http://en.wikipedia.org/wiki/Vehicle_identification_number
Parameters:
string $vin The vehical identification number.
Returns:
bool Returns TRUE if the vehical identification number is valid, FALSE otherwise.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.1.3
 if (is_vin('1M8GDM9AXKP042788')) {
    echo 'valid';
 } else {
    echo 'not valid';
 }
Todo:
Test and support ISO 3780.
Definition at line 1287 of file Validator.php.
static Boo_Validator::isYesNo ($ value, $ allowWord = false) [static]
Determins if value is a yes or no (1 or 0).
Returns:
bool Returns TRUE if yes or no, FALSE otherwise.
Parameters:
string $value The value to test.
bool $allowWord[optional] Allow words 'yes' and 'no' to be used as well.
Definition at line 1703 of file Validator.php.
References isYesNoWord().
static Boo_Validator::isYesNoWord ($ value) [static]
Determins if value is a yes or no word.
Returns:
bool Returns TRUE if value is 'yes' or 'no' (case insensitive), FALSE otherwise.
Parameters:
string $value The value to test.
Definition at line 1720 of file Validator.php.
References array_change_value_case().
Referenced by isYesNo().
static Boo_Validator::isZip ($ zip) [static]
Determins if a ZIP code is valid.
Returns:
bool Returns TRUE if ZIP code is valid, FALSE otherwise.
Parameters:
string $zip The ZIP code to test.
Todo:
Add support for other countries.
Definition at line 1003 of file Validator.php.
Referenced by Boo_Format::formatZip(), and Boo_User::setZip().
static Boo_Validator::validate ($ value, $ validationRule, $ required = true) [static]
Definition at line 451 of file Validator.php.
References quote().
Member Data Documentation
Boo_Validator::$countries [static, protected]
Array of countries.
The array contains the country names (official short names in English) in alphabetical order as given in ISO 3166-1 and the corresponding ISO 3166-1-alpha-2 code. The array index is the ISO 3166-1-alpha-2 code in strtoupper format. The array value is the short country name in ucword format (with the exception of the words "of, "and", "the). There are currently 246 countries in the array.
Updated 2008-08-08.
See also:
http://www.iso.org/iso/country_codes/iso_3166_code_lists/
Definition at line 34 of file Validator.php.
Referenced by Boo_Helper::getCountryNameByCode().
Boo_Validator::$greekLetters [static, protected]
Initial value:
 array(
        1 => 'Alpha',
        2 => 'Beta',
        3 => 'Gamma',
        4 => 'Delta',
        5 => 'Epsilon',
        7 => 'Zeta',
        8 => 'Eta',
        9 => 'Theta',
        10 => 'Iota',
        20 => 'Kappa',
        30 => 'Lambda',
        40 => 'Mu',
        50 => 'Nu',
        60 => 'Xi',
        70 => 'Omicron',
        80 => 'Pi',
        100 => 'Rho',
        200 => 'Sigma',
        300 => 'Tau',
        400 => 'Upsilon',
        500 => 'Phi',
        600 => 'Chi',
        700 => 'Psi',
        800 => 'Omega')
Array of Greek letters.
See also:
http://en.wikipedia.org/wiki/Greek_alphabet Key is numeric value, value is the English word.
Definition at line 349 of file Validator.php.
Boo_Validator::$states [static, protected]
Array of states.
The array contains all 50 state names plus the District of Columbia in alphabetical order and the corisponding abbreviations. The array index is the state abbreviation in strtoupper format. The array value is the state name in ucword format (with the exception of the word "of"). There are currently 51 states in the array.
Definition at line 290 of file Validator.php.
Referenced by Boo_Helper::getStateCodeByName(), and Boo_Helper::getStateNameByCode().
Boo_Validator::$trueFalse [static, protected]
Initial value:
 array(
        1 => 'True',
        0 => 'False')
Quick array for doing true and false.
Definition at line 386 of file Validator.php.
Boo_Validator::$yesNo [static, protected]
Initial value:
 array(
        1 => 'Yes',
        0 => 'No')
Quick array for doing yes and no.
Definition at line 379 of file Validator.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Validator.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.