API Documentation for Boo-2.0.x: Boo_Twitter Class Reference
Boo_Twitter Class Reference
Twitter class.
Public Member Functions
__construct ($username=false, $password=false)
Default constructor.
createBlock ($id)
createFavorite ($id)
createFriendship ($id)
destroyBlock ($id)
destroyFavorite ($id)
destroyFriendship ($id)
destroyMessage ($id)
destroyStatus ($id)
endSession ()
follow ($id)
friendshipExists ($userA, $userB)
getArchive ($page=1)
getCredentials ()
getDowntimeSchedule ()
getFavorites ($id=null, $page=1)
getFeatured ()
getFollowers ($id=null, $page=1, $lite=false)
getFriends ($id=null)
getFriendsTimeline ($id=null, $since=null)
getMessages ($since=null, $sinceId=0, $page=1)
getPublicTimeline ($sinceId=0)
getRateLimitStatus ()
getReplies ($page=0)
getSentMessages ($since=null, $sinceId=0, $page=1)
getSession ()
getUsername ()
getUserTimeline ($id=null, $count=20, $since=null)
hasSession ()
lastApiCall ()
lastStatusCode ()
leave ($id)
newMessage ($user, $text)
openSession ()
saveSession ()
setApplicationSource ($source)
setFormat ($format)
setPassword ($password)
setUsername ($username)
showStatus ($id)
showUser ($id)
showUserByEmail ($email)
showUserByScreenName ($screenName)
test ()
updateDeliveryDevice ($device)
updateLocation ($location)
Updates location. .
updateStatus ($status)
verifyCredentials ()
Static Public Member Functions
static getSupportedDevices ()
static getSupportedFormats ()
static isSupportedDevice ($device)
static isSupportedFormat ($format)
Public Attributes
const MAX_PASSWORD_LENGTH = 30
Maximum length of password.
const MAX_USERNAME_LENGTH = 15
Maximum length of username.
const MIN_PASSWORD_LENGTH = 6
Minimum length of password.
const MIN_USERNAME_LENGTH = 1
Minimum length of username.
Protected Member Functions
afterApiCall ($twitterData)
apiCall ($apiUrl, $requireCredentials=false, $httpPost=false)
beforeApiCall ($apiUrl)
Protected Attributes
$applicationSource = 'boo'
Contains the application calling the API.
$format = 'xml'
Return format.
$httpStatus = false
Contains the last HTTP status code returned.
$lastApiCall = false
Contains the last API call.
$password = false
Twitter password.
$username = false
Twitter username.
Static Protected Attributes
static $supportedDevices = array('sms', 'im', 'none')
static $supportedFormats = array('xml', 'json', 'rss', 'atom')
Array of supported formats.
Detailed Description
Twitter class.
This class is used to interact with the Twitter API.
Based on twitterlibphp by Justin Poliey.
License:
http://www.opensource.org/licenses/mit-license.php MIT License
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://github.com/jdp/twitterlibphp/ twitterlibphp
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 Justin Poliey
Copyright:
2009 David Singer
Author:
Justin Poliey <jdp34@njit.edu>
David Singer <david@ramaboo.com>
Version:
2.0.1
See also:
http://apiwiki.twitter.com/
Definition at line 23 of file Twitter.php.
Constructor & Destructor Documentation
Boo_Twitter::__construct ($ username = false, $ password = false)
Default constructor.
Returns:
void.
Parameters:
string $username[optional] Twitter username.
string $password[optional] Twitter password.
Reimplemented from Boo_Db.
Definition at line 93 of file Twitter.php.
References $password, $username, setPassword(), and setUsername().
Member Function Documentation
Boo_Twitter::afterApiCall ($ twitterData) [protected]
Definition at line 533 of file Twitter.php.
Referenced by apiCall().
Boo_Twitter::apiCall ($ apiUrl, $ requireCredentials = false, $ httpPost = false) [protected]
Definition at line 493 of file Twitter.php.
References afterApiCall(), beforeApiCall(), getCredentials(), and lastApiCall().
Referenced by createBlock(), createFavorite(), createFriendship(), destroyBlock(), destroyFavorite(), destroyFriendship(), destroyMessage(), destroyStatus(), endSession(), follow(), friendshipExists(), getArchive(), getDowntimeSchedule(), getFavorites(), getFeatured(), getFollowers(), getFriends(), getFriendsTimeline(), getMessages(), getPublicTimeline(), getRateLimitStatus(), getReplies(), getSentMessages(), getUserTimeline(), leave(), newMessage(), showStatus(), showUser(), showUserByEmail(), showUserByScreenName(), test(), updateDeliveryDevice(), updateLocation(), updateStatus(), and verifyCredentials().
Boo_Twitter::beforeApiCall ($ apiUrl) [protected]
Definition at line 529 of file Twitter.php.
Referenced by apiCall().
Boo_Twitter::createBlock ($ id)
Definition at line 473 of file Twitter.php.
References apiCall().
Boo_Twitter::createFavorite ($ id)
Definition at line 453 of file Twitter.php.
References apiCall().
Boo_Twitter::createFriendship ($ id)
Definition at line 366 of file Twitter.php.
References apiCall().
Boo_Twitter::destroyBlock ($ id)
Definition at line 478 of file Twitter.php.
References apiCall().
Boo_Twitter::destroyFavorite ($ id)
Definition at line 458 of file Twitter.php.
References apiCall().
Boo_Twitter::destroyFriendship ($ id)
Definition at line 371 of file Twitter.php.
References apiCall().
Boo_Twitter::destroyMessage ($ id)
Definition at line 361 of file Twitter.php.
References apiCall().
Boo_Twitter::destroyStatus ($ id)
Definition at line 259 of file Twitter.php.
References apiCall().
Boo_Twitter::endSession ()
Definition at line 397 of file Twitter.php.
References apiCall().
Boo_Twitter::follow ($ id)
Definition at line 463 of file Twitter.php.
References apiCall().
Boo_Twitter::friendshipExists ($ userA, $ userB)
Definition at line 376 of file Twitter.php.
References apiCall().
Boo_Twitter::getArchive ($ page = 1)
Definition at line 430 of file Twitter.php.
References apiCall().
Boo_Twitter::getCredentials ()
Definition at line 150 of file Twitter.php.
Referenced by apiCall().
Boo_Twitter::getDowntimeSchedule ()
Definition at line 488 of file Twitter.php.
References apiCall().
Boo_Twitter::getFavorites ($ id = null, $ page = 1)
Definition at line 438 of file Twitter.php.
References apiCall().
Boo_Twitter::getFeatured ()
Definition at line 296 of file Twitter.php.
References apiCall().
Boo_Twitter::getFollowers ($ id = null, $ page = 1, $ lite = false)
Definition at line 276 of file Twitter.php.
References apiCall().
Boo_Twitter::getFriends ($ id = null)
Definition at line 264 of file Twitter.php.
References apiCall().
Boo_Twitter::getFriendsTimeline ($ id = null, $ since = null)
Definition at line 207 of file Twitter.php.
References apiCall().
Boo_Twitter::getMessages ($ since = null, $ sinceId = 0, $ page = 1)
Definition at line 324 of file Twitter.php.
References apiCall().
Boo_Twitter::getPublicTimeline ($ sinceId = 0)
Definition at line 199 of file Twitter.php.
References apiCall().
Boo_Twitter::getRateLimitStatus ()
Definition at line 425 of file Twitter.php.
References apiCall().
Boo_Twitter::getReplies ($ page = 0)
Definition at line 251 of file Twitter.php.
References apiCall().
Boo_Twitter::getSentMessages ($ since = null, $ sinceId = 0, $ page = 1)
Definition at line 339 of file Twitter.php.
References apiCall().
Boo_Twitter::getSession ()
Definition at line 126 of file Twitter.php.
References hasSession().
static Boo_Twitter::getSupportedDevices () [static]
Definition at line 142 of file Twitter.php.
static Boo_Twitter::getSupportedFormats () [static]
Definition at line 135 of file Twitter.php.
Boo_Twitter::getUsername ()
Definition at line 186 of file Twitter.php.
Boo_Twitter::getUserTimeline ($ id = null, $ count = 20, $ since = null)
Definition at line 222 of file Twitter.php.
References apiCall().
Boo_Twitter::hasSession ()
Definition at line 122 of file Twitter.php.
Referenced by getSession(), and openSession().
static Boo_Twitter::isSupportedDevice ($ device) [static]
Definition at line 144 of file Twitter.php.
static Boo_Twitter::isSupportedFormat ($ format) [static]
Definition at line 137 of file Twitter.php.
References $format.
Boo_Twitter::lastApiCall ()
Definition at line 539 of file Twitter.php.
Referenced by apiCall().
Boo_Twitter::lastStatusCode ()
Definition at line 537 of file Twitter.php.
Boo_Twitter::leave ($ id)
Definition at line 468 of file Twitter.php.
References apiCall().
Boo_Twitter::newMessage ($ user, $ text)
Definition at line 354 of file Twitter.php.
References $text, $user, and apiCall().
Boo_Twitter::openSession ()
Definition at line 108 of file Twitter.php.
References hasSession().
Boo_Twitter::saveSession ()
Definition at line 103 of file Twitter.php.
Boo_Twitter::setApplicationSource ($ source)
Definition at line 152 of file Twitter.php.
References Boo_Validator::isString().
Boo_Twitter::setFormat ($ format)
Definition at line 163 of file Twitter.php.
References $format.
Boo_Twitter::setPassword ($ password)
Definition at line 188 of file Twitter.php.
References $password, Boo_Validator::isString(), MAX_PASSWORD_LENGTH, and MIN_PASSWORD_LENGTH.
Referenced by __construct().
Boo_Twitter::setUsername ($ username)
Definition at line 175 of file Twitter.php.
References $username, Boo_Validator::isAlphaNumPlus(), MAX_USERNAME_LENGTH, and MIN_USERNAME_LENGTH.
Referenced by __construct().
Boo_Twitter::showStatus ($ id)
Definition at line 240 of file Twitter.php.
References apiCall().
Boo_Twitter::showUser ($ id)
Definition at line 301 of file Twitter.php.
References apiCall().
Boo_Twitter::showUserByEmail ($ email)
Definition at line 306 of file Twitter.php.
References apiCall(), and Boo_Validator::isEmail().
Boo_Twitter::showUserByScreenName ($ screenName)
Definition at line 318 of file Twitter.php.
References apiCall().
Boo_Twitter::test ()
Definition at line 483 of file Twitter.php.
References apiCall().
Boo_Twitter::updateDeliveryDevice ($ device)
Definition at line 414 of file Twitter.php.
References apiCall().
Boo_Twitter::updateLocation ($ location)
Updates location. .
Returns:
mixed Twitter data.
Parameters:
string $location Your location.
Definition at line 408 of file Twitter.php.
References apiCall().
Boo_Twitter::updateStatus ($ status)
Definition at line 245 of file Twitter.php.
References apiCall().
Boo_Twitter::verifyCredentials ()
Definition at line 383 of file Twitter.php.
References apiCall().
Member Data Documentation
Boo_Twitter::$applicationSource = 'boo' [protected]
Contains the application calling the API.
Attention:
Must be registered first.
See also:
http://twitter.com/help/request_source
Definition at line 50 of file Twitter.php.
Boo_Twitter::$format = 'xml' [protected]
Return format.
See also:
Boo_Twitter::getSupportedFormat();
Definition at line 56 of file Twitter.php.
Referenced by isSupportedFormat(), and setFormat().
Boo_Twitter::$httpStatus = false [protected]
Contains the last HTTP status code returned.
Definition at line 37 of file Twitter.php.
Boo_Twitter::$lastApiCall = false [protected]
Contains the last API call.
Definition at line 42 of file Twitter.php.
Boo_Twitter::$password = false [protected]
Twitter password.
Definition at line 32 of file Twitter.php.
Referenced by __construct(), and setPassword().
Boo_Twitter::$supportedDevices = array('sms', 'im', 'none') [static, protected]
Definition at line 64 of file Twitter.php.
Boo_Twitter::$supportedFormats = array('xml', 'json', 'rss', 'atom') [static, protected]
Array of supported formats.
Definition at line 61 of file Twitter.php.
Boo_Twitter::$username = false [protected]
Twitter username.
Definition at line 27 of file Twitter.php.
Referenced by __construct(), and setUsername().
const Boo_Twitter::MAX_PASSWORD_LENGTH = 30
Maximum length of password.
Definition at line 80 of file Twitter.php.
Referenced by setPassword().
const Boo_Twitter::MAX_USERNAME_LENGTH = 15
Maximum length of username.
Definition at line 70 of file Twitter.php.
Referenced by setUsername().
const Boo_Twitter::MIN_PASSWORD_LENGTH = 6
Minimum length of password.
Definition at line 85 of file Twitter.php.
Referenced by setPassword().
const Boo_Twitter::MIN_USERNAME_LENGTH = 1
Minimum length of username.
Definition at line 75 of file Twitter.php.
Referenced by setUsername().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Twitter.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.