API Documentation for Boo-2.0.x: Boo_Html_Input Class Reference
Boo_Html_Input Class Reference
HTML input class.
Public Member Functions
__construct ($type= 'text')
The constructor.
htmlOpen ()
Extends parent method.
isSticky ()
Returns inputs stickiness.
setSticky ($opt)
Sets the inputs stickiness.
Detailed Description
HTML input class.
This class is used to generate inputs.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.6.1
Todo:
Cleanup file to 2.0 spces.
Definition at line 29 of file Input.php.
Constructor & Destructor Documentation
Boo_Html_Input::__construct ($ type = 'text')
The constructor.
string $type (optional) Type type of input.
Returns:
void.
Reimplemented from Boo_Html_FormControl.
Definition at line 35 of file Input.php.
References Boo_Html::setAttr().
Member Function Documentation
Boo_Html_Input::htmlOpen ()
Extends parent method.
See also:
Boo_Html::htmlOpen().
Returns:
string Opening HTML tag for the element.
Reimplemented from Boo_Html.
Reimplemented in Boo_Html_Input_File.
Definition at line 61 of file Input.php.
References _post(), Boo_Html::getAttr(), isSticky(), and Boo_Html::setAttr().
Boo_Html_Input::isSticky ()
Returns inputs stickiness.
Returns:
bool TRUE if input is sticky, FALSE otherwise.
Reimplemented from Boo_Html_FormControl.
Definition at line 54 of file Input.php.
Referenced by htmlOpen().
Boo_Html_Input::setSticky ($ opt)
Sets the inputs stickiness.
Parameters:
bool $opt If input is sticky or not.
Returns:
bool TRUE.
Reimplemented from Boo_Html_FormControl.
Definition at line 45 of file Input.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html/Input.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.