API Documentation for Boo-2.0.x: Boo_Db Class Reference
Boo_Db Class Reference
Database class.
Public Member Functions
__construct ($tableName=false, $primaryKey=false)
Default constructor.
getPrimaryKey ()
Gets the primary key.
getTableName ()
Gets the table name.
setPrimaryKey ($key)
Sets the primary key for the table.
setTableName ($tableName)
Sets the table name.
Static Public Member Functions
static connect ()
Connects to a database.
Protected Attributes
$primaryKey = 'boo_id'
The name of the tables primary key.
$tableName = 'boo_default'
The table name.
Detailed Description
Database class.
This class is used to connect to a database.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition at line 16 of file Db.php.
Constructor & Destructor Documentation
Boo_Db::__construct ($ tableName = false, $ primaryKey = false)
Default constructor.
Handles shorthand object initialization.
Parameters:
string $tableName[optional] The table name.
string $primaryKey[optional] The primary key.
Returns:
void.
Reimplemented in Boo_Io, Boo_Lookup, Boo_Qrbg, and Boo_Twitter.
Definition at line 37 of file Db.php.
References $primaryKey, $tableName, setPrimaryKey(), and setTableName().
Member Function Documentation
static Boo_Db::connect () [static]
Connects to a database.
This function is used to connect to a database, in this case MySQL 5. You will need to set BOO_DB_CONNECTION_STRING, BOO_DB_USERNAME, and BOO_DB_PASSWORD in your config file.
Returns:
PDO object.
 $dbh = Boo_Db::connect();
Definition at line 60 of file Db.php.
References $e.
Referenced by Boo_Qrbg::clearCache(), Boo_Io::count(), Boo_Io::delete(), Boo_Qrbg::exec(), Boo_Io::exists(), Boo_Group::getGroupIdByName(), Boo_Group::getGroups(), Boo_User::login(), Boo_Lookup::open(), Boo_Io::open(), Boo_Qrbg::removeCacheById(), Boo_Io::save(), and Boo_Qrbg::saveCache().
Boo_Db::getPrimaryKey ()
Gets the primary key.
Returns:
string The primary key.
Definition at line 124 of file Db.php.
Boo_Db::getTableName ()
Gets the table name.
Returns:
string The table name.
Since:
2.0.0
Definition at line 96 of file Db.php.
Boo_Db::setPrimaryKey ($ key)
Sets the primary key for the table.
Parameters:
string $key The primary key.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 104 of file Db.php.
References Boo_Validator::isSqlSafe().
Referenced by Boo_Lookup::__construct(), and __construct().
Boo_Db::setTableName ($ tableName)
Sets the table name.
Parameters:
string $tableName The table name.
Returns:
bool Returns TRUE on successs, FALSE otherwise.
Todo:
Check if table name exists in database and cache the result.
Definition at line 79 of file Db.php.
References $tableName, and Boo_Validator::isSqlSafe().
Referenced by Boo_Lookup::__construct(), and __construct().
Member Data Documentation
Boo_Db::$primaryKey = 'boo_id' [protected]
The name of the tables primary key.
Definition at line 26 of file Db.php.
Referenced by Boo_Lookup::__construct(), __construct(), Boo_Io::__construct(), Boo_User::exists(), Boo_Io::exists(), and Boo_Lookup::getFieldByPrimaryKey().
Boo_Db::$tableName = 'boo_default' [protected]
The table name.
Definition at line 21 of file Db.php.
Referenced by Boo_Lookup::__construct(), __construct(), Boo_Io::__construct(), Boo_User::exists(), Boo_Io::exists(), and setTableName().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Db.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.