API Documentation for Boo-2.0.x: Boo_Csv Class Reference
Boo_Csv Class Reference
Comma separated values class.
Public Member Functions
__construct ()
Default constructor.
exportFields ($fields)
exportFieldsKey ($fields)
exportRows ($rows, $fieldNames=true)
getCsv ()
getRow ($index)
getRows ()
htmlTable ($rows, $attrs=array())
isEmpty ()
load ($csv)
open ($filename)
Open a file.
Static Public Member Functions
static fixLastComma ($string)
Strips last comma from a string.
static getFields ($text)
Protected Attributes
$csv = false
$rows = array()
Detailed Description
Comma separated values class.
A generic class for dealing with comma separated value data.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.8.0
Todo:
Debug class.
Definition at line 17 of file Csv.php.
Constructor & Destructor Documentation
Boo_Csv::__construct ()
Default constructor.
Returns:
void.
Definition at line 26 of file Csv.php.
Member Function Documentation
Boo_Csv::exportFields ($ fields)
Definition at line 162 of file Csv.php.
References $csv, and fixLastComma().
Referenced by exportRows().
Boo_Csv::exportFieldsKey ($ fields)
Definition at line 174 of file Csv.php.
References $csv, and fixLastComma().
Referenced by exportRows().
Boo_Csv::exportRows ($ rows, $ fieldNames = true)
Definition at line 115 of file Csv.php.
References $csv, $rows, exportFields(), and exportFieldsKey().
static Boo_Csv::fixLastComma ($ string) [static]
Strips last comma from a string.
Parameters:
string $string The string to fix.
Returns:
string The string without the last comma if present.
Definition at line 201 of file Csv.php.
Referenced by exportFields(), exportFieldsKey(), and Boo_Io::save().
Boo_Csv::getCsv ()
Definition at line 92 of file Csv.php.
static Boo_Csv::getFields ($ text) [static]
Definition at line 28 of file Csv.php.
References $text, array_trim(), and Boo_Validator::isNull().
Referenced by load().
Boo_Csv::getRow ($ index)
Definition at line 82 of file Csv.php.
Boo_Csv::getRows ()
Definition at line 80 of file Csv.php.
Boo_Csv::htmlTable ($ rows, $ attrs = array())
Definition at line 134 of file Csv.php.
References $rows.
Boo_Csv::isEmpty ()
Definition at line 90 of file Csv.php.
Boo_Csv::load ($ csv)
Definition at line 94 of file Csv.php.
References $csv, $rows, and getFields().
Boo_Csv::open ($ filename)
Open a file.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Parameters:
string $filename The filename.
Todo:
Implement function.
Definition at line 191 of file Csv.php.
Member Data Documentation
Boo_Csv::$csv = false [protected]
Definition at line 19 of file Csv.php.
Referenced by exportFields(), exportFieldsKey(), exportRows(), and load().
Boo_Csv::$rows = array() [protected]
Definition at line 20 of file Csv.php.
Referenced by exportRows(), htmlTable(), and load().
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Csv.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.