API Documentation for Boo-2.0.x: Boo_Html_Select Class Reference
Boo_Html_Select Class Reference
HTML drop-down list class.
Public Member Functions
__construct ()
Default constructor.
addDefault ($key)
Adds key to list of default items.
addSelected ($key)
Adds key to list of selected items.
clearData ()
Clears the lists data.
getData ()
Gets the lists data.
getDefault ()
Gets the default key.
getDefaultIndex ()
Gets the default index.
getPostedIndex ()
Gets index of posted value.
getSelected ()
Gets the selected key.
getSelectedIndex ()
Gets the selected index.
getTitle ()
Gets the title.
getTitleName ()
getTitleValue ()
Gets the titles value.
hasData ()
Determins if the list has data.
hasTitle ()
Determins if a title is set.
html (array $attrs=array())
Returns the HTML for the list.
setData (array $data)
Sets the lists data.
setDefault ($key)
Sets the default key.
setDefaultIndex ($index)
Sets the default index. Zero based.
setSelected ($key)
Sets the selected key.
setSelectedIndex ($index)
Sets the selected index.
setTitle ($name, $value=null)
Sets the title.
Static Public Member Functions
static htmlCountriesSelect ()
HTML select of all countries.
static htmlStatesSelect ()
HTML select of all US states.
Protected Attributes
$data = array()
The select elements data.
$default = ''
The default key.
$selected = ''
The selected key.
$title = array('name' => '', 'value' => '')
The title of the select element.
Detailed Description
HTML drop-down list class.
This class is used to generate HTML drop-down lists.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.7.0
Todo:
Add support for selecting multiple items.
Fix issues with htmlentities.
Definition at line 19 of file Select.php.
Constructor & Destructor Documentation
Boo_Html_Select::__construct ()
Default constructor.
Returns:
void.
Definition at line 52 of file Select.php.
Member Function Documentation
Boo_Html_Select::addDefault ($ key)
Adds key to list of default items.
This feature is not yet implemented! Added for future API compatibility.
Parameters:
string $key The default key.
Returns:
bool Returns TRUE on success, FALSE on failure.
Todo:
Finish this function when updating class to support multiple selects.
Definition at line 179 of file Select.php.
References setDefault().
Boo_Html_Select::addSelected ($ key)
Adds key to list of selected items.
This feature is not yet implemented! Added for future API compatibility.
Parameters:
string $key The selected key.
Returns:
bool Returns TRUE on success, FALSE on failure.
Todo:
Finish this function when updating class to support multiple selects.
Definition at line 223 of file Select.php.
References setSelected().
Boo_Html_Select::clearData ()
Clears the lists data.
Returns:
bool Function always returns TRUE.
Definition at line 77 of file Select.php.
Boo_Html_Select::getData ()
Gets the lists data.
Returns:
array The data.
Definition at line 87 of file Select.php.
Boo_Html_Select::getDefault ()
Gets the default key.
Returns:
string The default key.
Definition at line 188 of file Select.php.
Boo_Html_Select::getDefaultIndex ()
Gets the default index.
* Zero based.
Warning:
This function relies on the internal order of the data array. This can be dangerous.
Returns:
mixed Returns default index on success, FALSE on failure.
Definition at line 277 of file Select.php.
References Boo_Html::$count, and Boo_Validator::isNull().
Boo_Html_Select::getPostedIndex ()
Gets index of posted value.
Warning:
This function relies on the internal order of the data array. This can be dangerous.
Returns:
mixed Returns posted index on success, FALSE otherwise.
Definition at line 362 of file Select.php.
References Boo_Html::$count, and Boo_Html_FormControl::getPostedValue().
Boo_Html_Select::getSelected ()
Gets the selected key.
Returns:
string The selected key.
Definition at line 232 of file Select.php.
Boo_Html_Select::getSelectedIndex ()
Gets the selected index.
Zero based.
Warning:
This function relies on the internal order of the data array. This can be dangerous.
Returns:
mixed Returns selected index on success, FALSE on failure.
Definition at line 338 of file Select.php.
References Boo_Html::$count, and Boo_Validator::isNull().
Boo_Html_Select::getTitle ()
Gets the title.
API compatibility.
Returns:
string The title.
Definition at line 130 of file Select.php.
References getTitleName().
Boo_Html_Select::getTitleName ()
Gets the titles name (as seen by the user).
Returns:
string The titles name.
Definition at line 137 of file Select.php.
Referenced by getTitle().
Boo_Html_Select::getTitleValue ()
Gets the titles value.
Returns:
string The titles value.
Definition at line 144 of file Select.php.
Boo_Html_Select::hasData ()
Determins if the list has data.
Returns:
bool Returns TRUE if data is set, FALSE otherwise.
Definition at line 480 of file Select.php.
Referenced by setDefault(), setDefaultIndex(), setSelected(), and setSelectedIndex().
Boo_Html_Select::hasTitle ()
Determins if a title is set.
Returns:
bool Returns TRUE if title is set, FALSE otherwise.
Definition at line 115 of file Select.php.
References Boo_Validator::isNull().
Referenced by html().
Boo_Html_Select::html (array $ attrs = array())
Returns the HTML for the list.
Parameters:
array $attrs [optional] Array of attributes.
Returns:
string The HTML for list the list.
Reimplemented from Boo_Html.
Definition at line 387 of file Select.php.
References $selected, Boo_Html::applyAttrs(), Boo_Html::getAttr(), hasTitle(), Boo_Html::htmlClose(), Boo_Html::htmlOpen(), Boo_Validator::isNull(), and Boo_Html_FormControl::isSticky().
static Boo_Html_Select::htmlCountriesSelect () [static]
HTML select of all countries.
Returns:
Boo_Html_Select The HTML select of all countries.
Definition at line 503 of file Select.php.
References Boo_Validator::getCountries().
static Boo_Html_Select::htmlStatesSelect () [static]
HTML select of all US states.
Returns:
Boo_Html_Select The HTML select of all US states.
Definition at line 488 of file Select.php.
References Boo_Validator::getStates().
Boo_Html_Select::setData (array $ data)
Sets the lists data.
Parameters:
array $data The data.
Returns:
bool Returns TRUE on sccess, FALSE otherwise.
Definition at line 62 of file Select.php.
Boo_Html_Select::setDefault ($ key)
Sets the default key.
Parameters:
string $key The default key.
Returns:
bool Returns TRUE on success, FALSE on error.
Definition at line 152 of file Select.php.
References hasData().
Referenced by addDefault(), and setDefaultIndex().
Boo_Html_Select::setDefaultIndex ($ index)
Sets the default index. Zero based.
Warning:
This function relies on the internal order of the data array. This can be dangerous.
Parameters:
int $index The default index.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 243 of file Select.php.
References Boo_Html::$count, hasData(), and setDefault().
Boo_Html_Select::setSelected ($ key)
Sets the selected key.
Parameters:
string $key The selected key.
Returns:
bool Returns TRUE on success, FALSE on error.
Definition at line 196 of file Select.php.
References hasData().
Referenced by addSelected(), and setSelectedIndex().
Boo_Html_Select::setSelectedIndex ($ index)
Sets the selected index.
Zero based.
Warning:
This function relies on the internal order of the data array. This can be dangerous.
Parameters:
int $index The selected index.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 304 of file Select.php.
References Boo_Html::$count, hasData(), and setSelected().
Boo_Html_Select::setTitle ($ name, $ value = null)
Sets the title.
Parameters:
string $name The name of the title (displayed to user).
string $value (optional) The value for the title.
Returns:
bool Returns TRUE on success, FALSE otherwise.
Definition at line 96 of file Select.php.
References Boo_Validator::isNull().
Member Data Documentation
Boo_Html_Select::$data = array() [protected]
The select elements data.
Implemented as an array where the key is the option value and the value is the text displayed.
Definition at line 25 of file Select.php.
Boo_Html_Select::$default = '' [protected]
The default key.
Overided by posted values or selected key.
Definition at line 39 of file Select.php.
Boo_Html_Select::$selected = '' [protected]
The selected key.
Overrides posted value and default key.
Definition at line 46 of file Select.php.
Referenced by html().
Boo_Html_Select::$title = array('name' => '', 'value' => '') [protected]
The title of the select element.
Will be displayed as the first item in the select list if set and will contain a value of an empty string by default.
Definition at line 32 of file Select.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html/Select.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.