API Documentation for Boo-2.0.x: Boo_Html Class Reference
Boo_Html Class Reference
HTML class.
Public Member Functions
__construct ($element= 'div')
Default constructor.
__toString ()
Converts object to string.
addAttrs (array $attrs)
Adds attributes.
addClass ($class)
Adds class(es) to element.
addClasses (array $classes)
Add classes to element.
appendContent ($content, $cleanup=true)
Appends content to the elements existing content.
applyAttrs (array $attrs)
Convenience funciton for applying attributes.
clearAll ()
Clears everything but the element.
clearAttrs ()
Clears all attributes.
clearClasses ()
Clears all classes.
clearContent ()
Clears content.
getAttr ($attr)
Returns the attributes value.
getAttrs ()
Returns an array of attributes.
getContent ()
Returns content.
getElement ()
Returns the element name.
hasAttr ($attr)
Determins if element has an attribute.
hasClass ($class)
Determins if element has a given class.
html (array $attrs=array())
Returns HTML.
htmlClose ()
Returns closing HTML tag.
htmlInner ()
Returns inner HTML.
htmlOpen ()
Returns opening HTML tag.
isEmpty ()
Determins if content is empty.
isTagless ()
Determins if element has a tag.
isValid ()
Determins if the object is valid.
prependContent ($content, $cleanup=true)
Prepend content to the elements existing content.
removeAttr ($attr)
Removes attribute.
removeAttrs (array $attrs)
Removes array of attributes.
removeClass ($class)
Removes class(es) from element.
removeClasses (array $classes)
Removes classes from element.
setAttr ($attr, $value)
Sets the attribute.
setAttrs (array $attrs)
Sets the attributes.
setClass ($class)
Sets the elements class.
setContent ($content, $cleanup=true)
Sets the elements content.
setElement ($element, $force=false)
Sets the tag name.
toggleClass ($class)
Toggles class(es) for element.
toggleClasse (array $classes)
Toggles classes for element.
Static Public Member Functions
static getClearfixElements ()
Gets an array of all clearfix elements.
static getStandardElements ()
Gets an array of all standard elements.
static getSupportedElements ()
Gets an array of all supported elements.
static isClearfixElement ($element)
Determines if an element should have the clearfix class.
static isStandardElement ($element)
Determins if the element is a standard element.
static isSupportedElement ($element)
Determins if an element is valid.
Protected Attributes
$attributes = array()
HTML attributes.
$classes = array()
HTML classes.
$content = array()
HTML element content.
$element = null
HTML element name.
Static Protected Attributes
static $clearfixElements = array('div', 'form', 'fieldset', 'ol', 'ul', 'li', 'table')
List of HTML elements that require the clearfix class.
static $count = 0
Static count of elements.
static $standardElements
List of HTML elements that support the common attributes.
static $supportedElements
List of all supported HTML elements.
Detailed Description
HTML class.
This class is used to generate HTML elements.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
1.8.1
Definition at line 101 of file Html.php.
Constructor & Destructor Documentation
Boo_Html::__construct ($ element = 'div')
Default constructor.
Parameters:
string $element[optional] The HTML element to create.
Returns:
void.
Reimplemented in Boo_Html_Form_Xml, Boo_Html_FormControl, Boo_Html_Input, and Boo_Html_List.
Definition at line 175 of file Html.php.
References $element, addClass(), isClearfixElement(), isStandardElement(), and setElement().
Member Function Documentation
Boo_Html::__toString ()
Converts object to string.
See also:
Boo_Page::html()
Since:
2.0.0
Returns:
string Returns HTML for object.
Definition at line 861 of file Html.php.
References html().
Boo_Html::addAttrs (array $ attrs)
Adds attributes.
Parameters:
array $attrs The attributes to add.
Returns:
int Returns the number of attributes added, FALSE on failure.
Definition at line 299 of file Html.php.
References $count, and setAttr().
Referenced by applyAttrs().
Boo_Html::addClass ($ class)
Adds class(es) to element.
Parameters:
string $class The class(es) to add.
Returns:
mixded If class(es) are added then the number of additions is returned, FALSE otherwise.
Definition at line 507 of file Html.php.
References addClasses().
Referenced by Boo_Html_Input_Submit::__construct(), Boo_Html_Input_Reset::__construct(), __construct(), Boo_Html_Input_Button::__construct(), Boo_Dialog_MessageBox::__construct(), addClasses(), and toggleClass().
Boo_Html::addClasses (array $ classes)
Add classes to element.
Returns:
int Returns the number of classes added, FALSE on failure.
Parameters:
array $classes The classes to add.
Definition at line 540 of file Html.php.
References $count, and addClass().
Referenced by addClass(), and removeClass().
Boo_Html::appendContent ($ content, $ cleanup = true)
Appends content to the elements existing content.
Parameters:
string $content The content.
bool $cleanup[optional] Cleanup content.
Returns:
bool Function always returns TRUE.
Definition at line 711 of file Html.php.
References $content.
Referenced by Boo_Html_Form_Xml::handleFormChild(), Boo_Html_List::html(), and Boo_Html_Form_Xml::html().
Boo_Html::applyAttrs (array $ attrs)
Convenience funciton for applying attributes.
Will only apply attributes if array is not empty.
Returns:
int Returns the number of attributes applied, FALSE on failure.
Parameters:
array $attrs The attributes array.
Definition at line 330 of file Html.php.
References addAttrs().
Referenced by Boo_Html_Script::__construct(), Boo_Html_Link::__construct(), Boo_Html_Select::html(), and html().
Boo_Html::clearAll ()
Clears everything but the element.
Since:
2.0.0
Returns:
bool FUnction always returns TRUE.
Definition at line 679 of file Html.php.
References clearAttrs(), clearClasses(), and clearContent().
Boo_Html::clearAttrs ()
Clears all attributes.
Since:
2.0.0
Returns:
bool Function always returns TRUE.
Definition at line 444 of file Html.php.
Referenced by clearAll().
Boo_Html::clearClasses ()
Clears all classes.
Since:
2.0.0
Returns:
bool Function always returns TRUE.
Definition at line 668 of file Html.php.
Referenced by clearAll().
Boo_Html::clearContent ()
Clears content.
Returns:
bool Function always returns TRUE.
Definition at line 745 of file Html.php.
Referenced by clearAll(), Boo_Html_List::html(), and setContent().
Boo_Html::getAttr ($ attr)
Returns the attributes value.
Parameters:
string $attr The attributes name.
Returns:
string The attributes value if attribute is set, FALSE otherwise.
Definition at line 372 of file Html.php.
Referenced by Boo_Dialog_MessageBox::clearSession(), Boo_Html_FormControl::getPostedValue(), Boo_Html_Select::html(), Boo_Html_Form_Xml::html(), Boo_Html_Textarea::htmlOpen(), Boo_Html_Input::htmlOpen(), Boo_Html_Form_Xml::isPostback(), Boo_Html_Form_Xml::loadXmlForm(), Boo_Dialog_MessageBox::openSession(), and Boo_Dialog_MessageBox::saveSession().
Boo_Html::getAttrs ()
Returns an array of attributes.
Parameters:
string $attr The attributes name.
Returns:
array Returns the attributes.
Definition at line 320 of file Html.php.
static Boo_Html::getClearfixElements () [static]
Gets an array of all clearfix elements.
Since:
2.0.0
Returns:
array Array of all clearfix elements.
Definition at line 251 of file Html.php.
Boo_Html::getContent ()
Returns content.
Returns:
array Content of the element.
Definition at line 737 of file Html.php.
Boo_Html::getElement ()
Returns the element name.
Returns:
string The element name.
Definition at line 217 of file Html.php.
static Boo_Html::getStandardElements () [static]
Gets an array of all standard elements.
Since:
2.0.0
Returns:
array Array of all standard elements.
Definition at line 270 of file Html.php.
static Boo_Html::getSupportedElements () [static]
Gets an array of all supported elements.
Returns:
array Array of all supported elements.
Definition at line 233 of file Html.php.
Boo_Html::hasAttr ($ attr)
Determins if element has an attribute.
Parameters:
string $attr The attributes name.
Returns:
bool Returns TRUE if the attribute is set (even to null), FALSE otherwise.
Definition at line 387 of file Html.php.
Referenced by Boo_Html_FormControl::getPostedValue().
Boo_Html::hasClass ($ class)
Determins if element has a given class.
Parameters:
mixed $class The class name to compare.
Returns:
bool Returns TRUE if element has class, FALSE otherwise.
Definition at line 492 of file Html.php.
Referenced by toggleClass().
Boo_Html::html (array $ attrs = array())
Returns HTML.
Returns:
string HTML for the element.
Parameters:
array $attrs[optional] Array of attributes.
 <div id="myid" class="auther name">This is my first div.</div>
Reimplemented in Boo_Html_Empty, Boo_Html_Form_Xml, Boo_Html_List, and Boo_Html_Select.
Definition at line 774 of file Html.php.
References applyAttrs(), htmlClose(), htmlInner(), and htmlOpen().
Referenced by __toString().
Boo_Html::htmlClose ()
Returns closing HTML tag.
Returns:
string Closing HTML tag for the element.
 </div>
Reimplemented in Boo_Html_Empty.
Definition at line 815 of file Html.php.
References isTagless().
Referenced by Boo_Html_Select::html(), html(), and Boo_Dialog_MessageBox::html().
Boo_Html::htmlInner ()
Returns inner HTML.
Returns:
string The inner HTML from the element.
Definition at line 754 of file Html.php.
Referenced by html().
Boo_Html::htmlOpen ()
Returns opening HTML tag.
Returns:
string Opening HTML tag for the element.
 <div id="myid" class="auther name">
Reimplemented in Boo_Html_Empty, Boo_Html_Input_File, Boo_Html_Input, and Boo_Html_Textarea.
Definition at line 787 of file Html.php.
References isTagless().
Referenced by Boo_Html_Select::html(), html(), and Boo_Dialog_MessageBox::html().
static Boo_Html::isClearfixElement ($ element) [static]
Determines if an element should have the clearfix class.
Since:
2.0.0
Parameters:
string $element The element to test.
Returns:
bool Returns TRUE if element should have the clearfix class, FALSE otherwise.
Definition at line 241 of file Html.php.
References $element.
Referenced by __construct().
Boo_Html::isEmpty ()
Determins if content is empty.
Since:
2.0.0
Returns:
bool Returns TRUE if content is empty, FALSE otherwise.
Reimplemented in Boo_Html_List.
Definition at line 852 of file Html.php.
static Boo_Html::isStandardElement ($ element) [static]
Determins if the element is a standard element.
Since:
2.0.0
Parameters:
string $element The element to test.
Returns:
bool Retunrs TRUE if element is a standard element, FALSE otherwise.
Definition at line 260 of file Html.php.
References $element.
Referenced by __construct().
static Boo_Html::isSupportedElement ($ element) [static]
Determins if an element is valid.
Returns:
bool Returns TRUE if element is valid, FALSE otherwise.
Parameters:
string $element The element to test.
Definition at line 224 of file Html.php.
References $element.
Boo_Html::isTagless ()
Determins if element has a tag.
Returns:
bool Returns TRUE if element has a tag, FALSE otherwise (contains other tags, or is just test).
Definition at line 829 of file Html.php.
Referenced by htmlClose(), and htmlOpen().
Boo_Html::isValid ()
Determins if the object is valid.
This feature is not yet implemented! Added for future API compatibility.
Returns:
bool Returns TRUE if object is valid, FALSE otherwise.
Todo:
Finish function and decide what is required for validity.
Reimplemented in Boo_Html_Form_Xml.
Definition at line 842 of file Html.php.
Referenced by Boo_Html_Form_Xml::setErrors().
Boo_Html::prependContent ($ content, $ cleanup = true)
Prepend content to the elements existing content.
Parameters:
string $content The content.
bool $cleanup[optional] Cleanup content.
Returns:
bool Function always returns TRUE.
Definition at line 725 of file Html.php.
References $content.
Boo_Html::removeAttr ($ attr)
Removes attribute.
Parameters:
string $attr The attributes name.
Returns:
bool Returns TRUE if successfull, FALSE otherwise.
Definition at line 403 of file Html.php.
Referenced by removeAttrs().
Boo_Html::removeAttrs (array $ attrs)
Removes array of attributes.
Returns:
int Returns the number of attributes removed, FALSE on failure.
Parameters:
array $attrs The attributes to remove.
Definition at line 423 of file Html.php.
References $count, and removeAttr().
Boo_Html::removeClass ($ class)
Removes class(es) from element.
Parameters:
mixed $class The class(es) to remove.
Returns:
mixed If class(es) are found then the number removed is returned, FALSE otherwise.
Definition at line 561 of file Html.php.
References addClasses(), and removeClasses().
Referenced by removeClasses(), and toggleClass().
Boo_Html::removeClasses (array $ classes)
Removes classes from element.
Returns:
int Returns the number of classes removed, FALSE on failure.
Parameters:
array $classes The classes to be removed.
Definition at line 595 of file Html.php.
References $count, and removeClass().
Referenced by removeClass().
Boo_Html::setAttr ($ attr, $ value)
Sets the attribute.
Parameters:
string $attr The attributes name.
string $value The attributes value.
Returns:
bool Returns TRUE if successful, FALSE otherwise.
 $html->setAttr('id', 'myid');
Definition at line 350 of file Html.php.
References Boo_Validator::isNull(), and setClass().
Referenced by Boo_Html_Input_Text::__construct(), Boo_Html_Input_Submit::__construct(), Boo_Html_Input_Reset::__construct(), Boo_Html_Input_Radio::__construct(), Boo_Html_Input_Password::__construct(), Boo_Html_Input_Image::__construct(), Boo_Html_Input_Hidden::__construct(), Boo_Html_Input_File::__construct(), Boo_Html_Input_Checkbox::__construct(), Boo_Html_Input::__construct(), Boo_Html_Form::__construct(), Boo_Html_Input_Button::__construct(), addAttrs(), Boo_Dialog_MessageBox::html(), Boo_Html_Input::htmlOpen(), Boo_Html_Form_Xml::loadXmlForm(), Boo_Html_Form_Xml::open(), and setAttrs().
Boo_Html::setAttrs (array $ attrs)
Sets the attributes.
Parameters:
array $attrs The attributes .
Returns:
int Returns the number of attributes set, FALSE on failure.
Definition at line 277 of file Html.php.
References $count, and setAttr().
Boo_Html::setClass ($ class)
Sets the elements class.
Input may be a single name, space delimited string of names, or an array of names.
Parameters:
mixed $class The class(es) to set.
Returns:
bool Returns TRUE if class was set, FALSE otherwise.
 $html->setClass('author name');
Definition at line 461 of file Html.php.
References array_trim().
Referenced by setAttr().
Boo_Html::setContent ($ content, $ cleanup = true)
Sets the elements content.
Parameters:
string $content The content.
bool $cleanup[optional] Cleanup content.
Returns:
bool Function always returns TRUE.
 $html->setContent("This is my first div.");
Definition at line 696 of file Html.php.
References $content, and clearContent().
Referenced by Boo_Html_Textarea::htmlOpen().
Boo_Html::setElement ($ element, $ force = false)
Sets the tag name.
Parameters:
string $element The tag name. Set to FALSE for tagless.
bool $force Force non standard element to be used. Usefull for writing non standard HTML (not that you should do that).
Returns:
bool Returns TRUE on success, FALSE otherwise.
 $html->setElement('div');
Definition at line 201 of file Html.php.
References $element.
Referenced by __construct(), and Boo_Html_Empty::__construct().
Boo_Html::toggleClass ($ class)
Toggles class(es) for element.
Parameters:
string $class The class(es) name.
Returns:
int Returns the number of classes toggled, FALSE otherwise.
Definition at line 616 of file Html.php.
References addClass(), hasClass(), and removeClass().
Referenced by toggleClasse().
Boo_Html::toggleClasse (array $ classes)
Toggles classes for element.
Returns:
int Returns number of classes toggled, FALSE on failure
Parameters:
array $classes Array of classes to toggle.
Definition at line 647 of file Html.php.
References $count, and toggleClass().
Member Data Documentation
Boo_Html::$attributes = array() [protected]
HTML attributes.
Definition at line 110 of file Html.php.
Referenced by Boo_Html_Form_Xml::handleFormChild().
Boo_Html::$classes = array() [protected]
HTML classes.
Definition at line 105 of file Html.php.
Boo_Html::$clearfixElements = array('div', 'form', 'fieldset', 'ol', 'ul', 'li', 'table') [static, protected]
List of HTML elements that require the clearfix class.
Todo:
Finish list.
Definition at line 163 of file Html.php.
Boo_Html::$content = array() [protected]
HTML element content.
Definition at line 120 of file Html.php.
Referenced by appendContent(), prependContent(), and setContent().
Boo_Html::$count = 0 [static, protected]
Static count of elements.
Definition at line 168 of file Html.php.
Referenced by addAttrs(), addClasses(), Boo_Html_List::getCountByClass(), Boo_Html_Select::getDefaultIndex(), Boo_Html_Select::getPostedIndex(), Boo_Html_Select::getSelectedIndex(), Boo_Html_List::html(), Boo_Html_Form_Xml::loadXmlForm(), Boo_Html_List::merge(), removeAttrs(), removeClasses(), setAttrs(), Boo_Html_Select::setDefaultIndex(), Boo_Html_Select::setSelectedIndex(), and toggleClasse().
Boo_Html::$element = null [protected]
HTML element name.
Definition at line 115 of file Html.php.
Referenced by Boo_Html_List::__construct(), __construct(), Boo_Html_FormControl::__construct(), isClearfixElement(), isStandardElement(), isSupportedElement(), and setElement().
Boo_Html::$standardElements [static, protected]
Initial value:
 array(
        'a', 'abbr', 'acronym', 'address', 'area', 'b', 'big', 'blockquote',
        'body', 'button', 'caption', 'cite', 'code', 'col', 'colgroup', 'dd', 'del',
        'dfn', 'div', 'dl', 'dt', 'em', 'fieldset', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'hr', 'i', 'img', 'input', 'ins', 'kbd', 'label', 'legend', 'li',
        'link', 'noscript', 'object', 'ol', 'optgroup', 'option', 'p',
        'pre', 'q', 'samp', 'select', 'small', 'span', 'strong', 'sub', 'sup',
        'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'tr', 'tt', 'ul', 'var')
List of HTML elements that support the common attributes.
Common attributes are:
class
id
style
title
dir
xml:lang
xml:space
See also:
http://www.w3.org/TR/xhtml-modularization/abstract_modules.html#s_common_collection
Since:
2.0.0
Definition at line 149 of file Html.php.
Boo_Html::$supportedElements [static, protected]
Initial value:
 array(
        'a', 'abbr', 'acronym', 'address', 'area', 'b', 'base', 'bdo', 'big', 'blockquote',
        'body', 'br', 'button', 'caption', 'cite', 'code', 'col', 'colgroup', 'dd', 'del',
        'dfn', 'div', 'dl', 'dt', 'em', 'fieldset', 'form', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
        'head', 'hr', 'html', 'i', 'img', 'input', 'ins', 'kbd', 'label', 'legend', 'li',
        'link', 'map', 'meta', 'noscript', 'object', 'ol', 'optgroup', 'option', 'p', 'param',
        'pre', 'q', 'samp', 'script', 'select', 'small', 'span', 'strong', 'style', 'sub', 'sup',
        'table', 'tbody', 'td', 'textarea', 'tfoot', 'th', 'thead', 'title', 'tr', 'tt', 'ul', 'var')
List of all supported HTML elements.
Definition at line 125 of file Html.php.
The documentation for this class was generated from the following file:
/var/www/Boo-2.0.0/classes/Html.php
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.