API Documentation for Boo-2.0.x: /var/www/Boo-2.0.0/functions/core.php File Reference
core.php File Reference
Core functions file.
Functions
add_flag ($flags, $flagAdd)
Adds a set of flags to eachother.
answer_word ($opt)
Returns the answer word.
array_add (array $a1, array $a2)
Adds the values of one array to the values of another array with the same key.
array_change_value_case (array $input, $case=CASE_LOWER)
Returns an array with all values lowercased or uppercased.
array_trim (&$array, $charlist=false)
Trims whitespace from each value in an array.
array_trim_callback (&$value, $key, $charlist)
Callback function used with array_trim().
bool_word ($opt)
Returns word associated with boolean value.
br ($count=2, $return=false)
Returns a HTML break.
clean_filename ($filename)
Cleans file name of dangerous characters.
count_files ($path, &$fileList=false)
Counts files recursively.
file_get_contents_css ($filename)
Returns contents of css file.
fix_magic_quotes ()
Fixes magic quotes if you them on (which you shouldn't).
get_include_contents ($filename)
Gets the include contents of a file.
get_uptime ()
Returns uptime on a unix system.
has_flag ($flags, $flagCheck)
Determins if a flag is present.
header_css ()
Sets the headers correctly for PHP to output CSS.
header_download ($filename, $contentLength=-1, $contentType= 'application/force-download')
Sets headers correctly for downloading a file.
header_json ($contentLength=-1)
Sets the headers correctly for JSON responses.
header_no_cache ($contentLength=-1, $contentType= 'text/html', $charset= 'utf-8')
Sets the headers correctly for no cache pages.
is_even ($number)
Checks if a number is even.
is_odd ($number)
Checks if a number is odd.
ltrim_word ($str, $word, $caseSensitive=true)
Returns a string with words removed from the begining.
move_element (array $array, $index, $direction)
Moves an element within an array.
pre_r ($expression, $return=false)
Returns output of print_r enclosed in .
quote ($string)
Returns the string surrounded by double quotes.
remove_flag ($flags, $flagRemove)
Removes a flag from a set of flags.
rmdirr ($dirname)
Delete a file, or a folder and its contents.
if(!function_exists('stripslashes_deep')) rtrim_word ($str, $word, $caseSensitive=true)
Un-quotes a quoted string recursivly.
safe_scripts ()
Makes sure running scripts is allowed.
safe_tests ()
Makes sure running tests is allowed.
strtodb ($string)
Formats string for insertion into database.
truncate ($text, $length, $etc= '...')
Truncates a string to a given length.
word_bool ($word)
Returns TRUE if the word equals "true".
Detailed Description
Core functions file.
This file provides core functions used by Boo.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition in file core.php.
Function Documentation
add_flag ($ flags, $ flagAdd)
Adds a set of flags to eachother.
Returns:
int Returns result of the flag addition.
Parameters:
int $flags The original flag set.
int $flagAdd The flag set to add.
Definition at line 407 of file core.php.
answer_word ($ opt)
Returns the answer word.
Parameters:
bool $opt The value to test.
Returns:
string Returns "yes" if TRUE, "no" if FALSE.
Definition at line 44 of file core.php.
array_add (array $ a1, array $ a2)
Adds the values of one array to the values of another array with the same key.
Parameters:
array $a1 The first array.
array $a2 The second array.
Returns:
array Returns the combined array.
Definition at line 533 of file core.php.
Referenced by count_files().
array_change_value_case (array $ input, $ case = CASE_LOWER)
Returns an array with all values lowercased or uppercased.
Since:
2.0.0
Returns:
array Returns an array with all values lowercased or uppercased.
Parameters:
object $input The array to work on
int $case[optional] Either CASE_UPPER or CASE_LOWER (default).
Definition at line 468 of file core.php.
Referenced by Boo_Validator::isTrueFalseWord(), and Boo_Validator::isYesNoWord().
array_trim (&$ array, $ charlist = false)
Trims whitespace from each value in an array.
Returns:
void.
Parameters:
array $array A reference to the input array.
string $charlist List of all characters that you want to be stripped.
Definition at line 443 of file core.php.
Referenced by _post(), Boo_Csv::getFields(), Boo_LoremIpsum::loadFiles(), Boo_Html::setClass(), and Boo_Log::write().
array_trim_callback (&$ value, $ key, $ charlist)
Callback function used with array_trim().
Returns:
void.
Parameters:
string $value A reference to the value to trim.
mixed $key The array key.
string $charlist List of all characters that you want to be stripped.
Definition at line 452 of file core.php.
bool_word ($ opt)
Returns word associated with boolean value.
Parameters:
bool $opt The value to test.
Returns:
string Returns "true" if TRUE, "false" if FALSE.
Definition at line 35 of file core.php.
br ($ count = 2, $ return = false)
Returns a HTML break.
This function is usefull for quickly outputing breaks for testing.
Parameters:
int $count[optional] The number of breaks to return.
bool $return[optional] Set to TRUE to return output, FALSE to print.
Returns:
string HTML breaks. Will echo if $return is set to FALSE.
Definition at line 382 of file core.php.
clean_filename ($ filename)
Cleans file name of dangerous characters.
Parameters:
string The file name (not including directory).
Returns:
string The safe file name.
Definition at line 337 of file core.php.
count_files ($ path, &$ fileList = false)
Counts files recursively.
See also:
Boo_Helper::getFileExtension()
Parameters:
string $path The path.
mixed[optional] $fileList The file list.
Returns:
array Returns an array of files where the key is the file extension and the value is the count, or FALSE on error.
Definition at line 490 of file core.php.
References array_add(), and Boo_Helper::getFileExtension().
file_get_contents_css ($ filename)
Returns contents of css file.
This function will remove the line if it exists.
Parameters:
string $filename Filename to the css file.
Returns:
string The contents of the file.
Definition at line 104 of file core.php.
fix_magic_quotes ()
Fixes magic quotes if you them on (which you shouldn't).
Returns:
void.
Definition at line 624 of file core.php.
get_include_contents ($ filename)
Gets the include contents of a file.
Returns:
string The contents.
Parameters:
string $filename The filename.
Definition at line 637 of file core.php.
get_uptime ()
Returns uptime on a unix system.
The output format is D HH:MM:SS or HH:MM:SS if day is 0.
Returns:
string The uptime.
Definition at line 242 of file core.php.
has_flag ($ flags, $ flagCheck)
Determins if a flag is present.
Returns:
bool Returns TRUE if flag is present, FALSE otherwise.
Parameters:
int $flags The flags to be tested.
int $flagCheck The flag to check for.
Definition at line 397 of file core.php.
header_css ()
Sets the headers correctly for PHP to output CSS.
Returns:
void.
Definition at line 123 of file core.php.
header_download ($ filename, $ contentLength = -1, $ contentType = 'application/force-download')
Sets headers correctly for downloading a file.
Parameters:
string $filename The filename as displayed to the user.
int $contentLength[optional] The length of the content.
string $contentType[optional] The content type.
Returns:
void.
Definition at line 136 of file core.php.
header_json ($ contentLength = -1)
Sets the headers correctly for JSON responses.
Returns:
void.
Parameters:
int $contentLength[optional] The content length.
Since:
2.0.0
Definition at line 191 of file core.php.
References header_no_cache().
header_no_cache ($ contentLength = -1, $ contentType = 'text/html', $ charset = 'utf-8')
Sets the headers correctly for no cache pages.
Returns:
void.
Parameters:
int $contentLength[optional] The content length.
string $contentType[optional] The content type.
string $charset[optional] The character set.
Since:
2.0.0
Definition at line 165 of file core.php.
Referenced by header_json().
is_even ($ number)
Checks if a number is even.
Parameters:
int $number The number.
Returns:
bool TRUE if number is even, FALSE otherwise.
Definition at line 28 of file core.php.
is_odd ($ number)
Checks if a number is odd.
Parameters:
int $number The number.
Returns:
bool TRUE if number is odd, FALSE otherwise.
Definition at line 21 of file core.php.
ltrim_word ($ str, $ word, $ caseSensitive = true)
Returns a string with words removed from the begining.
Removes all proceding whitespace as well.
Returns:
string Returns string without word if found, original string otherwise.
Parameters:
string $str The string to manipulate.
string $word The word to remove.
bool $caseSensitive[optional] Use case sensitive searching.
Definition at line 602 of file core.php.
move_element (array $ array, $ index, $ direction)
Moves an element within an array.
Parameters:
array $array The array.
int $index The item to move.
mixed $direction The direction to move the item as a positive or negative integer. The words "up" or "down" may also be used.
Returns:
mixed The array on success, or FALSE on failure.
Warning:
Only works on numerically indexed arrays.
Definition at line 203 of file core.php.
pre_r ($ expression, $ return = false)
Returns output of print_r enclosed in .
 tags.
Returns:
 string The output of print_r enclosed in  tags.
Parameters:
mixed  $expression The expression to be printed.
bool  $return[optional] Set to TRUE to return output, FALSE to print.
Definition at line 427 of file core.php.
quote ($ string)
Returns the string surrounded by double quotes.
Returns:
string The quoted string.
Definition at line 309 of file core.php.
Referenced by Boo_Format::format(), and Boo_Validator::validate().
remove_flag ($ flags, $ flagRemove)
Removes a flag from a set of flags.
Returns:
int Returns the result after the flag removal.
Parameters:
int $flags The original flag set.
int $flagRemove The flag to remove.
Definition at line 417 of file core.php.
rmdirr ($ dirname)
Delete a file, or a folder and its contents.
Author:
Aidan Lister <aidan@php.net>
Version:
1.0.3
Link:
http://aidanlister.com/repos/v/function.rmdirr.php
Parameters:
string $dirname Directory to delete.
Returns:
bool Returns TRUE on success, FALSE on failure. Public Domain
Definition at line 68 of file core.php.
if (!function_exists('stripslashes_deep')) rtrim_word ($ str, $ word, $ caseSensitive = true)
Un-quotes a quoted string recursivly.
Returns:
mixed Returns Un-quoted string or array.
Parameters:
mixed $value The input string or array. Returns a string with words removed from the end. Removes all trailing whitespace as well.
Returns:
string Returns string without word if found, original string otherwise.
Parameters:
string $str The string to manipulate.
string $word The word to remove.
bool $caseSensitive[optional] Use case sensitive searching.
Definition at line 573 of file core.php.
safe_scripts ()
Makes sure running scripts is allowed.
Set BOO_ALLOW_SCRIPTS to TRUE in your config file to allow scripts.
Returns:
mixed Returns TRUE if allowed, exits otherwise.
Definition at line 282 of file core.php.
safe_tests ()
Makes sure running tests is allowed.
Set BOO_ALLOW_TESTS to TRUE in your config file to allow tests.
Returns:
mixed Returns TRUE if allowed, exits otherwise.
Definition at line 297 of file core.php.
strtodb ($ string)
Formats string for insertion into database.
This function does not check for SQL injections. By default this function is identical to strtolower().
If you wish to preserve capitalization in your database or use another capitalization schema then edit this function.
Only some strings are passed though this function. For example a users first name would be however the state code would not (its always uppercase).
Parameters:
string $string The string to format
Returns:
string Returns the string in database format (default is lowercase).
Definition at line 328 of file core.php.
Referenced by Boo_User::setApartmentNumber(), Boo_User::setCity(), Boo_User::setCompany(), Boo_Group::setDescription(), Boo_User::setFirstName(), Boo_User::setLastName(), Boo_Group::setName(), and Boo_User::setStreet().
truncate ($ text, $ length, $ etc = '...')
Truncates a string to a given length.
If the string ends in a punctuation mark then it is removed before applying $etc.
Punctuation marks include [.!?:;,-] and the space character.
Parameters:
string $text The text to truncate.
int $length The length to truncate to.
string $etc[optional] Addition to the string after truncating. Defaults to ellipsis.
Returns:
string Returns truncated string plus addition if supplied.
Definition at line 358 of file core.php.
References $text.
word_bool ($ word)
Returns TRUE if the word equals "true".
Parameters:
string $word The word to test.
Returns:
bool TRUE if string equals "true", FALSE otherwise.
Definition at line 53 of file core.php.
Referenced by Boo_Html_Form_Xml::handleValidateXml().
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.