API Documentation for Boo-2.0.x: /var/www/Boo-2.0.0/tests/html-all.php File Reference
html-all.php File Reference
Used for testing the Boo_Html object.
Variables
$elements = Boo_Html::getStandardElements()
$empty = new Boo_Html_Empty
foreach($elements as $key=> $value) $input = new Boo_Html_Input_Button
$text = htmlspecialchars($input->html())
Detailed Description
Used for testing the Boo_Html object.
Displays one of each HTML element.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2008 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
See also:
Boo_Html
Definition in file html-all.php.
Variable Documentation
$elements = Boo_Html::getStandardElements()
Definition at line 26 of file html-all.php.
$empty = new Boo_Html_Empty
Definition at line 125 of file html-all.php.
$input = new Boo_Html_Input_Button
Definition at line 43 of file html-all.php.
Referenced by Boo_Html_Form_Xml::handleFormControlChild().
$text = htmlspecialchars($input->html())
Definition at line 46 of file html-all.php.
Referenced by Boo_Csv::getFields(), Boo_Twitter::newMessage(), and truncate().
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.