API Documentation for Boo-2.0.x: /var/www/Boo-2.0.0/functions/superglobal.php File Reference
superglobal.php File Reference
Superglobal functions file.
Functions
_cookie ($key)
Returns a value from $_COOKIE.
_env ($key)
Returns a value from $_ENV.
_files ($key)
Returns a value from $_FILES.
_get ($key)
Returns a value from $_GET.
_post ($key)
Returns a value from $_POST.
_request ($key)
Returns a value from $_REQUEST.
_server ($key)
Returns a value from $_SERVER.
_session ($key)
Returns a value from $_SESSION.
globals ($key)
Returns a value from $GLOBALS.
Detailed Description
Superglobal functions file.
This file provides superglobal functions used by Boo.
License:
http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License
Link:
http://code.ramaboo.com/ Boo Framework
Copyright:
2009 David Singer
Author:
David Singer <david@ramaboo.com>
Version:
2.0.1
Definition in file superglobal.php.
Function Documentation
_cookie ($ key)
Returns a value from $_COOKIE.
Parameters:
string $key The key for array $_COOKIE.
Returns:
mixed The value from $_COOKIE or FALSE if not found.
Definition at line 111 of file superglobal.php.
_env ($ key)
Returns a value from $_ENV.
Parameters:
string $key The key for array $_ENV.
Returns:
mixed The value from $_ENV or FALSE if not found.
Definition at line 153 of file superglobal.php.
_files ($ key)
Returns a value from $_FILES.
Parameters:
string $key The key for array $_FILES.
Returns:
mixed The value from $_FILES or FALSE if not found.
Definition at line 97 of file superglobal.php.
_get ($ key)
Returns a value from $_GET.
Parameters:
string $key The key for array $_GET.
Returns:
mixed The value from $_GET or FALSE if not found.
Definition at line 49 of file superglobal.php.
_post ($ key)
Returns a value from $_POST.
Parameters:
string $key The key for array $_POST.
Returns:
mixed The value from $_POST or FALSE if not found.
Definition at line 63 of file superglobal.php.
References array_trim().
Referenced by Boo_Html_Form_Xml::handleValidateXml(), Boo_Html_Textarea::htmlOpen(), and Boo_Html_Input::htmlOpen().
_request ($ key)
Returns a value from $_REQUEST.
Parameters:
string $key The key for array $_REQUEST.
Returns:
mixed The value from $_REQUEST or FALSE if not found.
Definition at line 139 of file superglobal.php.
_server ($ key)
Returns a value from $_SERVER.
Parameters:
string $key The key for array $_SERVER.
Returns:
mixed The value from $_SERVER or FALSE if not found.
Definition at line 35 of file superglobal.php.
Referenced by Boo_User::auth(), and Boo_User::verifyUserIdHash().
_session ($ key)
Returns a value from $_SESSION.
Parameters:
string $key The key for array $_SESSION.
Returns:
mixed The value from $_SESSION or FALSE if not found.
Definition at line 125 of file superglobal.php.
globals ($ key)
Returns a value from $GLOBALS.
Parameters:
string $key The key for array $GLOBALS.
Returns:
mixed The value from $GLOBALS or FALSE if not found.
Definition at line 21 of file superglobal.php.
Referenced by Boo_Error::__construct(), Boo_Error::dbError(), Boo_Error::getGlobals(), and Boo_Error::htmlErrorDiv().
API Documentation for Boo-2.0.x is licensed under the GNU General Public License.